package gov.sir.core.web.acciones.correccion;

public interface AwCorrecciones_Constants {

	// Html Action Messages --------------------------------

	String PAGE_REGION__DATOSANTIGUOSISTEMA_RECARGAR_ACTION = "PAGE_REGION__DATOSANTIGUOSISTEMA_RECARGAR_ACTION";
	String PAGE_REGION__DATOSANTIGUOSISTEMA_RECARGAR_ACTION_OK = "PAGE_REGION__DATOSANTIGUOSISTEMA_RECARGAR_ACTION";

	String ACT_PAGE_REGION__DATOSANTIGUOSISTEMA_RECARGAR_ACTION = "ACT_PAGE_REGION__DATOSANTIGUOSISTEMA_RECARGAR_ACTION";
	String ACT_PAGE_REGION__DATOSANTIGUOSISTEMA_RECARGAR_ACTION_OK = "ACT_PAGE_REGION__DATOSANTIGUOSISTEMA_RECARGAR_ACTION";

	// -----------------------------------------------------

        String ENVIARCORRECCIONSIMPLEAREVISIONAPROBACION_ACTION    = "ENVIARCORRECCIONSIMPLEAREVISIONAPROBACION_ACTION";
        String ENVIARCORRECCIONSIMPLEAREVISIONANALISIS_ACTION      = "ENVIARCORRECCIONSIMPLEAREVISIONANALISIS_ACTION";


        // Html Action Messages (From Update Ciudadano) ------------------------
        String FOLIOEDIT_RELOADBYUPDATECIUDADANO_EDITANOTACIONNORMAL_PAGERENDERING_PROCESS_ACTION
            = "FOLIOEDIT_RELOADBYUPDATECIUDADANO_EDITANOTACIONNORMAL_PAGERENDERING_PROCESS_ACTION";

        // ---------------------------------------------------------------------


        // Html Action Messages (correccion.padreshijos) --------------------------------


        String FOLIOEDIT_PADRESHIJOS_PADRE_ADDITEM_ACTION = "FOLIOEDIT_PADRESHIJOS_PADRE_ADDITEM_ACTION";
        String FOLIOEDIT_PADRESHIJOS_PADRE_DELITEM_ACTION = "FOLIOEDIT_PADRESHIJOS_PADRE_DELITEM_ACTION";

        String FOLIOEDIT_PADRESHIJOS_HIJO_ADDITEM_ACTION  = "FOLIOEDIT_PADRESHIJOS_HIJO_ADDITEM_ACTION";
        String FOLIOEDIT_PADRESHIJOS_HIJO_DELITEM_ACTION  = "FOLIOEDIT_PADRESHIJOS_HIJO_DELITEM_ACTION";

        // -----------------------------------------------------

        // Permisos Session Parameters --------------------------------

        String PARAM__MODEL_PERMISOS_LIST = "PARAM_PERMISOS";

        // -----------------------------------------------------



}
