/* Generated by Together */

package gov.sir.core.web.navegacion.correccion;

import javax.servlet.http.HttpServletRequest;

import org.auriga.smart.web.navegacion.ControlNavegacion;
import org.auriga.smart.web.navegacion.ControlNavegacionException;

import gov.sir.core.web.WebKeys;
import gov.sir.core.web.acciones.correccion.AWModificarFolio;
import gov.sir.core.web.navegacion.registro.ControlNavegacionSegregacion;
import gov.sir.core.eventos.correccion.EvnRespCorreccionFolioPadresHijos;
import gov.sir.core.eventos.correccion.EvnRespCorreccion;

public class ControlNavegacionModificacionFolio implements ControlNavegacion {
	
	//SIR-41(R1)	

  // bug 3562 - part1
      public static final String PAGE_ANOTACIONCANCELADORACREARSTEP0_BTNSTART__EVENTRESP_OK =
           "PAGE_ANOTACIONCANCELADORACREARSTEP0_BTNSTART__EVENTRESP_OK";
      public static final String PAGE_ANOTACIONCANCELADORACREARSTEP1_BTNBACK__EVENTRESP_OK =
           "PAGE_ANOTACIONCANCELADORACREARSTEP1_BTNBACK__EVENTRESP_OK";
      public static final String PAGE_ANOTACIONCANCELADORACREARSTEP1_BTNNEXT__EVENTRESP_OK =
           "PAGE_ANOTACIONCANCELADORACREARSTEP1_BTNNEXT__EVENTRESP_OK";

  // bug 3562 - part2
      public static final String PAGE_ANOTACIONCANCELADORAEDITARSTEP0_BTNSTART__EVENTRESP_OK =
           "PAGE_ANOTACIONCANCELADORAEDITARSTEP0_BTNSTART__EVENTRESP_OK";
      public static final String PAGE_ANOTACIONCANCELADORAEDITARSTEP1_BTNBACK__EVENTRESP_OK =
           "PAGE_ANOTACIONCANCELADORAEDITARSTEP1_BTNBACK__EVENTRESP_OK";
      public static final String PAGE_ANOTACIONCANCELADORAEDITARSTEP1_BTNNEXT__EVENTRESP_OK =
           "PAGE_ANOTACIONCANCELADORAEDITARSTEP1_BTNNEXT__EVENTRESP_OK";

   // bug 3551
   public static final String PAGE_REGION__FINISHANOTACIONCOPIARANOTACION__EVENTRESP_OK
    = "PAGE_REGION__FINISHANOTACIONCOPIARANOTACION__EVENTRESP_OK";


   // bug 3563 (segregacion/englobe)
   public static final String PAGE_REGION__STARTANOTACIONSEGREGACION__EVENTRESP_OK
  = "SEGREGACION_ANOTACION";//"PAGE_REGION__STARTANOTACIONSEGREGACION__EVENTRESP_OK";
   public static final String PAGE_REGION__STARTANOTACIONENGLOBE__EVENTRESP_OK
  = "ENGLOBAR";//"PAGE_REGION__STARTANOTACIONSEGREGACION__EVENTRESP_OK";

   public static final String PAGE_REGION__STARTANOTACIONCOPIARANOTACION__EVENTRESP_OK
  = "PAGE_REGION__STARTANOTACIONCOPIARANOTACION__EVENTRESP_OK";


   public static final String PAGE_REGION__FINISHANOTACIONSEGREGACION__EVENTRESP_OK =
        "PAGE_REGION__FINISHANOTACIONSEGREGACION__EVENTRESP_OK";
   public static final String PAGE_REGION__FINISHANOTACIONENGLOBE__EVENTRESP_OK =
        "PAGE_REGION__FINISHANOTACIONENGLOBE__EVENTRESP_OK";

    // edicion folio-padreshijos
    public static final String FOLIOEDIT_PADRESHIJOS_PADRE_ADDITEM__EVENTRESP_OK
    = EvnRespCorreccionFolioPadresHijos.FOLIOEDIT_PADRESHIJOS_PADRE_ADDITEM__EVENTRESP_OK;

    public static final String FOLIOEDIT_PADRESHIJOS_PADRE_DELITEM__EVENTRESP_OK
    = EvnRespCorreccionFolioPadresHijos.FOLIOEDIT_PADRESHIJOS_PADRE_DELITEM__EVENTRESP_OK;

    public static final String FOLIOEDIT_PADRESHIJOS_HIJO_ADDITEM__EVENTRESP_OK
    = EvnRespCorreccionFolioPadresHijos.FOLIOEDIT_PADRESHIJOS_HIJO_ADDITEM__EVENTRESP_OK;

    public static final String FOLIOEDIT_PADRESHIJOS_HIJO_DELITEM__EVENTRESP_OK
    = EvnRespCorreccionFolioPadresHijos.FOLIOEDIT_PADRESHIJOS_HIJO_DELITEM__EVENTRESP_OK;


    // actualizacion de ciudadanos en varios folios
    public static final String EVENTRESPOK_FOLIOEDIT_RELOADBYUPDATECIUDADANO_EDITANOTACIONNORMAL
        = "EVENTRESPOK_FOLIOEDIT_RELOADBYUPDATECIUDADANO_EDITANOTACIONNORMAL";

    // edicion folio-direccion definitiva

    public static final String FOLIOEDIT_DIRECCIONDEFINITIVA_DELITEM__EVENTRESP_OK
    = "FOLIOEDIT_DIRECCIONDEFINITIVA_DELITEM__EVENTRESP_OK";

    // revision-aprobar
    public static final String CORR_REVISIONAPROBACION__PRINTFORM_EVENTRESP_OK
        = EvnRespCorreccion.CORR_REVISIONAPROBACION__PRINTFORM_EVENTRESP_OK;

    // creacion anotacion-canceladora

    public static final String CANCELAR_CANCELACION__EVENTRESP_OK="CANCELAR_CANCELACION__EVENTRESP_OK";
    public static final String CANCELAR_ANOTACION__EVENTRESP_OK="CANCELAR_ANOTACION__EVENTRESP_OK";
    public static final String REFRESCAR_CANCELACION__EVENTRESP_OK="REFRESCAR_CANCELACION__EVENTRESP_OK";
    public static final String CANCELAR__EVENTRESP_OK="CANCELAR__EVENTRESP_OK";
    public static final String AGREGAR_VARIOS_CIUDADANOS_CANCELACION__EVENTRESP_OK = "AGREGAR_VARIOS_CIUDADANOS_CANCELACION__EVENTRESP_OK";
    public static final String AGREGAR_1_REGISTRO_TABLA_CIUDADANOS_CANCELACION__EVENTRESP_OK = "AGREGAR_1_REGISTRO_TABLA_CIUDADANOS_CANCELACION__EVENTRESP_OK";
    public static final String REMOVER_1_REGISTRO_TABLA_CIUDADANOS_CANCELACION__EVENTRESP_OK = "REMOVER_1_REGISTRO_TABLA_CIUDADANOS_CANCELACION__EVENTRESP_OK";
    public static final String ELIMINAR_CIUDADANO_ANOTACION_CANCELACION__EVENTRESP_OK = "ELIMINAR_CIUDADANO_ANOTACION_CANCELACION__EVENTRESP_OK";
    public static final String VALIDAR_CIUDADANO_CANCELACION__EVENTRESP_OK  = "VALIDAR_CIUDADANO_CANCELACION__EVENTRESP_OK";

    // edicion anotacion-canceladora

    public static final String CANCELAR_EDICION_CANCELACION__EVENTRESP_OK="CANCELAR_EDICION_CANCELACION__EVENTRESP_OK";
    public static final String REFRESCAR_EDICION_CANCELACION__EVENTRESP_OK="REFRESCAR_EDICION_CANCELACION__EVENTRESP_OK";
    public static final String AGREGAR_VARIOS_CIUDADANOS_EDICION_CANCELACION__EVENTRESP_OK= "AGREGAR_VARIOS_CIUDADANOS_EDICION_CANCELACION__EVENTRESP_OK";
    public static final String AGREGAR_1_REGISTRO_TABLA_CIUDADANOS_EDICION_CANCELACION__EVENTRESP_OK= "AGREGAR_1_REGISTRO_TABLA_CIUDADANOS_EDICION_CANCELACION__EVENTRESP_OK";
    public static final String REMOVER_1_REGISTRO_TABLA_CIUDADANOS_EDICION_CANCELACION__EVENTRESP_OK= "REMOVER_1_REGISTRO_TABLA_CIUDADANOS_EDICION_CANCELACION__EVENTRESP_OK";
    public static final String ELIMINAR_CIUDADANO_ANOTACION_EDICION_CANCELACION__EVENTRESP_OK= "ELIMINAR_CIUDADANO_ANOTACION_EDICION_CANCELACION__EVENTRESP_OK";
    public static final String VALIDAR_CIUDADANO_EDICION_CANCELACION__EVENTRESP_OK= "VALIDAR_CIUDADANO_EDICION_CANCELACION__EVENTRESP_OK";
    public static final String GRABAR_EDICION_CANCELACION__EVENTRESP_OK = "GRABAR_EDICION_CANCELACION__EVENTRESP_OK";

    // otros: edicion anotacion normal
    public static final String REFRESCAR_EDICION_ANOTACIONNORMAL__EVENTRESP_OK = "REFRESCAR_EDICION_ANOTACIONNORMAL__EVENTRESP_OK";

    // creacion anotacion-normal

    public static final String CRTANOTACIONNORMAL_CIUDADANO_ADDITEM__EVENTRESP_OK = "CRTANOTACIONNORMAL_CIUDADANO_ADDITEM__EVENTRESP_OK";
    public static final String CRTANOTACIONNORMAL_CIUDADANO_DELITEM__EVENTRESP_OK = "CRTANOTACIONNORMAL_CIUDADANO_DELITEM__EVENTRESP_OK";
    public static final String CRTANOTACIONNORMAL_CIUDADANO_ADDREPEATER_1FIELD__EVENTRESP_OK = "CRTANOTACIONNORMAL_CIUDADANO_ADDREPEATER_1FIELD__EVENTRESP_OK";
    public static final String CRTANOTACIONNORMAL_CIUDADANO_DELREPEATER_1FIELD__EVENTRESP_OK = "CRTANOTACIONNORMAL_CIUDADANO_DELREPEATER_1FIELD__EVENTRESP_OK";
    public static final String CRTANOTACIONNORMAL_CIUDADANO_VALIDATEITEM__EVENTRESP_OK       = "CRTANOTACIONNORMAL_CIUDADANO_VALIDATEITEM__EVENTRESP_OK";



        /** id - redireccion hacia edicion de una anotacion canceladora */
        public static final String EDITAR_CANCELACION__EVENTRESP_OK = "EDITAR_CANCELACION__EVENTRESP_OK";

        public static final String CANCELAR_EDICION_ANOTACION__EVENTRESP_OK
            = "CANCELAR_EDICION_ANOTACION__EVENTRESP_OK";

        public static final String ACEPTAR_EDICION_ANOTACION__EVENTRESP_OK
            = "ACEPTAR_EDICION_ANOTACION__EVENTRESP_OK";

        public static final String ELIMINAR_ANOTACION_TEMPORAL_EVENTRESP_OK
            = "ELIMINAR_ANOTACION_TEMPORAL_EVENTRESP_OK";

        public static final String ELIMINAR_CAMBIOS_ANOTACION_DEFINITIVA_TEMPORAL_EVENTRESP_OK
            = "ELIMINAR_CAMBIOS_ANOTACION_DEFINITIVA_TEMPORAL_EVENTRESP_OK";



        /** Constante que indica que se va validar un ciudadano de la anotación */
        public static final String VALIDAR_CIUDADANO_EDICION__EVENTRESP_OK = "VALIDAR_CIUDADANO_EDICION__EVENTRESP_OK";
        /** Constante que indica que se va a agregar un registro en la tabla de agragar ciudadanos**/
        public static final String AGREGAR_1_REGISTRO_TABLA_CIUDADANOS_EDICION__EVENTRESP_OK = "AGREGAR_1_REGISTRO_TABLA_CIUDADANOS_EDICION__EVENTRESP_OK";
        /** Constante que indica que se va a remover un registro en la tabla de agragar ciudadanos**/
        public static final String REMOVER_1_REGISTRO_TABLA_CIUDADANOS_EDICION__EVENTRESP_OK = "REMOVER_1_REGISTRO_TABLA_CIUDADANOS_EDICION__EVENTRESP_OK";


        /** Constante que indica que se van a agregar varios ciudadanos a la anotacion */
        public static final String AGREGAR_VARIOS_CIUDADANOS_EDICION__EVENTRESP_OK= "AGREGAR_VARIOS_CIUDADANOS_EDICION__EVENTRESP_OK";

        private static final String EDITAR_ANOTACION__EVENTRESP_OK = "EDITAR_ANOTACION__EVENTRESP_OK";

        private static final String ELIMINAR_CIUDADANO_EDICION__EVENTRESP_OK = "ELIMINAR_CIUDADANO_EDICION__EVENTRESP_OK";

	private static final String AGREGAR_CIUDADANO = "AGREGAR_CIUDADANO";

	private static final String AGREGAR_CIUDADANO_ANOTACION = "AGREGAR_CIUDADANO_ANOTACION";

	private static final String ELIMINAR_CIUDADANO_ANOTACION = "ELIMINAR_CIUDADANO_ANOTACION";

	private static final String EDITAR_CIUDADANO_ANOTACION = "EDITAR_CIUDADANO_ANOTACION";

	private static final String FOLIO_CREADO = "FOLIO_CREADO";

	private static final String CREACION_FOLIO_REGISTRADO = "CREACION_FOLIO_REGISTRADO";

	private static final String CARGAR_FOLIO_CORRECCION = "CARGAR_FOLIO_CORRECCION";

	private static final String CARGAR_FOLIO_ESPECIALIZADO = "CARGAR_FOLIO_ESPECIALIZADO";

	private static final String EDICION_FOLIO = "EDICION_FOLIO";

	private static final String CARGAR_DIGITACION_MASIVA = "CARGAR_DIGITACION_MASIVA";

	private static final String CARGAR_FOLIO_DIGITACION = "CARGAR_FOLIO_DIGITACION";

	private static final String CARGAR_ANOTACION = "CARGAR_ANOTACION";

	private static final String CANCELAR_ANOTACION_SESSION__EVENTRESP_OK = "CANCELAR_ANOTACION_SESSION__EVENTRESP_OK";

	private static final String CARGAR_ANOTACION_AGREGAR = "CARGAR_ANOTACION_AGREGAR";

	private static final String REGRESAR_CORRECCION = "REGRESAR_CORRECCION";

	private static final String REGRESAR_ESPECIALIZADO = "REGRESAR_ESPECIALIZADO";

	private static final String REGRESAR_DIGITACION = "REGRESAR_DIGITACION";

	public static final String SEGREGACION = "SEGREGACION";

	public static final String CONVERTIR_ANOTACION_CANCELACION = "CONVERTIR_ANOTACION_CANCELACION";
	
	/** Constante que indica que se van a agregar al la lista de ciudadanos los propietarios de una folio**/
	public static final String GUARDAR_PROPIETARIOS_AGREGAR_ANOTACION_CORRECIONES = "GUARDAR_PROPIETARIOS_AGREGAR_ANOTACION_CORRECIONES";
	/** Constante que indica que se van a agregar al la lista de ciudadanos los propietarios de una folio**/
	public static final String GUARDAR_PROPIETARIOS_ANOTACION_CANCELACION_CORRECIONES = "GUARDAR_PROPIETARIOS_ANOTACION_CANCELACION_CORRECIONES";
	/** Constante que indica que se van a agregar al la lista de ciudadanos los propietarios de una folio**/
	public static final String GUARDAR_PROPIETARIOS_EDITAR_ANOTACION_CORRECIONES = "GUARDAR_PROPIETARIOS_EDITAR_ANOTACION_CORRECIONES";
	/** Constante que indica que se van a agregar al la lista de ciudadanos los propietarios de una folio**/
	public static final String GUARDAR_PROPIETARIOS_EDITAR_CANCELACION_CORRECIONES = "GUARDAR_PROPIETARIOS_EDITAR_CANCELACION_CORRECIONES";
	
	
	/** Constante que indica que se va a consultar los ultimos propietarios de un folio*/
	public static final String GET_ULTIMOS_PROPIETARIOS = "GET_ULTIMOS_PROPIETARIOS";
	private static final String CONVERTIR_ANOTACION_ESTANDAR_OK = "CONVERTIR_ANOTACION_ESTANDAR_OK";

	public final static String REFRESCAR_ANOTACION = "REFRESCAR_ANOTACION";
	
	
	//PQ
	public static final String CONSULTAR_ANOTACIONES_FOLIO="CONSULTAR_ANOTACIONES_FOLIO"; 
	public static final String VER_DETALLES_FOLIO_EVENTRESP_OK="VER_DETALLES_FOLIO_EVENTRESP_OK";
	
	public static final String SEGREGAR = "SEGREGAR";
        public static final String ANOTACIONES_ASOCIADAS_OK ="ANOTACIONES_ASOCIADAS_OK";
	
	
	/* (non-Javadoc)
	 * @see org.auriga.smart.web.navegacion.ControlNavegacion#doStart(javax.servlet.http.HttpServletRequest)
	 */
	public void doStart(HttpServletRequest arg0) {

	}

	/* (non-Javadoc)
	 * @see org.auriga.smart.web.navegacion.ControlNavegacion#procesarNavegacion(javax.servlet.http.HttpServletRequest)
	 */
	public String procesarNavegacion(HttpServletRequest request) throws ControlNavegacionException {
		String accion = (String) request.getParameter(WebKeys.ACCION);

		if ((accion == null) || accion.equals("")) {
			throw new ControlNavegacionException("La accion enviada por la accion web no es valida");
		}

		if (accion.equals(AWModificarFolio.CARGAR_FOLIO_CORRECCION) || accion.equals(AWModificarFolio.AGREGAR_DIRECCION_CORRECCION) || accion.equals(AWModificarFolio.ELIMINAR_DIRECCION_CORRECCION)) {
			return CARGAR_FOLIO_CORRECCION;
		}

		if (accion.equals(AWModificarFolio.CARGAR_FOLIO_DIGITACION) || accion.equals(AWModificarFolio.AGREGAR_DIRECCION_DIGITACION) || accion.equals(AWModificarFolio.ELIMINAR_DIRECCION_DIGITACION)) {
			return CARGAR_FOLIO_DIGITACION;
		}

		if (accion.equals(AWModificarFolio.CARGAR_FOLIO_ESPECIALIZADO) || accion.equals(AWModificarFolio.AGREGAR_DIRECCION_ESPECIALIZADO) || accion.equals(AWModificarFolio.ELIMINAR_DIRECCION_ESPECIALIZADO)) {
			return CARGAR_FOLIO_ESPECIALIZADO;
		}

		if (accion.equals(AWModificarFolio.EDICION_FOLIO) || accion.equals(AWModificarFolio.AGREGAR_DIRECCION_EDICION)  || accion.equals(AWModificarFolio.ELIMINAR_DIRECCION_EDICION)) {
			return EDICION_FOLIO;
		}

		if (accion.equals(AWModificarFolio.CARGAR_ANOTACION)) {
			return CARGAR_ANOTACION;
		}

		if (accion.equals(AWModificarFolio.AGREGAR_CIUDADANO_ANOTACION)) {
			return AGREGAR_CIUDADANO_ANOTACION;
		}

		if (accion.equals(AWModificarFolio.ELIMINAR_CIUDADANO_ANOTACION)) {
			return ELIMINAR_CIUDADANO_ANOTACION;
		}

		if (accion.equals(AWModificarFolio.EDITAR_CIUDADANO_ANOTACION)) {
			return AGREGAR_CIUDADANO_ANOTACION;
		}

		if (accion.equals(AWModificarFolio.GUARDAR_CAMBIOS_FOLIO)) {
			return SEGREGACION;
		}
		
		if (accion.equals(AWModificarFolio.SEGREGAR)) {
			return ControlNavegacionSegregacion.SEGREGACION_HERENCIA;
		}

		if (accion.equals(AWModificarFolio.ACEPTAR_EDICION_CORRECCION) || accion.equals(AWModificarFolio.CANCELAR_EDICION_CORRECCION)) {
			return REGRESAR_CORRECCION;
		}

		if (accion.equals(AWModificarFolio.ACEPTAR_EDICION_DIGITACION) || accion.equals(AWModificarFolio.CANCELAR_EDICION_DIGITACION)) {
			return REGRESAR_DIGITACION;
		}

		if (accion.equals(AWModificarFolio.ACEPTAR_EDICION_ESPECIALIZADO) || accion.equals(AWModificarFolio.CANCELAR_EDICION_ESPECIALIZADO)) {
			return REGRESAR_ESPECIALIZADO;
		}

		if (accion.equals(AWModificarFolio.AGREGAR_CIUDADANO) || accion.equals(AWModificarFolio.ELIMINAR_CIUDADANO)) {
			return CARGAR_ANOTACION_AGREGAR;
		}

		if (accion.equals(AWModificarFolio.CARGAR_ANOTACION_AGREGAR)) {
			return CARGAR_ANOTACION_AGREGAR;
		}

		if (accion.equals(AWModificarFolio.CANCELAR_ANOTACION_SESSION)) {
			return CANCELAR_ANOTACION_SESSION__EVENTRESP_OK;
		}

		if (accion.equals(AWModificarFolio.AGREGAR_ANOTACION)) {
			String agregarAnotacion = request.getParameter(AWModificarFolio.AGREGAR_ANOTACION);

			if (agregarAnotacion.equals(AWModificarFolio.AGREGAR_ANOTACION_CORRECCION)) {
				return CARGAR_FOLIO_CORRECCION;
			}

			if (agregarAnotacion.equals(AWModificarFolio.AGREGAR_ANOTACION_ESPECIALIZADO)) {
				return CARGAR_FOLIO_ESPECIALIZADO;
			}
		}

		if (accion.equals(AWModificarFolio.ELIMINAR_ANOTACION)) {
			String eliminaranotacion = request.getParameter(AWModificarFolio.ELIMINAR_ANOTACION);

			if (eliminaranotacion.equals(AWModificarFolio.ELIMINAR_ANOTACION_CORRECCION)) {
				return CARGAR_FOLIO_CORRECCION;
			}

			if (eliminaranotacion.equals(AWModificarFolio.ELIMINAR_ANOTACION_ESPECIALIZADO)) {
				return CARGAR_FOLIO_ESPECIALIZADO;
			}
		}

		if (accion.equals(AWModificarFolio.ACEPTAR_EDICION_ANOTACION) || accion.equals(AWModificarFolio.CANCELAR_EDICION_ANOTACION)) {
                    // TODO: revisar: el siguiente parametro esta llegando "null"
			String agregarAnotacion = request.getParameter(AWModificarFolio.AGREGAR_ANOTACION);

			if (agregarAnotacion.equals(AWModificarFolio.AGREGAR_ANOTACION_CORRECCION)) {
				return CARGAR_FOLIO_CORRECCION;
			}

			if (agregarAnotacion.equals(AWModificarFolio.AGREGAR_ANOTACION_ESPECIALIZADO)) {
				return CARGAR_FOLIO_ESPECIALIZADO;
			}
			request.removeAttribute(AWModificarFolio.AGREGAR_ANOTACION);
                        if( AWModificarFolio.CANCELAR_EDICION_ANOTACION.equals( accion.trim() ) ) {
                            return CANCELAR_EDICION_ANOTACION__EVENTRESP_OK;
                        }
                        if( AWModificarFolio.ACEPTAR_EDICION_ANOTACION.equals( accion ) ){
                            return ACEPTAR_EDICION_ANOTACION__EVENTRESP_OK;
                        }

		}
		if (accion.equals(AWModificarFolio.CONSULTA_DIGITACION_MASIVA) || accion.equals(AWModificarFolio.EDITAR_FOLIO_DIGITACION_MASIVA)) {
			return CARGAR_DIGITACION_MASIVA;
		}

                 //  ----------------------------------------------------------------------------------
                 //   bug 3562
                 //  ----------------------------------------------------------------------------------
                 //  edicion-folio.anotacion-canceladora.crear --------------------------------------
                 if( AWModificarFolio.PAGE_ANOTACIONCANCELADORACREARSTEP0_BTNSTART_ACTION.equals( accion ) ) {
                     return PAGE_ANOTACIONCANCELADORACREARSTEP0_BTNSTART__EVENTRESP_OK;
                 }
                 if( AWModificarFolio.PAGE_ANOTACIONCANCELADORACREARSTEP1_BTNBACK_ACTION.equals( accion ) ) {
                     return PAGE_ANOTACIONCANCELADORACREARSTEP1_BTNBACK__EVENTRESP_OK;
                 }
                 if( AWModificarFolio.PAGE_ANOTACIONCANCELADORACREARSTEP1_BTNNEXT_ACTION.equals( accion ) ) {
                     return PAGE_ANOTACIONCANCELADORACREARSTEP1_BTNNEXT__EVENTRESP_OK;
                 }
                 //  edicion-folio.anotacion-canceladora.editar --------------------------------------
                 if( AWModificarFolio.PAGE_ANOTACIONCANCELADORAEDITARSTEP0_BTNSTART_ACTION.equals( accion ) ) {
                     return PAGE_ANOTACIONCANCELADORAEDITARSTEP0_BTNSTART__EVENTRESP_OK;
                 }
                 if( AWModificarFolio.PAGE_ANOTACIONCANCELADORAEDITARSTEP1_BTNBACK_ACTION.equals( accion ) ) {
                     return PAGE_ANOTACIONCANCELADORAEDITARSTEP1_BTNBACK__EVENTRESP_OK;
                 }
                 if( AWModificarFolio.PAGE_ANOTACIONCANCELADORAEDITARSTEP1_BTNNEXT_ACTION.equals( accion ) ) {
                     return PAGE_ANOTACIONCANCELADORAEDITARSTEP1_BTNNEXT__EVENTRESP_OK;
                 }
                 //  ----------------------------------------------------------------------------------

                // correccion.editciudadano-variosfolios.edicion

                if( AWModificarFolio.FOLIOEDIT_RELOADBYUPDATECIUDADANO_EDITANOTACIONNORMAL_PAGERENDERING_PROCESS_ACTION.equals( accion )  ){
                  // si debe actualizarse
                    return EVENTRESPOK_FOLIOEDIT_RELOADBYUPDATECIUDADANO_EDITANOTACIONNORMAL;

                }

                // correccion.anotacion.edicion
                if( AWModificarFolio.REFRESCAR_EDICION.equals( accion )  ){
                    return REFRESCAR_EDICION_ANOTACIONNORMAL__EVENTRESP_OK ;
                }


                // correccion.edicion.anotacion.2
                if( AWModificarFolio.EDITAR_ANOTACION.equals( accion ) ) {
                    return EDITAR_ANOTACION__EVENTRESP_OK;
                }
                // correccion.edicion.anotacion.2
                if( AWModificarFolio.ELIMINAR_CIUDADANO_EDICION.equals( accion ) ) {
                    return ELIMINAR_CIUDADANO_EDICION__EVENTRESP_OK;
                }
                if( AWModificarFolio.AGREGAR_VARIOS_CIUDADANOS_EDICION.equals( accion ) ){
                    return AGREGAR_VARIOS_CIUDADANOS_EDICION__EVENTRESP_OK;
                }
                if(AWModificarFolio.EDITAR_ANOTACION_CIUDADANO_EDICION.equals(accion)){
                	return AGREGAR_VARIOS_CIUDADANOS_EDICION__EVENTRESP_OK;
                }
                if( AWModificarFolio.AGREGAR_1_REGISTRO_TABLA_CIUDADANOS_EDICION.equals( accion ) ) {
                    return AGREGAR_1_REGISTRO_TABLA_CIUDADANOS_EDICION__EVENTRESP_OK;
                }
                if( AWModificarFolio.REMOVER_1_REGISTRO_TABLA_CIUDADANOS_EDICION.equals( accion ) ){
                    return REMOVER_1_REGISTRO_TABLA_CIUDADANOS_EDICION__EVENTRESP_OK;
                }
                if( AWModificarFolio.VALIDAR_CIUDADANO_EDICION.equals( accion ) ){
                    return VALIDAR_CIUDADANO_EDICION__EVENTRESP_OK;
                }
                //if( AWModificarFolio.EDITAR_CANCELACION.equals( accion  ) ) {
                //    return EDITAR_CANCELACION__EVENTRESP_OK;
                //}
                if( AWModificarFolio.ELIMINAR_ANOTACION_TEMPORAL.equals( accion ) ){
                    return ELIMINAR_ANOTACION_TEMPORAL_EVENTRESP_OK;
                }
                if( AWModificarFolio.ELIMINAR_CAMBIOS_ANOTACION_DEFINITIVA_TEMPORAL.equals( accion ) ){
                    return ELIMINAR_CAMBIOS_ANOTACION_DEFINITIVA_TEMPORAL_EVENTRESP_OK;
                }

                // ------ edicion folio-direccion definitivas

                if( AWModificarFolio.FOLIOEDIT_DIRECCIONDEFINITIVA_DELITEM_ACTION.equals( accion ) ){
                    return FOLIOEDIT_DIRECCIONDEFINITIVA_DELITEM__EVENTRESP_OK;
                }
                
                if( AWModificarFolio.FOLIOEDIT_DIRECCIONDEFINITIVA_EDITITEM_ACTION.equals( accion ) ){
                    return FOLIOEDIT_DIRECCIONDEFINITIVA_DELITEM__EVENTRESP_OK;
                }
                
                if( AWModificarFolio.EDITAR_DIRECCION_CORRECCION_ACEPTAR_DEF.equals( accion ) ){
                    return FOLIOEDIT_DIRECCIONDEFINITIVA_DELITEM__EVENTRESP_OK;
                }
                
                if( AWModificarFolio.EDITAR_DIRECCION_CORRECCION_ACEPTAR_TEMP.equals( accion ) ){
                    return FOLIOEDIT_DIRECCIONDEFINITIVA_DELITEM__EVENTRESP_OK;
                }
                
                if( AWModificarFolio.EDITAR_DIRECCION_CORRECCION_TEMP.equals( accion ) ){
                    return FOLIOEDIT_DIRECCIONDEFINITIVA_DELITEM__EVENTRESP_OK;
                }


                // ------ creacion anotacion-canceladora
                if( AWModificarFolio.CANCELAR_CANCELACION.equals( accion ) ){
                    return CANCELAR_CANCELACION__EVENTRESP_OK ;
                }
                if( AWModificarFolio.CANCELAR_ANOTACION.equals( accion ) ){
                    return CANCELAR_ANOTACION__EVENTRESP_OK ;
                }
                if( AWModificarFolio.REFRESCAR_CANCELACION.equals( accion )  ){
                    return REFRESCAR_CANCELACION__EVENTRESP_OK ;
                }
                if( AWModificarFolio.CANCELAR.equals( accion ) ){
                    return CANCELAR__EVENTRESP_OK ;
                }
                if( AWModificarFolio.CARGAR_DESCRIPCION_NATURALEZA_CANCELACION.equals( accion ) ){
                    return CANCELAR__EVENTRESP_OK ;
                }
                if( AWModificarFolio.CARGAR_DESCRIPCION_NATURALEZA_EDITAR_ANOTACION.equals( accion ) ){
                    return CARGAR_ANOTACION ;
                }
                if( AWModificarFolio.AGREGAR_VARIOS_CIUDADANOS_CANCELACION.equals( accion )  ){
                    return AGREGAR_VARIOS_CIUDADANOS_CANCELACION__EVENTRESP_OK ;
                }
                if( AWModificarFolio.AGREGAR_1_REGISTRO_TABLA_CIUDADANOS_CANCELACION.equals( accion ) ){
                    return AGREGAR_1_REGISTRO_TABLA_CIUDADANOS_CANCELACION__EVENTRESP_OK ;
                }
                if(  AWModificarFolio.REMOVER_1_REGISTRO_TABLA_CIUDADANOS_CANCELACION.equals( accion )  ){
                    return REMOVER_1_REGISTRO_TABLA_CIUDADANOS_CANCELACION__EVENTRESP_OK ;
                }
                if( AWModificarFolio.ELIMINAR_CIUDADANO_ANOTACION_CANCELACION.equals( accion )  ){
                    return ELIMINAR_CIUDADANO_ANOTACION_CANCELACION__EVENTRESP_OK ;
                }
                if( AWModificarFolio.VALIDAR_CIUDADANO_CANCELACION.trim().equals( accion ) ){
                    return VALIDAR_CIUDADANO_CANCELACION__EVENTRESP_OK ;
                }
                // ------ edicion anotacion-canceladora
                if(  AWModificarFolio.CANCELAR_EDICION_CANCELACION.equals( accion )  ){
                    return CANCELAR_EDICION_CANCELACION__EVENTRESP_OK ;
                }
                if( AWModificarFolio.REFRESCAR_EDICION_CANCELACION.equals( accion )  ){
                    return REFRESCAR_EDICION_CANCELACION__EVENTRESP_OK ;
                }
                if( AWModificarFolio.AGREGAR_VARIOS_CIUDADANOS_EDICION_CANCELACION.equals( accion )  ){
                    return AGREGAR_VARIOS_CIUDADANOS_EDICION_CANCELACION__EVENTRESP_OK ;
                }
                if( AWModificarFolio.AGREGAR_1_REGISTRO_TABLA_CIUDADANOS_EDICION_CANCELACION.equals( accion ) ){
                    return AGREGAR_1_REGISTRO_TABLA_CIUDADANOS_EDICION_CANCELACION__EVENTRESP_OK ;
                }
                if(  AWModificarFolio.REMOVER_1_REGISTRO_TABLA_CIUDADANOS_EDICION_CANCELACION.equals( accion )  ){
                    return REMOVER_1_REGISTRO_TABLA_CIUDADANOS_EDICION_CANCELACION__EVENTRESP_OK ;
                }
                if( AWModificarFolio.ELIMINAR_CIUDADANO_ANOTACION_EDICION_CANCELACION.equals( accion ) ){
                    return ELIMINAR_CIUDADANO_ANOTACION_EDICION_CANCELACION__EVENTRESP_OK ;
                }
                if( AWModificarFolio.VALIDAR_CIUDADANO_EDICION_CANCELACION.equals( accion )  ){
                    return VALIDAR_CIUDADANO_EDICION_CANCELACION__EVENTRESP_OK;
                }
                if( AWModificarFolio.GRABAR_EDICION_CANCELACION.equals( accion ) ) {
                    return GRABAR_EDICION_CANCELACION__EVENTRESP_OK;
                }

                // ------ creacion anotacion-normal (varios-ciudadanos)
                if( AWModificarFolio.CRTANOTACIONNORMAL_CIUDADANO_ADDITEM.equals( accion ) ){
                    return CRTANOTACIONNORMAL_CIUDADANO_ADDITEM__EVENTRESP_OK ;
                }
                if (AWModificarFolio.EDITAR_ANOTACION_CIUDADANO.equals( accion )){
                	return CRTANOTACIONNORMAL_CIUDADANO_ADDITEM__EVENTRESP_OK;
                }
                if( AWModificarFolio.CRTANOTACIONNORMAL_CIUDADANO_DELITEM.equals( accion ) ){
                    return CRTANOTACIONNORMAL_CIUDADANO_DELITEM__EVENTRESP_OK ;
                }
                if( AWModificarFolio.CRTANOTACIONNORMAL_CIUDADANO_ADDREPEATER_1FIELD.equals( accion ) ){
                    return CRTANOTACIONNORMAL_CIUDADANO_ADDREPEATER_1FIELD__EVENTRESP_OK ;
                }
                if( AWModificarFolio.CRTANOTACIONNORMAL_CIUDADANO_DELREPEATER_1FIELD.equals( accion ) ){
                    return CRTANOTACIONNORMAL_CIUDADANO_DELREPEATER_1FIELD__EVENTRESP_OK ;
                }
                if( AWModificarFolio.CRTANOTACIONNORMAL_CIUDADANO_VALIDATEITEM.equals( accion ) ){
                    return CRTANOTACIONNORMAL_CIUDADANO_VALIDATEITEM__EVENTRESP_OK;
                }
                // ------ folio padres-hijos edit
                if( AWModificarFolio.FOLIOEDIT_PADRESHIJOS_PADRE_ADDITEM_ACTION.equals( accion ) ){
                    return FOLIOEDIT_PADRESHIJOS_PADRE_ADDITEM__EVENTRESP_OK;
                }
                if( AWModificarFolio.FOLIOEDIT_PADRESHIJOS_PADRE_DELITEM_ACTION.equals( accion ) ){
                    return FOLIOEDIT_PADRESHIJOS_PADRE_DELITEM__EVENTRESP_OK;
                }
                if( AWModificarFolio.FOLIOEDIT_PADRESHIJOS_HIJO_ADDITEM_ACTION.equals( accion ) ){
                    return FOLIOEDIT_PADRESHIJOS_HIJO_ADDITEM__EVENTRESP_OK;
                }
                if( AWModificarFolio.FOLIOEDIT_PADRESHIJOS_HIJO_DELITEM_ACTION.equals( accion ) ){
                    return FOLIOEDIT_PADRESHIJOS_HIJO_DELITEM__EVENTRESP_OK;
                }

                if( AWModificarFolio.CONVERTIR_ANOTACION_CANCELACION.equals( accion ) ){
                    return CONVERTIR_ANOTACION_CANCELACION;
                }

                // bug 3551 (copiar-anotacion) -----
                if( AWModificarFolio.PAGE_REGION__STARTANOTACIONCOPIARANOTACION_ACTION.equals( accion ) ){
                    return PAGE_REGION__STARTANOTACIONCOPIARANOTACION__EVENTRESP_OK;
                }

                // ---------------------------------

                // bug 3563 (segregacion/englobe) -----
                if( AWModificarFolio.PAGE_REGION__STARTANOTACIONSEGREGACION_ACTION.equals( accion ) ){
                    return PAGE_REGION__STARTANOTACIONSEGREGACION__EVENTRESP_OK;
                }
                if( AWModificarFolio.PAGE_REGION__STARTANOTACIONENGLOBE_ACTION.equals( accion ) ){
                    return PAGE_REGION__STARTANOTACIONENGLOBE__EVENTRESP_OK;
                }
                if( AWModificarFolio.PAGE_REGION__FINISHANOTACIONSEGREGACION_ACTION.equals( accion ) ){
                    return PAGE_REGION__FINISHANOTACIONSEGREGACION__EVENTRESP_OK;
                }
                if( AWModificarFolio.PAGE_REGION__FINISHANOTACIONENGLOBE_ACTION.equals( accion ) ){
                    return PAGE_REGION__FINISHANOTACIONENGLOBE__EVENTRESP_OK;
                }
               
                
                if (accion.equals(AWModificarFolio.GET_ULTIMOS_PROPIETARIOS)){
        			return GET_ULTIMOS_PROPIETARIOS;	
        		} else if (accion.equals(AWModificarFolio.CANCELAR_PROPIETARIOS)){
        			String paramVistaAnterior = (String) request.getSession().getAttribute("paramVistaAnterior");
        			if (paramVistaAnterior.equals("AGREGAR_ANOTACION_CORRECIONES")){
        				return GUARDAR_PROPIETARIOS_AGREGAR_ANOTACION_CORRECIONES;
        			} else if (paramVistaAnterior.equals("ANOTACION_CANCELACION_CORRECIONES")){
        				return GUARDAR_PROPIETARIOS_ANOTACION_CANCELACION_CORRECIONES;
        			} else if (paramVistaAnterior.equals("EDITAR_ANOTACION_CORRECCIONES")){
        				return GUARDAR_PROPIETARIOS_EDITAR_ANOTACION_CORRECIONES;
        			} else if (paramVistaAnterior.equals("EDITAR_CANCELACION_CORRECCIONES")){
        				return GUARDAR_PROPIETARIOS_EDITAR_CANCELACION_CORRECIONES;
        			}
        		} else if (accion.equals(AWModificarFolio.GUARDAR_PROPIETARIOS)){
        			String paramVistaAnterior = (String) request.getSession().getAttribute("paramVistaAnterior");
        			if (paramVistaAnterior.equals("AGREGAR_ANOTACION_CORRECIONES")){
        				return GUARDAR_PROPIETARIOS_AGREGAR_ANOTACION_CORRECIONES;
        			} else if (paramVistaAnterior.equals("ANOTACION_CANCELACION_CORRECIONES")){
        				return GUARDAR_PROPIETARIOS_ANOTACION_CANCELACION_CORRECIONES;
        			} else if (paramVistaAnterior.equals("EDITAR_ANOTACION_CORRECCIONES")){
        				return GUARDAR_PROPIETARIOS_EDITAR_ANOTACION_CORRECIONES;
        			} else if (paramVistaAnterior.equals("EDITAR_CANCELACION_CORRECCIONES")){
        				return GUARDAR_PROPIETARIOS_EDITAR_CANCELACION_CORRECIONES;
        			}
        		} else if (accion.equals(AWModificarFolio.CONVERTIR_ANOTACION_ESTANDAR))
        		{
        			return CONVERTIR_ANOTACION_ESTANDAR_OK;
        		} else if(accion.equals(AWModificarFolio.REFRESCAR_ANOTACION)){
        			return REFRESCAR_ANOTACION;
        		}else if(CONSULTAR_ANOTACIONES_FOLIO.equals(accion)){
        			return VER_DETALLES_FOLIO_EVENTRESP_OK;
        			
        		}else if(AWModificarFolio.CAMBIAR_ANOTACIONES_CORRECCION.equals(accion)){
        			return FOLIOEDIT_PADRESHIJOS_HIJO_DELITEM__EVENTRESP_OK;
        		}else if(AWModificarFolio.ANOTACIONES_ASOCIADAS.equals(accion)){
        			return ANOTACIONES_ASOCIADAS_OK;
        		}
                // ------
                // TODO: probar por qué esta AGREGAR_CIUDADANO
		return AGREGAR_CIUDADANO; // return null;

	}

	/* (non-Javadoc)
	 * @see org.auriga.smart.web.navegacion.ControlNavegacion#doEnd(javax.servlet.http.HttpServletRequest)
	 */
	public void doEnd(HttpServletRequest arg0) {

	}
}
