package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.TipoTarifa;


/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class ActoresRepartoNotarialEnhanced extends Enhanced 
{ 

    private String idCirculo; // pk 
    private String coordinadorReparto;
    private String directorReparto;
    
    public ActoresRepartoNotarialEnhanced() {
    }

	public static ActoresRepartoNotarialEnhanced enhance (
			TipoTarifa tipoTarifa)
	{
		return (ActoresRepartoNotarialEnhanced)Enhanced.enhance(tipoTarifa);
	}
	


    public String getCoordinadorReparto() {
		return coordinadorReparto;
	}

	public void setCoordinadorReparto(String coordinadorReparto) {
		this.coordinadorReparto = coordinadorReparto;
	}

	public String getDirectorReparto() {
		return directorReparto;
	}

	public void setDirectorReparto(String directorReparto) {
		this.directorReparto = directorReparto;
	}

	public String getIdCirculo() {
		return idCirculo;
	}

	public void setIdCirculo(String idCirculo) {
		this.idCirculo = idCirculo;
	}
}
