package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.AlcanceGeografico;



/*
 * Generated by JDO Genie (version:3.2.0beta2 (28 Jun 2004))
 */
public class AlcanceGeograficoEnhanced extends Enhanced{

	public static final String TIPO_LOCAL = "0";
	public static final String TIPO_NACIONAL = "1";
    
    private String idAlcanceGeografico; // pk 
    private String nombre;

    public AlcanceGeograficoEnhanced() {
    }

    public String getIdAlcanceGeografico() {
        return idAlcanceGeografico;
    }

    public void setIdAlcanceGeografico(String idAlcanceGeografico) {
        this.idAlcanceGeografico = idAlcanceGeografico;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public static AlcanceGeograficoEnhanced enhance(AlcanceGeografico alcanceGeografico) {
		return (AlcanceGeograficoEnhanced) Enhanced.enhance(alcanceGeografico);
	}


}