package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.AumentoRecibo;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class AumentoReciboEnhanced extends Enhanced {

    private String idAumentoRecibo; // pk 
    private Date fechaCreacion;
    private String motivo;
    private long numeroRecibo;
    private UsuarioEnhanced usuario;

    public AumentoReciboEnhanced() {
    }

    public String getIdAumentoRecibo() {
        return idAumentoRecibo;
    }

    public void setIdAumentoRecibo(String idAumentoRecibo) {
        this.idAumentoRecibo = idAumentoRecibo;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getMotivo() {
        return motivo;
    }

    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    public long getNumeroRecibo() {
        return numeroRecibo;
    }

    public void setNumeroRecibo(long numeroRecibo) {
        this.numeroRecibo = numeroRecibo;
    }

    public UsuarioEnhanced getUsuario() {
        return usuario;
    }

    public void setUsuario(UsuarioEnhanced usuario) {
        this.usuario = usuario;
    }
    
 
	public static AumentoReciboEnhanced enhance(AumentoRecibo aumento) {
		return (AumentoReciboEnhanced) Enhanced.enhance(aumento);
	}
}