package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.Categoria;

import java.util.List;
import java.util.ArrayList;
import java.util.Collections;

/*
 * Generated by JDO Genie (version:3.2.0beta7 (20 Sep 2004))
 */
public class CategoriaEnhanced extends Enhanced{

    private String idCategoria; // pk 
    private String nombre;
    private UsuarioEnhanced usuario;
    private double unidadMin;
    private double unidadMax;
    private double valorMin;
    private double valorMax;
    private List oficinasOrigen = new ArrayList(); // contains OficinaCategoriaEnhanced  inverse OficinaCategoriaEnhanced.categoria
    private boolean activo = true;
    
    public CategoriaEnhanced() {
    }

    public String getIdCategoria() {
        return idCategoria;
    }

    public void setIdCategoria(String idCategoria) {
        this.idCategoria = idCategoria;
    }

	public UsuarioEnhanced getUsuario() {
		return usuario;
	}

	public void setUsuario(UsuarioEnhanced usuario) {
		this.usuario = usuario;
	}


    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public double getUnidadMax() {
        return unidadMax;
    }

    public void setUnidadMax(double unidadMax) {
        this.unidadMax = unidadMax;
    }

    public double getValorMax() {
        return valorMax;
    }

    public void setValorMax(double valorMax) {
        this.valorMax = valorMax;
    }

    public List getOficinasOrigens() {
        return Collections.unmodifiableList(oficinasOrigen);
    }

    public boolean addOficinasOrigen(OficinaCategoriaEnhanced newOficinasOrigen) {
        return oficinasOrigen.add(newOficinasOrigen);
    }

    public boolean removeOficinasOrigen(OficinaCategoriaEnhanced oldOficinasOrigen) {
        return oficinasOrigen.remove(oldOficinasOrigen);
    }
    

	public static CategoriaEnhanced enhance(Categoria acto) {
		return (CategoriaEnhanced) Enhanced.enhance(acto);
	}

    /**
	 * @return
	 */
	public double getUnidadMin() {
		return unidadMin;
	}

	/**
	 * @param d
	 */
	public void setUnidadMin(double d) {
		unidadMin = d;
	}

	/**
	 * @return
	 */
	public double getValorMin() {
		return valorMin;
	}

	/**
	 * @param d
	 */
	public void setValorMin(double d) {
		valorMin = d;
	}
	

	public int hashCode() {
		int result = 0;
		result = 29 * result + (idCategoria != null ? idCategoria.hashCode() : 0);
		return result;
	}

	public boolean isActivo() {
		return activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}