package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.CirculoImpresora;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class CirculoImpresoraEnhanced extends Enhanced{

    private String idCirculo; // pk 
    private String idImpresora; // pk 
    private String idTipoImprimible; //pk
    private Date fechaCreacion;
    private CirculoEnhanced circulo;
    private boolean predeterminada;

    public boolean isPredeterminada() {
		return predeterminada;
	}

	public void setPredeterminada(boolean predeterminada) {
		this.predeterminada = predeterminada;
	}

	public CirculoImpresoraEnhanced() {
    }

    public String getIdCirculo() {
        return idCirculo;
    }

    public void setIdCirculo(String idCirculo) {
        this.idCirculo = idCirculo;
    }

    public String getIdImpresora() {
        return idImpresora;
    }

    public void setIdImpresora(String idImpresora) {
        this.idImpresora = idImpresora;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public CirculoEnhanced getCirculo() {
        return circulo;
    }

    public void setCirculo(CirculoEnhanced circulo) {
        this.circulo = circulo;
        setIdCirculo(circulo.getIdCirculo());
    }
    

	public static CirculoImpresoraEnhanced enhance(CirculoImpresora circuloImpresora) {
		return (CirculoImpresoraEnhanced) Enhanced.enhance(circuloImpresora);
	}

    public String getIdTipoImprimible() {
		return idTipoImprimible;
	}

	public void setIdTipoImprimible(String idTipoImprimible) {
		this.idTipoImprimible = idTipoImprimible;
	}
}