package gov.sir.core.negocio.modelo.jdogenie;


/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class CiudadanoTMP {

    private String idCiudadanoTmp; // pk
    private String tipoPersona;
    private String sexo;
    private String apellido1;
    private String apellido2;
    private String documento;
    private String nombre;
    private boolean solicitante;
    private String telefono;
    private String tipoDocumento;
    private String idCirculo;
    private String numeroRadicacion;

    public String getIdCirculo() {
		return idCirculo;
	}

	public void setIdCirculo(String idCirculo) {
		this.idCirculo = idCirculo;
	}

	public CiudadanoTMP() {
    }
    
    public CiudadanoTMP(CiudadanoEnhanced ciud){
    	idCiudadanoTmp = ciud.getIdCiudadano();
        tipoPersona = ciud.getTipoPersona();
        sexo = ciud.getSexo();
    	apellido1 = ciud.getApellido1();
    	apellido2 = ciud.getApellido2();
    	documento = ciud.getDocumento();
    	nombre = ciud.getNombre();
    	solicitante = ciud.isSolicitante();
    	telefono = ciud.getTelefono();
    	tipoDocumento = ciud.getTipoDoc();
    	idCirculo = ciud.getIdCirculo();
    }
    
    public CiudadanoEnhanced getDefinitivo(){
    	CiudadanoEnhanced ciud = new CiudadanoEnhanced();
    	ciud.setIdCiudadano(idCiudadanoTmp);
        ciud.setTipoPersona(tipoPersona);
        ciud.setSexo(sexo);
    	ciud.setApellido1(apellido1);
    	ciud.setApellido2(apellido2);
    	ciud.setDocumento(documento);
    	ciud.setNombre(nombre);
    	ciud.setSolicitante(solicitante);
    	ciud.setTelefono(telefono);
    	ciud.setTipoDoc(tipoDocumento);
    	ciud.setIdCirculo(idCirculo);
    	return ciud;
    }
    

    public String getIdCiudadanoTmp() {
        return idCiudadanoTmp;
    }

    public void setIdCiudadanoTmp(String idCiudadanoTmp) {
        this.idCiudadanoTmp = idCiudadanoTmp;
    }

    public String getTipoPersona() {
        return tipoPersona;
    }

    public void setTipoPersona(String tipoPersona) {
        this.tipoPersona = tipoPersona;
    }

    public String getSexo() {
        return sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    
    public String getApellido1() {
        return apellido1;
    }

    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    public String getApellido2() {
        return apellido2;
    }

    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    public String getDocumento() {
        return documento;
    }

    public void setDocumento(String documento) {
        this.documento = documento;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getTipoDocumento() {
        return tipoDocumento;
    }

    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    /**
	 * @return
	 */
	public boolean isSolicitante() {
		return solicitante;
	}

	/**
	 * @param b
	 */
	public void setSolicitante(boolean b) {
		solicitante = b;
	}

	public String getNumeroRadicacion() {
		return numeroRadicacion;
	}

	public void setNumeroRadicacion(String numeroRadicacion) {
		this.numeroRadicacion = numeroRadicacion;
	}

}
