package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.CiudadanoProhibicion;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class CiudadanoProhibicionEnhanced extends Enhanced{

    private String idCiudadano; // pk 
    private String idProhibicion; // pk 
    private String idCirculo; 
    private Date fechaCreacion;
    private Date fechaFinal;
    private Date fechaInicial;
    private CiudadanoEnhanced ciudadano; // inverse CiudadanoEnhanced.ciudadanoProhibicionEnhanced
    private ProhibicionEnhanced prohibicion;
    private String comentario;
    private UsuarioEnhanced usuarioCreacion;
    private UsuarioEnhanced usuarioEliminacion;
    private String comentarioAnulacion;

    public CiudadanoProhibicionEnhanced() {
    }

    public String getIdCirculo() {
		return idCirculo;
	}

	public void setIdCirculo(String idCirculo) {
		this.idCirculo = idCirculo;
	}
	
    public String getIdCiudadano() {
        return idCiudadano;
    }

    public void setIdCiudadano(String idCiudadano) {
        this.idCiudadano = idCiudadano;
    }

    public String getIdProhibicion() {
        return idProhibicion;
    }

    public void setIdProhibicion(String idProhibicion) {
        this.idProhibicion = idProhibicion;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Date getFechaFinal() {
        return fechaFinal;
    }

    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }

    public Date getFechaInicial() {
        return fechaInicial;
    }

    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }

    public CiudadanoEnhanced getCiudadano() {
        return ciudadano;
    }

    public void setCiudadano(CiudadanoEnhanced ciudadano) {
        this.ciudadano = ciudadano;
        setIdCiudadano(ciudadano.getIdCiudadano());
    }

    public ProhibicionEnhanced getProhibicion() {
        return prohibicion;
    }

    public void setProhibicion(ProhibicionEnhanced prohibicion) {
        this.prohibicion = prohibicion;
        setIdProhibicion(prohibicion.getIdProhibicion());
    }
    
   
	public static CiudadanoProhibicionEnhanced enhance(CiudadanoProhibicion ciudadanoP){
	   return (CiudadanoProhibicionEnhanced)Enhanced.enhance(ciudadanoP);
	}

    /**
	 * @return
	 */
	public String getComentario() {
		return comentario;
	}

	/**
	 * @param string
	 */
	public void setComentario(String string) {
		comentario = string;
	}

	/** Retorna el Usuario que creó esta instancia
	 * @return
	 */
	public UsuarioEnhanced getUsuarioCreacion() {
		return usuarioCreacion;
	}

	/** Modifica el Usuario que creó esta instancia
	 * @param string
	 */
	public void setUsuarioCreacion(UsuarioEnhanced usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}
	
	/** Retorna el Usuario que eliminó esta instancia
	 * @return
	 */
	public UsuarioEnhanced getUsuarioEliminacion() {
		return usuarioEliminacion;
	}

	/** Modifica el Usuario que eliminó esta instancia
	 * @param string
	 */
	public void setUsuarioEliminacion(UsuarioEnhanced usuarioEliminacion) {
		this.usuarioEliminacion = usuarioEliminacion;
	}

	public String getComentarioAnulacion() {
		return comentarioAnulacion;
	}

	public void setComentarioAnulacion(String comentarioAnulacion) {
		this.comentarioAnulacion = comentarioAnulacion;
	}
	
}