package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.Complementacion;



/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class ComplementacionEnhanced extends Enhanced{

    private String idComplementacion; // pk 
    private String complementacion;
    private String complementacionConflictiva;

    public ComplementacionEnhanced() {
    }

    public String getIdComplementacion() {
        return idComplementacion;
    }

    public void setIdComplementacion(String idComplementacion) {
        this.idComplementacion = idComplementacion;
    }

    public String getComplementacion() {
        return complementacion;
    }

    public void setComplementacion(String complementacion) {
        this.complementacion = complementacion;
    }
    
	public static ComplementacionEnhanced enhance(Complementacion complementacion){
	   return (ComplementacionEnhanced)Enhanced.enhance(complementacion);
	}

	public String getComplementacionConflictiva() {
		return complementacionConflictiva;
	}

	public void setComplementacionConflictiva(String complementacionConflictiva) {
		this.complementacionConflictiva = complementacionConflictiva;
	}

}