package gov.sir.core.negocio.modelo.jdogenie;

import java.util.Date;

import gov.sir.core.negocio.modelo.Complementacion;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class ComplementacionConflictivaAuditoriaEnhanced extends Enhanced{

	private String idAuditoria; // pk
	private String idComplementacion; // pk 
    private String complementacion;
    private String complementacionConflictiva;
    private Date fechaCreacion;
    private UsuarioEnhanced usuario; // inverse Usuario.Auditoria

    public ComplementacionConflictivaAuditoriaEnhanced() {
    }

    public String getIdComplementacion() {
        return idComplementacion;
    }

    public void setIdComplementacion(String idComplementacion) {
        this.idComplementacion = idComplementacion;
    }

    public String getComplementacion() {
        return complementacion;
    }

    public void setComplementacion(String complementacion) {
        this.complementacion = complementacion;
    }
    
	public static ComplementacionConflictivaAuditoriaEnhanced enhance(Complementacion complementacion){
	   return (ComplementacionConflictivaAuditoriaEnhanced)Enhanced.enhance(complementacion);
	}

	public String getComplementacionConflictiva() {
		return complementacionConflictiva;
	}

	public void setComplementacionConflictiva(String complementacionConflictiva) {
		this.complementacionConflictiva = complementacionConflictiva;
	}
	
	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getIdAuditoria() {
		return idAuditoria;
	}

	public void setIdAuditoria(String idAuditoria) {
		this.idAuditoria = idAuditoria;
	}

	public UsuarioEnhanced getUsuario() {
		return usuario;
	}

	public void setUsuario(UsuarioEnhanced usuario) {
		this.usuario = usuario;
	}



}