package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.Departamento;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;



/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class DepartamentoEnhanced  extends Enhanced{
    private String idDepartamento; // pk 
    private String nombre;
    private List municipios = new ArrayList(); // contains Municipio  inverse Municipio.departamento
    private UsuarioEnhanced usuario;
	
    public DepartamentoEnhanced() {
    }

    public String getIdDepartamento() {
        return idDepartamento;
    }

    public void setIdDepartamento(String idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public List getMunicipios() {
        return Collections.unmodifiableList(municipios);
    }

    public boolean addMunicipio(MunicipioEnhanced newMunicipio) {
        return municipios.add(newMunicipio);
    }

    public boolean removeMunicipio(MunicipioEnhanced oldMunicipio) {
        return municipios.remove(oldMunicipio);
    }
    
	public static DepartamentoEnhanced enhance(Departamento departamento){
	   return (DepartamentoEnhanced)Enhanced.enhance(departamento);
	}
	public UsuarioEnhanced getUsuario() {
		return usuario;
	}

	public void setUsuario(UsuarioEnhanced usuario) {
		this.usuario = usuario;
	}


    public boolean equals(Object o) {
		if (this == o) {
			return true;
		}

		if (!(o instanceof DepartamentoEnhanced)) {
			return false;
		}

		final DepartamentoEnhanced id = (DepartamentoEnhanced) o;

		if ((this.idDepartamento != null)
				? (!idDepartamento.equals(id.idDepartamento))
					: (id.idDepartamento != null)) {
			return false;
		}

		return true;
	}



}
