package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.Direccion;


/*
 * Generated by JDO Genie (version:3.2.0beta7 (20 Sep 2004))
 */
public class DireccionTMP {
    private String idDireccionTmp; // pk 
    private String idMatricula; // pk 
    private String especificacion;
    private String valorEje;
    private String valorEje1;
    private EjeEnhanced eje;
    private EjeEnhanced eje1;
    private FolioEnhanced folio;
    private UsuarioEnhanced usuario;
    private Integer orden;
    private boolean toDelete;

    public DireccionTMP(DireccionEnhanced auxDir) {
        idDireccionTmp = auxDir.getIdDireccion();
        idMatricula = auxDir.getIdMatricula();
        especificacion = auxDir.getEspecificacion();
        valorEje = auxDir.getValorEje();
        valorEje1 = auxDir.getValorEje1();
        eje = auxDir.getEje();
        eje1 = auxDir.getEje1();
        folio = auxDir.getFolio();
        toDelete = auxDir.isToDelete();
        //orden = auxDir.getOrden();
    }

    public DireccionTMP() {
    }

    public DireccionTMP(Direccion dir) {
        DireccionEnhanced auxDir = DireccionEnhanced.enhance(dir);
        idDireccionTmp = auxDir.getIdDireccion();
        idMatricula = auxDir.getIdMatricula();
        especificacion = auxDir.getEspecificacion();
        valorEje = auxDir.getValorEje();
        valorEje1 = auxDir.getValorEje1();
        eje = auxDir.getEje();
        eje1 = auxDir.getEje1();
        folio = auxDir.getFolio();
        toDelete = auxDir.isToDelete();
        //orden = auxDir.getOrden(); 
    }

    public String getIdDireccionTmp() {
        return idDireccionTmp;
    }

    public void setIdDireccionTmp(String idDireccionTmp) {
        this.idDireccionTmp = idDireccionTmp;
    }

    public String getIdMatricula() {
        return idMatricula;
    }

    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }

    public String getEspecificacion() {
        return especificacion;
    }

    public void setEspecificacion(String especificacion) {
        this.especificacion = especificacion;
    }

    public String getValorEje() {
        return valorEje;
    }

    public void setValorEje(String valorEje) {
        this.valorEje = valorEje;
    }

    public String getValorEje1() {
        return valorEje1;
    }

    public void setValorEje1(String valorEje1) {
        this.valorEje1 = valorEje1;
    }

    public EjeEnhanced getEje() {
        return eje;
    }

    public void setEje(EjeEnhanced eje) {
        this.eje = eje;
    }

    public EjeEnhanced getEje1() {
        return eje1;
    }

    public void setEje1(EjeEnhanced eje1) {
        this.eje1 = eje1;
    }

    public FolioEnhanced getFolio() {
        return folio;
    }

    public void setFolio(FolioEnhanced folio) {
        this.folio = folio;
        setIdMatricula(folio.getIdMatricula());
    }

    public DireccionEnhanced getDefinitivo() {
        DireccionEnhanced dir = new DireccionEnhanced();
        dir.setEje(this.getEje());
        dir.setEje1(this.getEje1());
        dir.setEspecificacion(this.getEspecificacion());
        dir.setIdDireccion(this.getIdDireccionTmp());
        dir.setIdMatricula(this.getIdMatricula());
        dir.setValorEje(this.getValorEje());
        dir.setValorEje1(this.getValorEje1());
		dir.setUsuarioCreacionTMP(this.getUsuario());
		dir.setToDelete(this.isToDelete());
		//dir.setOrden(this.getOrden());
        return dir;
    }

    /**
	 * @return
	 */
	public UsuarioEnhanced getUsuario() {
		return usuario;
	}

	/**
	 * @param enhanced
	 */
	public void setUsuario(UsuarioEnhanced enhanced) {
		usuario = enhanced;
	}

	/**
	 * @return
	 */
	public boolean isToDelete() {
		return toDelete;
	}

	/**
	 * @param b
	 */
	public void setToDelete(boolean b) {
		toDelete = b;
	}

	public Integer getOrden() {
		return orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

}