package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.Direccion;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class DireccionEnhanced extends Enhanced{
    private String idDireccion; // pk 
    private String idMatricula; // pk 
    private String especificacion;
    private EjeEnhanced eje;
    private String valorEje;
    private EjeEnhanced eje1;
    private String valorEje1;
    private FolioEnhanced folio; // inverse Folio.direcciones
    private UsuarioEnhanced usuarioCreacion;
	private UsuarioEnhanced usuarioCreacionTMP;
	private boolean toDelete;
	private String circulo;
//	private Integer orden;

    public DireccionEnhanced() {
    }

    public String getIdDireccion() {
        return idDireccion;
    }

    public void setIdDireccion(String idDireccion) {
        this.idDireccion = idDireccion;
    }

    public String getIdMatricula() {
        return idMatricula;
    }

    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }

    public String getEspecificacion() {
        return especificacion;
    }

    public void setEspecificacion(String especificacion) {
        this.especificacion = especificacion;
    }

    public EjeEnhanced getEje() {
        return eje;
    }

    public void setEje(EjeEnhanced eje) {
        this.eje = eje;
    }

    public EjeEnhanced getEje1() {
        return eje1;
    }

    public void setEje1(EjeEnhanced eje1) {
        this.eje1 = eje1;
    }

    public FolioEnhanced getFolio() {
        return folio;
    }

    public void setFolio(FolioEnhanced folio) {
        this.folio = folio;
        setIdMatricula(folio.getIdMatricula());
    }
    
	public static DireccionEnhanced enhance(Direccion direccion){
	   return (DireccionEnhanced)Enhanced.enhance(direccion);
	}


    /**
	 * @return
	 */
	public String getValorEje() {
		return valorEje;
	}

	/**
	 * @return
	 */
	public String getValorEje1() {
		return valorEje1;
	}

	/**
	 * @param string
	 */
	public void setValorEje(String string) {
		valorEje = string;
	}

	/**
	 * @param string
	 */
	public void setValorEje1(String string) {
		valorEje1 = string;
	}
	
	public String toString(){
		String string = new String();
		if(eje != null){
			string += eje.getNombre(); 
		}
		if(valorEje != null){
			string += " " + valorEje; 
		}
		if(eje1 != null){
			string += " " + eje1.getNombre();
		}
		if(valorEje1 != null){
			string += " " + valorEje1; 
		}
		if(especificacion != null){
			string += " - " + especificacion; 		
		}
		
		return string; 
	}

	/**
	 * @return
	 */
	public UsuarioEnhanced getUsuarioCreacion() {
		return usuarioCreacion;
	}

	/**
	 * @param enhanced
	 */
	public void setUsuarioCreacion(UsuarioEnhanced enhanced) {
		usuarioCreacion = enhanced;
	}

	/**
	 * @return
	 */
	public UsuarioEnhanced getUsuarioCreacionTMP() {
		return usuarioCreacionTMP;
	}

	/**
	 * @param enhanced
	 */
	public void setUsuarioCreacionTMP(UsuarioEnhanced enhanced) {
		usuarioCreacionTMP = enhanced;
	}

	/**
	 * @return
	 */
	public boolean isToDelete() {
		return toDelete;
	}

	/**
	 * @param b
	 */
	public void setToDelete(boolean b) {
		toDelete = b;
	}

	public String getCirculo() {
		return circulo;
	}

	public void setCirculo(String circulo) {
		this.circulo = circulo;
	}

	/*public Integer getOrden() {
		return orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}*/

}
