package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.DocumentoFotocopia;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class DocumentoFotocopiaEnhanced extends Enhanced {

    private String idDocFotocopia; // pk 
    private String idSolicitud; // pk 
    private String descripcion;
    private Date fechaCreacion;
    private long numCopias;
    private long numHojas;
    private SolicitudFotocopiaEnhanced solicitud; // inverse SolicitudFotocopiaEnhanced.documentoFotocopiaEnhanced
    private TipoDocumentoEnhanced tipoDocumento;
    private TipoFotocopiaEnhanced tipoFotocopia;

    public DocumentoFotocopiaEnhanced() {
    }

    public String getIdDocFotocopia() {
        return idDocFotocopia;
    }

    public void setIdDocFotocopia(String idDocFotocopia) {
        this.idDocFotocopia = idDocFotocopia;
    }

    public String getIdSolicitud() {
        return idSolicitud;
    }

    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public long getNumCopias() {
        return numCopias;
    }

    public void setNumCopias(long numCopias) {
        this.numCopias = numCopias;
    }

    public long getNumHojas() {
        return numHojas;
    }

    public void setNumHojas(long numHojas) {
        this.numHojas = numHojas;
    }

    public SolicitudFotocopiaEnhanced getSolicitud() {
        return solicitud;
    }

    public void setSolicitud(SolicitudFotocopiaEnhanced solicitud) {
        this.solicitud = solicitud;
        setIdSolicitud(solicitud.getIdSolicitud());
    }

    public TipoDocumentoEnhanced getTipoDocumento() {
        return tipoDocumento;
    }

    public void setTipoDocumento(TipoDocumentoEnhanced tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    public TipoFotocopiaEnhanced getTipoFotocopia() {
        return tipoFotocopia;
    }

    public void setTipoFotocopia(TipoFotocopiaEnhanced tipoFotocopia) {
        this.tipoFotocopia = tipoFotocopia;
    }
    
  
	public static DocumentoFotocopiaEnhanced enhance(DocumentoFotocopia documento){
	   return (DocumentoFotocopiaEnhanced)Enhanced.enhance(documento);
	}
}
