package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.DominioNaturalezaJuridica;


/*
 * Generated by JDO Genie (version:3.2.0beta7 (20 Sep 2004))
 */
public class DominioNaturalezaJuridicaEnhanced extends Enhanced {

    private String idDominioNatJur; // pk 
    private String nombre;

    public DominioNaturalezaJuridicaEnhanced() {
    }

    public String getIdDominioNatJur() {
        return idDominioNatJur;
    }

    public void setIdDominioNatJur(String idDominioNatJur) {
        this.idDominioNatJur = idDominioNatJur;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
   
	public static DominioNaturalezaJuridicaEnhanced enhance(DominioNaturalezaJuridica documento){
		return (DominioNaturalezaJuridicaEnhanced) Enhanced.enhance(documento);
	}
}