package gov.sir.core.negocio.modelo.jdogenie;

import java.util.Date;

import gov.sir.core.negocio.modelo.Folio;



/*
 * Generated by JDO Genie (version:3.2.0beta7 (20 Sep 2004))
 */
public class FolioDatosTMP {
    private String idMatricula; // pk
    private String codCatastral;
    private String codCatastralAnterior;
    private String lindero;
    private String nupre;
    private String hectareas;
    private String metros;
    private String centimetros;
    private String determinaInm;
    private String privMetros;
    private String privCentimetros;
    private String consMetros;
    private String consCentimetros;
    private String coeficiente;
    private String linderosDef;
    private double avaluo;
    private Date fechaAvaluo;
    private String destEconomica;
    private TipoPredioEnhanced tipoPredio;
    private EstadoFolioEnhanced estado;
    private FolioEnhanced folio;
    private String comentarioCambioEstado;
    private String radicacion;
    
    private Date fechaApertura;
    private ZonaRegistralEnhanced zonaRegistral;
    
    /** ID de radicación con el cual se editó 
     * por última vez cada dato temporal del folio */
    private String numRadicaLindero;    
    private String numRadicaNupre;
    private String numRadicaHectareas;
    private String numRadicaMetros;
    private String numRadicaCentimetros;
    private String numRadicaDeterminaInm;
    private String numRadicaPrivMetros;
    private String numRadicaPrivCentimetros;
    private String numRadicaConsMetros;
    private String numRadicaConsCentimetros;
    private String numRadicaCoeficiente;
    private String numRadicaLinderosDef;
    private String numRadicaCodCatastral;
    private String numRadicaCodCatastralAnterior;
    private String numRadicaTipoPredio;
    private String numRadicaRadicacion;
    private String numRadicaFechaApertura;
    private String numRadicaZonaRegistral;
    private String numRadicaEstado;
    private String numRadicaAvaluo;
    private String numRadicaFechaAvaluo;
    private String numRadicaDestEconomica;
    
    public FolioDatosTMP() {
    } 

    public FolioDatosTMP(Folio folio) {
        FolioEnhanced auxFolio = FolioEnhanced.enhance(folio);
        idMatricula = auxFolio.getIdMatricula();
        codCatastral = auxFolio.getCodCatastral();
        codCatastralAnterior = auxFolio.getCodCatastralAnterior();
        lindero = auxFolio.getLindero();
        nupre = auxFolio.getNupre();
        hectareas = auxFolio.getHectareas();
        metros = auxFolio.getMetros();
        centimetros = auxFolio.getCentimetros();
        determinaInm = auxFolio.getDeterminaInm();
        privMetros = auxFolio.getPrivMetros();
        privCentimetros = auxFolio.getPrivCentimetros();
        consMetros = auxFolio.getConsMetros();
        consCentimetros = auxFolio.getConsCentimetros();
        coeficiente = auxFolio.getCoeficiente();
        linderosDef = auxFolio.getLinderosDef();
        avaluo = auxFolio.getAvaluo();
        fechaAvaluo = auxFolio.getFechaAvaluo();
        destEconomica = auxFolio.getDestEconomica();
        tipoPredio = auxFolio.getTipoPredio();
        estado = auxFolio.getEstado();
        radicacion = auxFolio.getRadicacion();
        fechaApertura = auxFolio.getFechaApertura();
        zonaRegistral = auxFolio.getZonaRegistral();
    }

    public String getIdMatricula() {
        return idMatricula;
    }

    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }

    public String getCodCatastral() {
        return codCatastral;
    }

    public void setCodCatastral(String codCatastral) {
        this.codCatastral = codCatastral;
    }

    public String getCodCatastralAnterior() {
        return codCatastralAnterior;
    }

    public void setCodCatastralAnterior(String codCatastralAnterior) {
        this.codCatastralAnterior = codCatastralAnterior;
    }

    public String getLindero() {
        return lindero;
    }

    public void setLindero(String lindero) {
        this.lindero = lindero;
    }

    public String getNupre() {
        return nupre;
    }

    public void setNupre(String nupre) {
        this.nupre = nupre;
    }

    public String getHectareas() {
        return hectareas;
    }

    public void setHectareas(String hectareas) {
        this.hectareas = hectareas;
    }

    public String getMetros() {
        return metros;
    }

    public void setMetros(String metros) {
        this.metros = metros;
    }

    public String getCentimetros() {
        return centimetros;
    }

    public void setCentimetros(String centimetros) {
        this.centimetros = centimetros;
    }

    public String getDeterminaInm() {
        return determinaInm;
    }

    public void setDeterminaInm(String determinaInm) {
        this.determinaInm = determinaInm;
    }

    public String getPrivMetros() {
        return privMetros;
    }

    public void setPrivMetros(String privMetros) {
        this.privMetros = privMetros;
    }

    public String getPrivCentimetros() {
        return privCentimetros;
    }

    public void setPrivCentimetros(String privCentimetros) {
        this.privCentimetros = privCentimetros;
    }

    public String getConsMetros() {
        return consMetros;
    }

    public void setConsMetros(String consMetros) {
        this.consMetros = consMetros;
    }

    public String getConsCentimetros() {
        return consCentimetros;
    }

    public void setConsCentimetros(String consCentimetros) {
        this.consCentimetros = consCentimetros;
    }

    public String getCoeficiente() {
        return coeficiente;
    }

    public void setCoeficiente(String coeficiente) {
        this.coeficiente = coeficiente;
    }

    public String getLinderosDef() {
        return linderosDef;
    }

    public void setLinderosDef(String linderosDef) {
        this.linderosDef = linderosDef;
    }

    public double getAvaluo() {
        return avaluo;
    }

    public void setAvaluo(double avaluo) {
        this.avaluo = avaluo;
    }

    public Date getFechaAvaluo() {
        return fechaAvaluo;
    }

    public void setFechaAvaluo(Date fechaAvaluo) {
        this.fechaAvaluo = fechaAvaluo;
    }

    public String getDestEconomica() {
        return destEconomica;
    }

    public void setDestEconomica(String destEconomica) {
        this.destEconomica = destEconomica;
    }
      
    public FolioEnhanced getFolio() {
        return folio;
    }

    public void setFolio(FolioEnhanced folio) {
        this.folio = folio;
        setIdMatricula(folio.getIdMatricula());
    }

    /**
     * @return
     */
    public EstadoFolioEnhanced getEstado() {
        return estado;
    }

    /**
     * @return
     */
    public TipoPredioEnhanced getTipoPredio() {
        return tipoPredio;
    }

    /**
     * @param enhanced
     */
    public void setEstado(EstadoFolioEnhanced enhanced) {
        estado = enhanced;
    }

    /**
     * @param enhanced
     */
    public void setTipoPredio(TipoPredioEnhanced enhanced) {
        tipoPredio = enhanced;
    }

    /**
	 * @return
	 */
	public String getComentarioCambioEstado() {
		return comentarioCambioEstado;
	}

	/**
	 * @param string
	 */
	public void setComentarioCambioEstado(String string) {
		comentarioCambioEstado = string;
	}

	public String getRadicacion() {
		return radicacion;
	}

	public void setRadicacion(String radicacion) {
		this.radicacion = radicacion;
	}

	public ZonaRegistralEnhanced getZonaRegistral() {
		return zonaRegistral;
	}

	public void setZonaRegistral(ZonaRegistralEnhanced zonaRegistral) {
		this.zonaRegistral = zonaRegistral;
	}

	/**
	 * @return
	 */
	public Date getFechaApertura() {
		return fechaApertura;
	}

	/**
	 * @param date
	 */
	public void setFechaApertura(Date date) {
		fechaApertura = date;
	}

	public String getNumRadicaCodCatastral() {
		return numRadicaCodCatastral;
	}

	public void setNumRadicaCodCatastral(String numRadicaCodCatastral) {
		this.numRadicaCodCatastral = numRadicaCodCatastral;
	}

	public String getNumRadicaCodCatastralAnterior() {
		return numRadicaCodCatastralAnterior;
	}

	public void setNumRadicaCodCatastralAnterior(
			String numRadicaCodCatastralAnterior) {
		this.numRadicaCodCatastralAnterior = numRadicaCodCatastralAnterior;
	}

	public String getNumRadicaLindero() {
		return numRadicaLindero;
	}

    public String getNumRadicaNupre() {
        return numRadicaNupre;
    }

    public void setNumRadicaNupre(String numRadicaNupre) {
        this.numRadicaNupre = numRadicaNupre;
    }

    public String getNumRadicaHectareas() {
        return numRadicaHectareas;
    }

    public void setNumRadicaHectareas(String numRadicaHectareas) {
        this.numRadicaHectareas = numRadicaHectareas;
    }

    public String getNumRadicaMetros() {
        return numRadicaMetros;
    }

    public void setNumRadicaMetros(String numRadicaMetros) {
        this.numRadicaMetros = numRadicaMetros;
    }

    public String getNumRadicaCentimetros() {
        return numRadicaCentimetros;
    }

    public void setNumRadicaCentimetros(String numRadicaCentimetros) {
        this.numRadicaCentimetros = numRadicaCentimetros;
    }

    public String getNumRadicaDeterminaInm() {
        return numRadicaDeterminaInm;
    }

    public void setNumRadicaDeterminaInm(String numRadicaDeterminaInm) {
        this.numRadicaDeterminaInm = numRadicaDeterminaInm;
    }

    public String getNumRadicaPrivMetros() {
        return numRadicaPrivMetros;
    }

    public void setNumRadicaPrivMetros(String numRadicaPrivMetros) {
        this.numRadicaPrivMetros = numRadicaPrivMetros;
    }

    public String getNumRadicaPrivCentimetros() {
        return numRadicaPrivCentimetros;
    }

    public void setNumRadicaPrivCentimetros(String numRadicaPrivCentimetros) {
        this.numRadicaPrivCentimetros = numRadicaPrivCentimetros;
    }

    public String getNumRadicaConsMetros() {
        return numRadicaConsMetros;
    }

    public void setNumRadicaConsMetros(String numRadicaConsMetros) {
        this.numRadicaConsMetros = numRadicaConsMetros;
    }

    public String getNumRadicaConsCentimetros() {
        return numRadicaConsCentimetros;
    }

    public void setNumRadicaConsCentimetros(String numRadicaConsCentimetros) {
        this.numRadicaConsCentimetros = numRadicaConsCentimetros;
    }

    public String getNumRadicaCoeficiente() {
        return numRadicaCoeficiente;
    }

    public void setNumRadicaCoeficiente(String numRadicaCoeficiente) {
        this.numRadicaCoeficiente = numRadicaCoeficiente;
    }

    public String getNumRadicaLinderosDef() {
        return numRadicaLinderosDef;
    }

    public void setNumRadicaLinderosDef(String numRadicaLinderosDef) {
        this.numRadicaLinderosDef = numRadicaLinderosDef;
    }

    public String getNumRadicaAvaluo() {
        return numRadicaAvaluo;
    }

    public void setNumRadicaAvaluo(String numRadicaAvaluo) {
        this.numRadicaAvaluo = numRadicaAvaluo;
    }

    public String getNumRadicaFechaAvaluo() {
        return numRadicaFechaAvaluo;
    }

    public void setNumRadicaFechaAvaluo(String numRadicaFechaAvaluo) {
        this.numRadicaFechaAvaluo = numRadicaFechaAvaluo;
    }

    public String getNumRadicaDestEconomica() {
        return numRadicaDestEconomica;
    }

    public void setNumRadicaDestEconomica(String numRadicaDestEconomica) {
        this.numRadicaDestEconomica = numRadicaDestEconomica;
    }
      
	public void setNumRadicaLindero(String numRadicaLindero) {
		this.numRadicaLindero = numRadicaLindero;
	}

	public String getNumRadicaTipoPredio() {
		return numRadicaTipoPredio;
	}

	public void setNumRadicaTipoPredio(String numRadicaTipoPredio) {
		this.numRadicaTipoPredio = numRadicaTipoPredio;
	}

	public String getNumRadicaEstado() {
		return numRadicaEstado;
	}

	public void setNumRadicaEstado(String numRadicaEstado) {
		this.numRadicaEstado = numRadicaEstado;
	}

	public String getNumRadicaFechaApertura() {
		return numRadicaFechaApertura;
	}

	public void setNumRadicaFechaApertura(String numRadicaFechaApertura) {
		this.numRadicaFechaApertura = numRadicaFechaApertura;
	}

	public String getNumRadicaRadicacion() {
		return numRadicaRadicacion;
	}

	public void setNumRadicaRadicacion(String numRadicaRadicacion) {
		this.numRadicaRadicacion = numRadicaRadicacion;
	}

	public String getNumRadicaZonaRegistral() {
		return numRadicaZonaRegistral;
	}

	public void setNumRadicaZonaRegistral(String numRadicaZonaRegistral) {
		this.numRadicaZonaRegistral = numRadicaZonaRegistral;
	}

}