package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.Folio;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class FolioEnhanced extends Enhanced {
    private String idMatricula; // pk 
    private String codCatastral;
    private EstadoFolioEnhanced estado;
    private ComplementacionEnhanced complementacion;
    private String lindero;
    private String nupre;
    private String hectareas;
    private String metros;
    private String centimetros;
    private String determinaInm;
    private String privMetros;
    private String privCentimetros;
    private String consMetros;
    private String consCentimetros;
    private String coeficiente;
    private String linderosDef;
    private double avaluo;
    private Date fechaAvaluo;
    private String destEconomica;
    private TipoPredioEnhanced tipoPredio;
    private ZonaRegistralEnhanced zonaRegistral;
    private List anotaciones = new ArrayList(); // contains Anotacion  inverse Anotacion.folio
    private Date fechaApertura;
    private boolean definitivo;
    private int directo;
    private long lastIdDireccion;
    private long lastIdAnotacion;
    private long lastIdSalvedad;
    private DocumentoEnhanced documento;
    private String radicacion;
    private String usuarioGrabacion;
    private String codCatastralAnterior;
	private boolean inconsistente;

    //Atributos de modelo temporal:
    private long lastIdDireccionTMP;
    private long lastIdAnotacionTMP;
    private long lastIdSalvedadTMP;
    private List salvedadesTMP = new ArrayList(); // contains SalvedadFolioTMP  inverse SalvedadFolioTMP.folio
    private List anotacionesTMP = new ArrayList(); // contains AnotacionTMP  inverse AnotacionTMP.folio
    private List direccionesTMP = new ArrayList(); // contains DireccionTMP  inverse DireccionTMP.folio
	private ComplementacionTMP complementacionTMP;
	private FolioDatosTMP datosTMP;
    
    /**
     * Contiene una lista de 0 o 1 elemento con el Turno que crea al folio
     */
    private List turnosFolio = new ArrayList(); // contains TurnoFolio  inverse TurnoFolio.folio

    /*
    * De este arreglo sólo se usa el primer elemento con el fin de saber si el folio se encuentra o no bloqueado
    */
    private List bloqueoFolio = new ArrayList(); // contains BloqueoFolio  inverse BloqueoFolio.folio
    private List direcciones = new ArrayList(); // contains Direccion  inverse Direccion.folio
    private List salvedades = new ArrayList(); // contains SalvedadFolio  inverse SalvedadFolio.folio

	private UsuarioEnhanced usuarioCreacion;
	
	private String ordenLPAD;
	
	private List historialEstados = new ArrayList(); // contains EstadoHistoriaEnhanced  inverse EstadoHistoriaEnhanced.folio
	private long lastIdHistorialEstados;
	private String comentario;
	private DocumentoTMP documentoTMP;
	private String nombreLote;
	private String circulo;
	
    public FolioEnhanced() {
    }

    public String getIdMatricula() {
        return idMatricula;
    }

    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }

    public String getCodCatastral() {
        return codCatastral;
    }

    public void setCodCatastral(String codCatastral) {
        this.codCatastral = codCatastral;
    }

    public EstadoFolioEnhanced getEstado() {
        return estado;
    }

    public void setEstado(EstadoFolioEnhanced estado) {
        this.estado = estado;
    }

    public ComplementacionEnhanced getComplementacion() {
        return complementacion;
    }

    public void setComplementacion(ComplementacionEnhanced complementacion) {
        this.complementacion = complementacion;
    }

    public TipoPredioEnhanced getTipoPredio() {
        return tipoPredio;
    }

    public void setTipoPredio(TipoPredioEnhanced tipoPredio) {
        this.tipoPredio = tipoPredio;
    }

    public ZonaRegistralEnhanced getZonaRegistral() {
        return zonaRegistral;
    }

    public void setZonaRegistral(ZonaRegistralEnhanced ZonaRegistral) {
        this.zonaRegistral = ZonaRegistral;
    }

    public List getAnotaciones() {
        return Collections.unmodifiableList(anotaciones);
    }

    public boolean addAnotacione(AnotacionEnhanced newAnotacione) {
        return anotaciones.add(newAnotacione);
    }

    public boolean removeAnotacione(AnotacionEnhanced oldAnotacione) {
        return anotaciones.remove(oldAnotacione);
    }
    
    public boolean removeAllAnotaciones(){
    	return anotaciones.removeAll(anotaciones);
    }

    public List getBloqueoFolios() {
        return Collections.unmodifiableList(bloqueoFolio);
    }

    public boolean addBloqueoFolio(BloqueoFolioEnhanced newBloqueoFolio) {
        return bloqueoFolio.add(newBloqueoFolio);
    }

    public boolean removeBloqueoFolio(BloqueoFolioEnhanced oldBloqueoFolio) {
        return bloqueoFolio.remove(oldBloqueoFolio);
    }

    public List getDirecciones() {
        return Collections.unmodifiableList(direcciones);
    }

    public boolean addDireccione(DireccionEnhanced newDireccione) {
        return direcciones.add(newDireccione);
    }

    public boolean removeDireccione(DireccionEnhanced oldDireccione) {
        return direcciones.remove(oldDireccione);
    }
    
    public boolean removeAllDirecciones(){
    	return direcciones.removeAll(direcciones);
    }
    

    public List getSalvedades() {
        return Collections.unmodifiableList(salvedades);
    }

    public boolean addSalvedade(SalvedadFolioEnhanced newSalvedade) {
        return salvedades.add(newSalvedade);
    }

    public boolean removeSalvedade(SalvedadFolioEnhanced oldSalvedade) {
        return salvedades.remove(oldSalvedade);
    }
    
    public boolean removeAllSalvedades(){
    	return salvedades.removeAll(salvedades);
    }

    /**
     * @return
     */
    public String getLindero() {
        return lindero;
    }

    /**
     * @param string
     */
    public void setLindero(String string) {
        lindero = string;
    }
    
    /**
     * @return
     */
    public String getNupre() {
        return nupre;
    }

    /**
     * @param nupre
     */
    public void setNupre(String nupre) {
        this.nupre = nupre;
    }
    
    /**
     * @return
     */
    public String getHectareas() {
        return hectareas;
    }

    /**
     * @param hectareas
     */
    public void setHectareas(String hectareas) {
        this.hectareas = hectareas;
    }
    
    /**
     * @return
     */
    public String getMetros() {
        return metros;
    }

    /**
     * @param metros
     */
    public void setMetros(String metros) {
        this.metros = metros;
    }

    /**
     * @return
     */
    public String getCentimetros() {
        return centimetros;
    }

    /**
     * @param centimetros
     */
    public void setCentimetros(String centimetros) {
        this.centimetros = centimetros;
    }

    /**
     * @return
     */
    public String getDeterminaInm() {
        return determinaInm;
    }

    /**
     * @param determinaInm
     */
    public void setDeterminaInm(String determinaInm) {
        this.determinaInm = determinaInm;
    }

    
    /**
     * @return
     */
    public String getPrivMetros() {
        return privMetros;
    }

    /**
     * @param privMetros
     */
    public void setPrivMetros(String privMetros) {
        this.privMetros = privMetros;
    }

    /**
     * @return
     */
    public String getPrivCentimetros() {
        return privCentimetros;
    }

    /**
     * @param privCentimetros
     */
    public void setPrivCentimetros(String privCentimetros) {
        this.privCentimetros = privCentimetros;
    }
    
    /**
     * @return
     */
    public String getConsMetros() {
        return consMetros;
    }

    /**
     * @param consMetros
     */
    public void setConsMetros(String consMetros) {
        this.consMetros = consMetros;
    }
    
    /**
     * @return
     */
    public String getConsCentimetros() {
        return consCentimetros;
    }

    /**
     * @param consCentimetros
     */
    public void setConsCentimetros(String consCentimetros) {
        this.consCentimetros = consCentimetros;
    }
    
    /**
     * @return
     */
    public String getCoeficiente() {
        return coeficiente;
    }

    /**
     * @param coeficiente
     */
    public void setCoeficiente(String coeficiente) {
        this.coeficiente = coeficiente;
    }
    
    /**
     * @return
     */
    public String getLinderosDef() {
        return linderosDef;
    }

    /**
     * @param linderosDef
     */
    public void setLinderosDef(String linderosDef) {
        this.linderosDef = linderosDef;
    }
    
    /**
     * @return
     */
    public double getAvaluo() {
        return avaluo;
    }
    
    /**
     * @param avaluo
     */
    public void setAvaluo(double avaluo) {
        this.avaluo = avaluo;
    }
    
    /**
     * @return
     */
    public Date getFechaAvaluo() {
        return fechaAvaluo;
    }
    
    /**
     * @param fechaAvaluo
     */
    public void setFechaAvaluo(Date fechaAvaluo) {
        this.fechaAvaluo = fechaAvaluo;
    }
    
    /**
     * @return
     */
    public String getDestEconomica() {
        return destEconomica;
    }
    
    /**
     * @param destEconomica
     */
    public void setDestEconomica(String destEconomica) {
        this.destEconomica = destEconomica;
    }
     
    /**
     * @return
     */
    public Date getFechaApertura() {
        return fechaApertura;
    }

    /**
     * @param date
     */
    public void setFechaApertura(Date date) {
        fechaApertura = date;
    }

    /**
     * @return
     */
    public boolean isDefinitivo() {
        return definitivo;
    }

    /**
     * @param b
     */
    public void setDefinitivo(boolean b) {
        definitivo = b;
    }

    /**
     * @return
     */
    public long getLastIdDireccion() {
        return lastIdDireccion;
    }

    /**
     * @param l
     */
    public void setLastIdDireccion(long l) {
        lastIdDireccion = l;
    }

    /**
     * @return
     */
    public long getLastIdAnotacion() {
        return lastIdAnotacion;
    }

    /**
     * @return
     */
    public long getLastIdSalvedad() {
        return lastIdSalvedad;
    }

    /**
     * @param l
     */
    public void setLastIdAnotacion(long l) {
        lastIdAnotacion = l;
    }

    /**
     * @param l
     */
    public void setLastIdSalvedad(long l) {
        lastIdSalvedad = l;
    }

    /**
     * @return
     */
    public DocumentoEnhanced getDocumento() {
        return documento;
    }

    /**
     * @param documento
     */
    public void setDocumento(DocumentoEnhanced documento) {
        this.documento = documento;
    }

    /**
     * @return
     */
    public String getRadicacion() {
        return radicacion;
    }

    /**
     * @return
     */
    public String getUsuarioGrabacion() {
        return usuarioGrabacion;
    }

    /**
     * @param string
     */
    public void setRadicacion(String string) {
        radicacion = string;
    }

    /**
     * @param string
     */
    public void setUsuarioGrabacion(String string) {
        usuarioGrabacion = string;
    }

    /**
     * @return
     */
    public String getCodCatastralAnterior() {
        return codCatastralAnterior;
    }

    /**
     * @param string
     */
    public void setCodCatastralAnterior(String string) {
        codCatastralAnterior = string;
    }

    public List getTurnosFolios() {
        return Collections.unmodifiableList(turnosFolio);
    }

    public boolean addTurnosFolio(TurnoFolioEnhanced newTurnosFolio) {
        return turnosFolio.add(newTurnosFolio);
    }

    public boolean removeTurnosFolio(TurnoFolioEnhanced oldTurnosFolio) {
        return turnosFolio.remove(oldTurnosFolio);
    }

    public static FolioEnhanced enhance(Folio folio) {
        return (FolioEnhanced) Enhanced.enhance(folio);
    }

    /**
     * @return
     */
    public long getLastIdAnotacionTMP() {
        return lastIdAnotacionTMP;
    }

    /**
     * @return
     */
    public long getLastIdDireccionTMP() {
        return lastIdDireccionTMP;
    }

    /**
     * @return
     */
    public long getLastIdSalvedadTMP() {
        return lastIdSalvedadTMP;
    }

    /**
     * @param l
     */
    public void setLastIdAnotacionTMP(long l) {
        lastIdAnotacionTMP = l;
    }

    /**
     * @param l
     */
    public void setLastIdDireccionTMP(long l) {
        lastIdDireccionTMP = l;
    }

    /**
     * @param l
     */
    public void setLastIdSalvedadTMP(long l) {
        lastIdSalvedadTMP = l;
    }

    public List getSalvedadesTMPs() {
        return Collections.unmodifiableList(salvedadesTMP);
    }

    public boolean addSalvedadesTMP(SalvedadFolioTMP newSalvedadesTMP) {
        return salvedadesTMP.add(newSalvedadesTMP);
    }

    public boolean removeSalvedadesTMP(SalvedadFolioTMP oldSalvedadesTMP) {
        return salvedadesTMP.remove(oldSalvedadesTMP);
    }

    public List getAnotacionesTMPs() {
        return Collections.unmodifiableList(anotacionesTMP);
    }

    public boolean addAnotacionesTMP(AnotacionTMP newAnotacionesTMP) {
        return anotacionesTMP.add(newAnotacionesTMP);
    }

    public boolean removeAnotacionesTMP(AnotacionTMP oldAnotacionesTMP) {
        return anotacionesTMP.remove(oldAnotacionesTMP);
    }

    public List getDireccionesTMPs() {
        return Collections.unmodifiableList(direccionesTMP);
    }

    public boolean addDireccionesTMP(DireccionTMP newDireccionesTMP) {
        return direccionesTMP.add(newDireccionesTMP);
    }

    public boolean removeDireccionesTMP(DireccionTMP oldDireccionesTMP) {
        return direccionesTMP.remove(oldDireccionesTMP);
    }

    /**
	 * @return
	 */
	public ComplementacionTMP getComplementacionTMP() {
		return complementacionTMP;
	}

	/**
	 * @param complementacionTMP
	 */
	public void setComplementacionTMP(ComplementacionTMP complementacionTMP) {
		this.complementacionTMP = complementacionTMP;
	}

	/**
	 * @return
	 */
	public FolioDatosTMP getDatosTMP() {
		return datosTMP;
	}

	/**
	 * @param datosTMP
	 */
	public void setDatosTMP(FolioDatosTMP datosTMP) {
		this.datosTMP = datosTMP;
		if(datosTMP!=null){
			if((datosTMP.getIdMatricula()==null)){
				datosTMP.setIdMatricula(this.idMatricula);
			}
		}
		
	}

	/**
	 * @return
	 */
	public boolean isInconsistente() {
		return inconsistente;
	}

	/**
	 * @param b
	 */
	public void setInconsistente(boolean b) {
		inconsistente = b;
	}

	/**
	 * @return
	 */
	public UsuarioEnhanced getUsuarioCreacion() {
		return usuarioCreacion;
	}

	/**
	 * @param enhanced
	 */
	public void setUsuarioCreacion(UsuarioEnhanced enhanced) {
		usuarioCreacion = enhanced;
	}

	/**
	 * @return
	 */
	public String getOrdenLPAD() {
		return ordenLPAD;
	}

	/**
	 * @param string
	 */
	public void setOrdenLPAD(String string) {
		ordenLPAD = string;
	}
	

	public List getHistorialEstados() {
		return Collections.unmodifiableList(historialEstados);
	}

	public boolean addHistorialEstado(EstadoHistoriaEnhanced newHistorialEstado) {
		return historialEstados.add(newHistorialEstado);
	}

	public boolean removeHistorialEstado(EstadoHistoriaEnhanced oldHistorialEstado) {
		return historialEstados.remove(oldHistorialEstado);
	}
	
	/**
	 * @return
	 */
	public long getLastIdHistorialEstados() {
		return lastIdHistorialEstados;
	}

	/**
	 * @param l
	 */
	public void setLastIdHistorialEstados(long l) {
		lastIdHistorialEstados = l;
	}

	/**
	 * @param list
	 */
	public void setAnotaciones(List list) {
		anotaciones = list;
	}

	/**
	 * @return
	 */
	public String getComentario() {
		return comentario;
	}

	/**
	 * @param string
	 */
	public void setComentario(String string) {
		comentario = string;
	}

	/**
	 * @return
	 */
	public DocumentoTMP getDocumentoTMP() {
		return documentoTMP;
	}

	/**
	 * @param documentoTMP
	 */
	public void setDocumentoTMP(DocumentoTMP documentoTMP) {
		this.documentoTMP = documentoTMP;
	}

	/**
	 * @return
	 */
	public String getNombreLote() {
		return nombreLote;
	}

	/**
	 * @param string
	 */
	public void setNombreLote(String string) {
		nombreLote = string;
	}

	public int getDirecto() {
		return directo;
	}

	public void setDirecto(int directo) {
		this.directo = directo;
	}

	public String getCirculo() {
		return circulo;
	}

	public void setCirculo(String circulo) {
		this.circulo = circulo;
	}



}
