package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.GrupoNaturalezaJuridica;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;

/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class GrupoNaturalezaJuridicaEnhanced extends Enhanced{

    private String idGrupoNatJuridica; // pk 
    private String nombre;
    private List naturalezaJuridicas = new ArrayList(); // contains NaturalezaJuridica  inverse NaturalezaJuridica.grupoNaturalezaJuridica

    public GrupoNaturalezaJuridicaEnhanced() {
    }

    public String getIdGrupoNatJuridica() {
        return idGrupoNatJuridica;
    }

    public void setIdGrupoNatJuridica(String idGrupoNatJuridica) {
        this.idGrupoNatJuridica = idGrupoNatJuridica;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public List getNaturalezaJuridicas() {
        return Collections.unmodifiableList(naturalezaJuridicas);
    }

    public boolean addNaturalezaJuridica(NaturalezaJuridicaEnhanced newNaturalezaJuridica) {
        return naturalezaJuridicas.add(newNaturalezaJuridica);
    }

    public boolean removeNaturalezaJuridica(NaturalezaJuridicaEnhanced oldNaturalezaJuridica) {
        return naturalezaJuridicas.remove(oldNaturalezaJuridica);
    }


	public static GrupoNaturalezaJuridicaEnhanced enhance(GrupoNaturalezaJuridica grupo){
		return (GrupoNaturalezaJuridicaEnhanced) Enhanced.enhance(grupo);
	}
}