package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.NaturalezaJuridicaEntidad;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.9 (17 Jan 2005))
 */
public class NaturalezaJuridicaEntidadEnhanced  extends Enhanced {

    private String idNatJuridicaEntidad; // pk 
    private boolean exento;
    private Date fechaCreacion;
    private String nombre;
    private boolean activo;

    public NaturalezaJuridicaEntidadEnhanced() {
    }

    public String getIdNatJuridicaEntidad() {
        return idNatJuridicaEntidad;
    }

    public void setIdNatJuridicaEntidad(String idNatJuridicaEntidad) {
        this.idNatJuridicaEntidad = idNatJuridicaEntidad;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
     
	public static NaturalezaJuridicaEntidadEnhanced enhance(NaturalezaJuridicaEntidad naturaleza){
		return (NaturalezaJuridicaEntidadEnhanced)Enhanced.enhance(naturaleza);
	}

    /**
	 * @return
	 */
	public boolean isExento() {
		return exento;
	}

	/**
	 * @param b
	 */
	public void setExento(boolean b) {
		exento = b;
	}

	/**
	 * @return
	 */
	public boolean isActivo() {
		return activo;
	}

	/**
	 * @param b
	 */
	public void setActivo(boolean b) {
		activo = b;
	}

}
