package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.NotaActuacion;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class NotaActuacionEnhanced  extends Enhanced{

    private String idNotaActuacion; // pk
    private String idSolicitud; // pk
    private String estado;
    private Date fechaCreacion;
    private String nota;
    private SolicitudEnhanced solicitud; // inverse SolicitudCorreccionEnhanced.notasActuaciones
    private UsuarioEnhanced usuario;

    public NotaActuacionEnhanced() {
    }

    public String getIdNotaActuacion() {
        return idNotaActuacion;
    }

    public void setIdNotaActuacion(String idNotaActuacion) {
        this.idNotaActuacion = idNotaActuacion;
    }

    public String getIdSolicitud() {
        return idSolicitud;
    }

    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getNota() {
        return nota;
    }

    public void setNota(String nota) {
        this.nota = nota;
    }

    public SolicitudEnhanced getSolicitud() {
        return solicitud;
    }

    public void setSolicitud(SolicitudEnhanced solicitud) {
        this.solicitud = solicitud;
        setIdSolicitud(solicitud.getIdSolicitud());
    }

    public UsuarioEnhanced getUsuario() {
        return usuario;
    }

    public void setUsuario(UsuarioEnhanced usuario) {
        this.usuario = usuario;
    }
    
	public static NotaActuacionEnhanced enhance(NotaActuacion x){
		return (NotaActuacionEnhanced)Enhanced.enhance(x);
	}
}
