package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.NumeroMatricula;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class NumeroMatriculaEnhanced extends Enhanced{
    private String idNumero; // pk 

    public NumeroMatriculaEnhanced() {
    }

    public String getIdNumero() {
        return idNumero;
    }

    public void setIdNumero(String idNumero) {
        this.idNumero = idNumero;
    }
    
    public static NumeroMatriculaEnhanced enhance(NumeroMatricula numeroMatricula){
        return (NumeroMatriculaEnhanced)Enhanced.enhance(numeroMatricula);
    }
}
