package gov.sir.core.negocio.modelo.jdogenie;

import java.util.Date;

import gov.sir.core.negocio.modelo.Oficio;


/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class OficioEnhanced  extends Enhanced{

    private String idOficio; // pk 
    private String textoOficio;
    private TurnoHistoriaEnhanced turnoHistoria;
	private boolean firmado;
	private String numero;
	private Date fechaFirma;
	private Date fechaCreacion;
	private TipoOficioEnhanced tipo;

    public OficioEnhanced() {
    }

    public String getIdOficio() {
        return idOficio;
    }

    public void setIdOficio(String idOficio) {
        this.idOficio = idOficio;
    }

    public String getTextoOficio() {
        return textoOficio;
    }

    public void setTextoOficio(String textoOficio) {
        this.textoOficio = textoOficio;
    }

    public TurnoHistoriaEnhanced getTurnoHistoria() {
        return turnoHistoria;
    }

    public void setTurnoHistoria(TurnoHistoriaEnhanced turnoHistoria) {
        this.turnoHistoria = turnoHistoria;
    }
    

	public static OficioEnhanced enhance(Oficio oo) {
		return (OficioEnhanced) Enhanced.enhance(oo);
	}

    /**
	 * @return
	 */
	public boolean isFirmado() {
		return firmado;
	}

	/**
	 * @param b
	 */
	public void setFirmado(boolean b) {
		firmado = b;
	}

	/**
	 * @return
	 */
	public String getNumero() {
		return numero;
	}

	/**
	 * @param string
	 */
	public void setNumero(String string) {
		numero = string;
	}

	/**
	 * @return
	 */
	public Date getFechaFirma() {
		return fechaFirma;
	}

	/**
	 * @param date
	 */
	public void setFechaFirma(Date date) {
		fechaFirma = date;
	}

	/**
	 * @return
	 */
	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	/**
	 * @param date
	 */
	public void setFechaCreacion(Date date) {
		fechaCreacion = date;
	}

	/**
	 * @return
	 */
	public TipoOficioEnhanced getTipo() {
		return tipo;
	}

	/**
	 * @param enhanced
	 */
	public void setTipo(TipoOficioEnhanced enhanced) {
		tipo = enhanced;
	}

}
