package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.OtorganteNatural;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.9 (17 Jan 2005))
 */
public class OtorganteNaturalEnhanced  extends Enhanced{

    private String idMinuta; // pk 
    private String idOtorgante; // pk 
    private Date fechaCreacion;
    private String nombre;
    private boolean exento;
    private MinutaEnhanced minuta; // inverse MinutaEnhanced.otorgantesNaturales

    public OtorganteNaturalEnhanced() {
    }

    public String getIdMinuta() {
        return idMinuta;
    }

    public void setIdMinuta(String idMinuta) {
        this.idMinuta = idMinuta;
    }

    public String getIdOtorgante() {
        return idOtorgante;
    }

    public void setIdOtorgante(String idOtorgante) {
        this.idOtorgante = idOtorgante;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public MinutaEnhanced getMinuta() {
        return minuta;
    }

    public void setMinuta(MinutaEnhanced minuta) {
        this.minuta = minuta;
        setIdMinuta(minuta.getIdMinuta());
    }

 
	public static OtorganteNaturalEnhanced enhance(OtorganteNatural x){
		return (OtorganteNaturalEnhanced)Enhanced.enhance(x);
	}
    public boolean isExento() {
		return exento;
	}

	public void setExento(boolean exento) {
		this.exento = exento;
	}
}
