package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.ProcesoReparto;

import java.util.Date;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;

/*
 * Generated by JDO Genie (version:3.2.0beta7 (20 Sep 2004))
 */
public class ProcesoRepartoEnhanced extends Enhanced {

    private String idProcesoReparto; // pk 
    private Date fechaCreacion;
    private Date fechaReparto;
    private CirculoEnhanced circulo;
    private List repartos = new ArrayList(); // contains RepartoEnhanced  inverse RepartoEnhanced.procesoReparto

    public ProcesoRepartoEnhanced() {
    }

    public String getIdProcesoReparto() {
        return idProcesoReparto;
    }

    public void setIdProcesoReparto(String idProcesoReparto) {
        this.idProcesoReparto = idProcesoReparto;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Date getFechaReparto() {
        return fechaReparto;
    }

    public void setFechaReparto(Date fechaReparto) {
        this.fechaReparto = fechaReparto;
    }

    public CirculoEnhanced getCirculo() {
        return circulo;
    }

    public void setCirculo(CirculoEnhanced circulo) {
        this.circulo = circulo;
    }

    public List getRepartos() {
        return Collections.unmodifiableList(repartos);
    }

    public boolean addReparto(RepartoEnhanced newReparto) {
        return repartos.add(newReparto);
    }

    public boolean removeReparto(RepartoEnhanced oldReparto) {
        return repartos.remove(oldReparto);
    }
    
	public static ProcesoRepartoEnhanced enhance(ProcesoReparto reparto){
		return (ProcesoRepartoEnhanced)Enhanced.enhance(reparto);
	}
}