package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.RangoFolio;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class RangoFolioEnhanced extends Enhanced {

    private String idRangoFolio; // pk 
    private String idSolicitud; // pk 
    private Date fechaCreacion;
    private String matriculaFinal;
    private String matriculaInicial;
    private SolicitudEnhanced solicitud; // inverse SolicitudEnhanced.rangosFolio

    public RangoFolioEnhanced() {
    }

    public String getIdRangoFolio() {
        return idRangoFolio;
    }

    public void setIdRangoFolio(String idRangoFolio) {
        this.idRangoFolio = idRangoFolio;
    }

    public String getIdSolicitud() {
        return idSolicitud;
    }

    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getMatriculaFinal() {
        return matriculaFinal;
    }

    public void setMatriculaFinal(String matriculaFinal) {
        this.matriculaFinal = matriculaFinal;
    }

    public String getMatriculaInicial() {
        return matriculaInicial;
    }

    public void setMatriculaInicial(String matriculaInicial) {
        this.matriculaInicial = matriculaInicial;
    }

    public SolicitudEnhanced getSolicitud() {
        return solicitud;
    }

    public void setSolicitud(SolicitudEnhanced solicitud) {
        this.solicitud = solicitud;
        setIdSolicitud(solicitud.getIdSolicitud());
    }
    
   
	public static RangoFolioEnhanced enhance(RangoFolio rangoFolio){
		return (RangoFolioEnhanced)Enhanced.enhance(rangoFolio);
	}
}