package gov.sir.core.negocio.modelo.jdogenie;

import java.util.Date;

import gov.sir.core.negocio.modelo.Recurso;


/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class RecursoEnhanced extends Enhanced {

    private String anio; // pk 
    private String idCirculo; // pk 
    private long idProceso; // pk 
    private String idRecurso; // pk 
    private String idTurno; // pk 
    private String idTurnoHistoria; // pk 
    private String respuestaRecurso;
    private String textoRecurso;
    private TipoRecursoEnhanced tipoRecurso;
    private TurnoHistoriaEnhanced turnoHistoria; // inverse TurnoHistoriaEnhanced.recursoEnhanced
    private OficioEnhanced oficioRespuesta;
    private UsuarioEnhanced usuario;
    private String titulo;
    private String textoUsuario;
    private Date fecha;    
    private Date fechaEjecutoria;

    public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
	
	public Date getFechaEjecutoria() {
        return fechaEjecutoria;
    }
    
    public void setFechaEjecutoria(Date fechaEjecutoria) {
        this.fechaEjecutoria = fechaEjecutoria;
    }

	public String getTextoUsuario() {
		return textoUsuario;
	}

	public void setTextoUsuario(String textoUsuario) {
		this.textoUsuario = textoUsuario;
	}

	public String getTitulo() {
		return titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public UsuarioEnhanced getUsuario() {
		return usuario;
	}

	public void setUsuario(UsuarioEnhanced usuario) {
		this.usuario = usuario;
	}

	public RecursoEnhanced() {
    }

    public String getAnio() {
        return anio;
    }

    public void setAnio(String anio) {
        this.anio = anio;
    }

    public String getIdCirculo() {
        return idCirculo;
    }

    public void setIdCirculo(String idCirculo) {
        this.idCirculo = idCirculo;
    }

    public long getIdProceso() {
        return idProceso;
    }

    public void setIdProceso(long idProceso) {
        this.idProceso = idProceso;
    }

    public String getIdRecurso() {
        return idRecurso;
    }

    public void setIdRecurso(String idRecurso) {
        this.idRecurso = idRecurso;
    }

    public String getIdTurno() {
        return idTurno;
    }

    public void setIdTurno(String idTurno) {
        this.idTurno = idTurno;
    }

    public String getIdTurnoHistoria() {
        return idTurnoHistoria;
    }

    public void setIdTurnoHistoria(String idTurnoHistoria) {
        this.idTurnoHistoria = idTurnoHistoria;
    }

    public String getRespuestaRecurso() {
        return respuestaRecurso;
    }

    public void setRespuestaRecurso(String respuestaRecurso) {
        this.respuestaRecurso = respuestaRecurso;
    }

    public String getTextoRecurso() {
        return textoRecurso;
    }

    public void setTextoRecurso(String textoRecurso) {
        this.textoRecurso = textoRecurso;
    }

    public TipoRecursoEnhanced getTipoRecurso() {
        return tipoRecurso;
    }

    public void setTipoRecurso(TipoRecursoEnhanced tipoRecurso) {
        this.tipoRecurso = tipoRecurso;
    }

    public TurnoHistoriaEnhanced getTurnoHistoria() {
        return turnoHistoria;
    }

    public void setTurnoHistoria(TurnoHistoriaEnhanced turnoHistoria) {
        this.turnoHistoria = turnoHistoria;
        setAnio(turnoHistoria.getAnio());
        setIdCirculo(turnoHistoria.getIdCirculo());
        setIdProceso(turnoHistoria.getIdProceso());
        setIdTurno(turnoHistoria.getIdTurno());
        setIdTurnoHistoria(turnoHistoria.getIdTurnoHistoria());
    }
    
 
	public static RecursoEnhanced enhance (Recurso tipoTarifa){
		return (RecursoEnhanced)Enhanced.enhance(tipoTarifa);
	}

    /**
	 * @return
	 */
	public OficioEnhanced getOficioRespuesta() {
		return oficioRespuesta;
	}

	/**
	 * @param enhanced
	 */
	public void setOficioRespuesta(OficioEnhanced enhanced) {
		oficioRespuesta = enhanced;
	}

}
