package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.Reparto;

import java.util.Date;

/*
 * Generated by JDO Genie (version:3.2.0beta7 (20 Sep 2004))
 */
public class RepartoEnhanced extends Enhanced{

    private String anio; // pk 
    private String idCirculo; // pk 
    private long idProceso; // pk 
    private String idProcesoReparto; // pk 
    private String idTurno; // pk 
    private long idUsuario; // pk 
    private Date fechaCreacion;
    private ProcesoRepartoEnhanced procesoReparto; // inverse ProcesoRepartoEnhanced.repartos
    private TurnoEnhanced turno;
    private UsuarioEnhanced usuario; // inverse UsuarioEnhanced.repartos

    public RepartoEnhanced() {
    }

    public String getAnio() {
        return anio;
    }

    public void setAnio(String anio) {
        this.anio = anio;
    }

    public String getIdCirculo() {
        return idCirculo;
    }

    public void setIdCirculo(String idCirculo) {
        this.idCirculo = idCirculo;
    }

    public long getIdProceso() {
        return idProceso;
    }

    public void setIdProceso(long idProceso) {
        this.idProceso = idProceso;
    }

    public String getIdProcesoReparto() {
        return idProcesoReparto;
    }

    public void setIdProcesoReparto(String idProcesoReparto) {
        this.idProcesoReparto = idProcesoReparto;
    }

    public String getIdTurno() {
        return idTurno;
    }

    public void setIdTurno(String idTurno) {
        this.idTurno = idTurno;
    }

    public long getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public ProcesoRepartoEnhanced getProcesoReparto() {
        return procesoReparto;
    }

    public void setProcesoReparto(ProcesoRepartoEnhanced procesoReparto) {
        this.procesoReparto = procesoReparto;
        setIdProcesoReparto(procesoReparto.getIdProcesoReparto());
    }

    public TurnoEnhanced getTurno() {
        return turno;
    }

    public void setTurno(TurnoEnhanced turno) {
        this.turno = turno;
        setAnio(turno.getAnio());
        setIdCirculo(turno.getIdCirculo());
        setIdProceso(turno.getIdProceso());
        setIdTurno(turno.getIdTurno());
    }

    public UsuarioEnhanced getUsuario() {
        return usuario;
    }

    public void setUsuario(UsuarioEnhanced usuario) {
        this.usuario = usuario;
        setIdUsuario(usuario.getIdUsuario());
    }

    
	public static RepartoEnhanced enhance(Reparto reparto){
		return (RepartoEnhanced)Enhanced.enhance(reparto);
	}
}