package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.RolPantalla;


/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class RolPantallaEnhanced  extends Enhanced
{

    private long idPantallaAdministrativa; // pk
    private String idRol; // pk
    private PantallaAdministrativaEnhanced pantalla; // inverse PantallaAdministrativaEnhanced.roles
    private RolSIREnhanced rol; // inverse RolEnhanced.pantallas

    public RolPantallaEnhanced() {
    }

    public long getIdPantallaAdministrativa() {
        return idPantallaAdministrativa;
    }

    public void setIdPantallaAdministrativa(long idPantallaAdministrativa) {
        this.idPantallaAdministrativa = idPantallaAdministrativa;
    }

    public String getIdRol() {
        return idRol;
    }

    public void setIdRol(String idRol) {
        this.idRol = idRol;
    }

    public PantallaAdministrativaEnhanced getPantalla() {
        return pantalla;
    }

    public void setPantalla(PantallaAdministrativaEnhanced pantalla) {
        this.pantalla = pantalla;
        setIdPantallaAdministrativa(pantalla.getIdPantallaAdministrativa());
    }

    public RolSIREnhanced getRol() {
        return rol;
    }

    public void setRol(RolSIREnhanced rol) {
        this.rol = rol;
        setIdRol(rol.getIdRol());
    }


	public static RolPantallaEnhanced enhance (
	RolPantalla rol)
	{
		return (RolPantallaEnhanced)Enhanced.enhance(rol);
	}
}
