package gov.sir.core.negocio.modelo.jdogenie;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import gov.sir.core.negocio.modelo.SalvedadFolio;

/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class SalvedadFolioEnhanced extends Enhanced {
	private String idMatricula; // pk 
	private String idSalvedad; // pk 
	private String descripcion;
	private FolioEnhanced folio; // inverse Folio.salvedades
	private UsuarioEnhanced usuarioCreacion;
	private List turnoSalvedadFolio = new ArrayList(); // contains TurnoSalvedadFolioEnhanced  inverse TurnoSalvedadFolioEnhanced.salvedad
	private Date fechaCreacion;
	private String numRadicacion;
	private UsuarioEnhanced usuarioCreacionTMP;

	public SalvedadFolioEnhanced() {
	}

	public String getIdMatricula() {
		return idMatricula;
	}

	public void setIdMatricula(String idMatricula) {
		this.idMatricula = idMatricula;
	}

	public String getIdSalvedad() {
		return idSalvedad;
	}

	public void setIdSalvedad(String idSalvedad) {
		this.idSalvedad = idSalvedad;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public FolioEnhanced getFolio() {
		return folio;
	}

	public void setFolio(FolioEnhanced folio) {
		this.folio = folio;
		setIdMatricula(folio.getIdMatricula());
	}

	public static SalvedadFolioEnhanced enhance(SalvedadFolio salvedad) {
		return (SalvedadFolioEnhanced) Enhanced.enhance(salvedad);
	}

	
	/**
	 * @return
	 */
	public UsuarioEnhanced getUsuarioCreacion() {
		return usuarioCreacion;
	}

	/**
	 * @param enhanced
	 */
	public void setUsuarioCreacion(UsuarioEnhanced enhanced) {
		usuarioCreacion = enhanced;
	}
	 
	 public List getTurnoSalvedadFolios() {
		 return Collections.unmodifiableList(turnoSalvedadFolio);
	 }

	 public boolean addTurnoSalvedadFolio(TurnoSalvedadFolioEnhanced newTurnoSalvedadFolioEnhanced) {
		 return turnoSalvedadFolio.add(newTurnoSalvedadFolioEnhanced);
	 }

	 public boolean removeTurnoSalvedadFolio(TurnoSalvedadFolioEnhanced oldTurnoSalvedadFolioEnhanced) {
		 return turnoSalvedadFolio.remove(oldTurnoSalvedadFolioEnhanced);
	 }


	/**
	 * @return
	 */
	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	/**
	 * @param date
	 */
	public void setFechaCreacion(Date date) {
		fechaCreacion = date;
	}

	/**
	 * @return
	 */
	public String getNumRadicacion() {
		return numRadicacion;
	}

	/**
	 * @param string
	 */
	public void setNumRadicacion(String string) {
		numRadicacion = string;
	}

	/**
	 * @return
	 */
	public UsuarioEnhanced getUsuarioCreacionTMP() {
		return usuarioCreacionTMP;
	}

	/**
	 * @param enhanced
	 */
	public void setUsuarioCreacionTMP(UsuarioEnhanced enhanced) {
		usuarioCreacionTMP = enhanced;
	}

}
