package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.Secuencias;

/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class SecuenciasEnhanced extends Enhanced {

	private String tableName; // pk 
	private long lastUsedId;

	public SecuenciasEnhanced() {
	}

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public long getLastUsedId() {
		return lastUsedId;
	}

	public void setLastUsedId(long lastUsedId) {
		this.lastUsedId = lastUsedId;
	}

	public static SecuenciasEnhanced enhance(Secuencias secuencias) {
		return (SecuenciasEnhanced) Enhanced.enhance(secuencias);
	}
}