package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.SolCheckedItemDev;

import java.util.Date;


/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class SolCheckedItemDevEnhanced extends Enhanced{

    private String idCheckItemDev; // pk
    private String idSolicitud; // pk
    private Date fechaCreacion;
    private CheckItemDevEnhanced checkItem;
    private SolicitudDevolucionEnhanced solicitud; // inverse SolicitudDevolucionEnhanced.checkedItems

    public SolCheckedItemDevEnhanced() {
    }

    public String getIdCheckItemDev() {
        return idCheckItemDev;
    }

    public void setIdCheckItemDev(String idCheckItemDev) {
        this.idCheckItemDev = idCheckItemDev;
    }

    public String getIdSolicitud() {
        return idSolicitud;
    }

    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public CheckItemDevEnhanced getCheckItem() {
        return checkItem;
    }

    public void setCheckItem(CheckItemDevEnhanced checkItem) {
        this.checkItem = checkItem;
        setIdCheckItemDev(checkItem.getIdCheckItemDev());
    }

    public SolicitudDevolucionEnhanced getSolicitud() {
        return solicitud;
    }

    public void setSolicitud(SolicitudDevolucionEnhanced solicitud) {
        this.solicitud = solicitud;
        setIdSolicitud(solicitud.getIdSolicitud());
    }
    
	public static SolCheckedItemDevEnhanced enhance(SolCheckedItemDev x) {
		return (SolCheckedItemDevEnhanced) Enhanced.enhance(x);
	}
}
