package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.Solicitud;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class SolicitudEnhanced extends Enhanced {
	private String idSolicitud; // pk
	private TurnoEnhanced turno;
	private TurnoEnhanced turnoAnterior;
	private CirculoEnhanced circulo;
	private UsuarioEnhanced usuario;
	private List solicitudFolios = new ArrayList();
	// contains SolicitudFolio  inverse SolicitudFolio.solicitud
	private List liquidaciones = new ArrayList(); // contains Liquidacion  inverse Liquidacion.solicitud
	private Date fecha;
	private long lastIdLiquidacion;
	private ProcesoEnhanced proceso;
	private String comentario;
	private List solicitudesPadre = new ArrayList(); // contains SolicitudAsociadaEnhanced  inverse SolicitudAsociadaEnhanced.solicitudHija
	private List solicitudesHijas = new ArrayList(); // contains SolicitudAsociadaEnhanced  inverse SolicitudAsociadaEnhanced.solicitudPadre
	private List solicitudesVinculadas = new ArrayList(); // contains SolicitudVinculadaEnhanced  inverse SolicitudVinculadaEnhanced.solicitudPadre
	private int numReimpresionesRecibo;
	private int lastIdWebSegEng;


	public int getLastIdWebSegEng() {
		return lastIdWebSegEng;
	}

	public void setLastIdWebSegEng(int lastIdWebSegEng) {
		this.lastIdWebSegEng = lastIdWebSegEng;
	}

	public SolicitudEnhanced() {
	}

	public String getIdSolicitud() {
		return idSolicitud;
	}

	public void setIdSolicitud(String idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

	public TurnoEnhanced getTurnoAnterior() {
		return turnoAnterior;
	}

	public void setTurnoAnterior(TurnoEnhanced turnoAnterior) {
		this.turnoAnterior = turnoAnterior;
	}

	public List getSolicitudFolios() {
		return Collections.unmodifiableList(solicitudFolios);
	}

	public boolean addSolicitudFolio(SolicitudFolioEnhanced newSolicitudFolio) {
		return solicitudFolios.add(newSolicitudFolio);
	}

	public boolean removeSolicitudFolio(SolicitudFolioEnhanced oldSolicitudFolio) {
		return solicitudFolios.remove(oldSolicitudFolio);
	}

	public List getLiquidaciones() {
		return Collections.unmodifiableList(liquidaciones);
	}

	public boolean addLiquidacion(LiquidacionEnhanced newLiquidacion) {
		return liquidaciones.add(newLiquidacion);
	}

	public boolean removeLiquidacion(LiquidacionEnhanced oldLiquidacion) {
		return liquidaciones.remove(oldLiquidacion);
	}

	public static SolicitudEnhanced enhance(Solicitud solicitud) {
		return (SolicitudEnhanced) Enhanced.enhance(solicitud);
	}


	public List getSolicitudesPadres() {
		return Collections.unmodifiableList(solicitudesPadre);
	}

	public boolean addSolicitudesPadre(SolicitudAsociadaEnhanced newSolicitudesPadre) {
		return solicitudesPadre.add(newSolicitudesPadre);
	}

	public boolean removeSolicitudesPadre(SolicitudAsociadaEnhanced oldSolicitudesPadre) {
		return solicitudesPadre.remove(oldSolicitudesPadre);
	}
	

	 public List getSolicitudesHijas() {
		 return Collections.unmodifiableList(solicitudesHijas);
	 }

	 public boolean addSolicitudesHija(SolicitudAsociadaEnhanced newSolicitudesHija) {
		 return solicitudesHijas.add(newSolicitudesHija);
	 }

	 public boolean removeSolicitudesHija(SolicitudAsociadaEnhanced oldSolicitudesHija) {
		 return solicitudesHijas.remove(oldSolicitudesHija);
	 }
	

	/**
	 * @return
	 */
	public TurnoEnhanced getTurno() {
		return turno;
	}

	/**
	 * @param turno
	 */
	public void setTurno(TurnoEnhanced turno) {
		this.turno = turno;
	}

	/**
	 * @return
	 */
	public CirculoEnhanced getCirculo() {
		return circulo;
	}

	/**
	 * @return
	 */
	public UsuarioEnhanced getUsuario() {
		return usuario;
	}

	/**
	 * @param circulo
	 */
	public void setCirculo(CirculoEnhanced circulo) {
		this.circulo = circulo;
	}

	/**
	 * @param usuario
	 */
	public void setUsuario(UsuarioEnhanced usuario) {
		this.usuario = usuario;
	}

	/**
	 * 
	 * @return
	 */
	public Date getFecha() {
		return fecha;
	}

	/**
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/**
	 * @return
	 */
	public long getLastIdLiquidacion() {
		return lastIdLiquidacion;
	}

	/**
	 * @param l
	 */
	public void setLastIdLiquidacion(long l) {
		lastIdLiquidacion = l;
	}

	/**
	 * @return
	 */
	public ProcesoEnhanced getProceso() {
		return proceso;
	}

	/**
	 * @param proceso
	 */
	public void setProceso(ProcesoEnhanced proceso) {
		this.proceso = proceso;
	}

	/**
	 * @return
	 */
	public String getComentario() {
		return comentario;
	}

	/**
	 * @param string
	 */
	public void setComentario(String string) {
		comentario = string;
	}
	
	/**
	 * @return
	 */
	public CiudadanoEnhanced getCiudadano() {
		return null;
	}

	/**
	 * @return
	 */
	public DatosAntiguoSistemaEnhanced getDatosAntiguoSistema() {
		return null;
	}
	
	/**
	 * @return
	 */
	public void setCiudadano(CiudadanoEnhanced ciudadanoEnhanced) {
	}

	/**
	 * @return
	 */
	public void setDatosAntiguoSistema(DatosAntiguoSistemaEnhanced datosAntiguoSistemaEnhanced) {
	}
	
	
	public void setSolicitudFolios(List listaSolicitudes)
	{
		this.solicitudFolios = listaSolicitudes;
	}
	

	public List getSolicitudesVinculadas() {
		return Collections.unmodifiableList(solicitudesVinculadas);
	}

	public boolean addSolicitudesVinculada(SolicitudVinculadaEnhanced newSolicitudesVinculada) {
		return solicitudesVinculadas.add(newSolicitudesVinculada);
	}

	public boolean removeSolicitudesVinculada(SolicitudVinculadaEnhanced oldSolicitudesVinculada) {
		return solicitudesVinculadas.remove(oldSolicitudesVinculada);
	}
	/**
	 * @return Returns the numReimpresionesRecibo.
	 */
	public int getNumReimpresionesRecibo() {
		return numReimpresionesRecibo;
	}
	/**
	 * @param numReimpresionesRecibo The numReimpresionesRecibo to set.
	 */
	public void setNumReimpresionesRecibo(int numReimpresionesRecibo) {
		this.numReimpresionesRecibo = numReimpresionesRecibo;
	}
}
