package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.SolicitudPermisoCorreccion;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class SolicitudPermisoCorreccionEnhanced  extends Enhanced{

    private String idPermiso; // pk 
    private String idSolicitud; // pk 
    private Date fechaCreacion;
    private PermisoCorreccionEnhanced permiso;
    private SolicitudEnhanced solicitud; // inverse SolicitudCorreccionEnhanced.solicitudPermisoCorreccionEnhanced

    public SolicitudPermisoCorreccionEnhanced() {
    }

    public String getIdPermiso() {
        return idPermiso;
    }

    public void setIdPermiso(String idPermiso) {
        this.idPermiso = idPermiso;
    }

    public String getIdSolicitud() {
        return idSolicitud;
    }

    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public PermisoCorreccionEnhanced getPermiso() {
        return permiso;
    }

    public void setPermiso(PermisoCorreccionEnhanced permiso) {
        this.permiso = permiso;
        setIdPermiso(permiso.getIdPermiso());
    }

    public SolicitudEnhanced getSolicitud() {
        return solicitud;
    }

    public void setSolicitud(SolicitudEnhanced solicitud) {
        this.solicitud = solicitud;
        setIdSolicitud(solicitud.getIdSolicitud());
    }
    

	public static SolicitudPermisoCorreccionEnhanced enhance(SolicitudPermisoCorreccion solicitud) {
		return (SolicitudPermisoCorreccionEnhanced) Enhanced.enhance(solicitud);
	}
}
