package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.SubtipoAtencion;

import java.util.List;
import java.util.ArrayList;
import java.util.Collections;



/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class SubtipoAtencionEnhanced extends Enhanced{

    private String idSubtipoAtencion; // pk 
    private long minAnotaciones;
    private String nombre;
    private long orden;
    private long unidadesTrabajo;
    private List tiposActo = new ArrayList(); // contains SubtipoAtencionTipoActo  inverse SubtipoAtencionTipoActo.subtipoAtencion
	private List subtipoSolicitudes = new ArrayList(); // contains SubAtencionSubSolicitudEnhanced  inverse SubAtencionSubSolicitudEnhanced.subtipoAtencion
	private long minFolios;

    public SubtipoAtencionEnhanced() {
    }

    public String getIdSubtipoAtencion() {
        return idSubtipoAtencion;
    }

    public void setIdSubtipoAtencion(String idSubtipoAtencion) {
        this.idSubtipoAtencion = idSubtipoAtencion;
    }

    public long getMinAnotacione() {
        return minAnotaciones;
    }

    public void setMinAnotacione(long minAnotaciones) {
        this.minAnotaciones = minAnotaciones;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public long getOrden() {
        return orden;
    }

    public void setOrden(long orden) {
        this.orden = orden;
    }

    public long getUnidadesTrabajo() {
        return unidadesTrabajo;
    }

    public void setUnidadesTrabajo(long unidadesTrabajo) {
        this.unidadesTrabajo = unidadesTrabajo;
    }

    public List getTiposActos() {
        return Collections.unmodifiableList(tiposActo);
    }

    public boolean addTiposActo(SubtipoAtencionTipoActoEnhanced newTiposActo) {
        return tiposActo.add(newTiposActo);
    }

    public boolean removeTiposActo(SubtipoAtencionTipoActoEnhanced oldTiposActo) {
        return tiposActo.remove(oldTiposActo);
    }
    
	public static SubtipoAtencionEnhanced enhance(SubtipoAtencion subtipoAtencion) {
		return (SubtipoAtencionEnhanced) Enhanced.enhance(subtipoAtencion);
	}
	

	

	 public List getSubtipoSolicitudes() {
		 return Collections.unmodifiableList(subtipoSolicitudes);
	 }

	 public boolean addSubtipoSolicitude(SubAtencionSubSolicitudEnhanced newSubtipoSolicitude) {
		 return subtipoSolicitudes.add(newSubtipoSolicitude);
	 }

	 public boolean removeSubtipoSolicitude(SubAtencionSubSolicitudEnhanced oldSubtipoSolicitude) {
		 return subtipoSolicitudes.remove(oldSubtipoSolicitude);
	 }
//	..


    /**
	 * @return
	 */
	public long getMinAnotaciones() {
		return minAnotaciones;
	}

	/**
	 * @param l
	 */
	public void setMinAnotaciones(long l) {
		minAnotaciones = l;
	}

	/**
	 * @return
	 */
	public long getMinFolios() {
		return minFolios;
	}

	/**
	 * @param l
	 */
	public void setMinFolios(long l) {
		minFolios = l;
	}

}