package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.SucursalBanco;

/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class SucursalBancoEnhanced extends Enhanced{

	private String idBanco; // pk 
	private String idSucursal; // pk 
	private String nombre;
	private BancoEnhanced banco;

	public SucursalBancoEnhanced() {
	}

	public String getIdBanco() {
		return idBanco;
	}

	public void setIdBanco(String idBanco) {
		this.idBanco = idBanco;
	}

	public String getIdSucursal() {
		return idSucursal;
	}

	public void setIdSucursal(String idSucursal) {
		this.idSucursal = idSucursal;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BancoEnhanced getBanco() {
		return banco;
	}

	public void setBanco(BancoEnhanced banco) {
		this.banco = banco;
		setIdBanco(banco.getIdBanco());
	}
	
	public static SucursalBancoEnhanced enhance(SucursalBanco sucursalBanco) {
		return (SucursalBancoEnhanced) Enhanced.enhance(sucursalBanco);
	}
}