package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.Tarifa;

import java.util.Date;

/*
 * Generated by JDO Genie (version:3.2.0beta7 (20 Sep 2004))
 */
public class TarifaEnhanced extends Enhanced{

    private String idCodigo; // pk 
    private String idTipo; // pk 
    private long idVersion; // pk 
    private Date fechaCreacion;
    private Date fechaInicial;
    private double valor;
    private TipoTarifaEnhanced tipoTarifa; // inverse TipoTarifa.tarifas

    public TarifaEnhanced() {
    }

    public String getIdCodigo() {
        return idCodigo;
    }

    public void setIdCodigo(String idCodigo) {
        this.idCodigo = idCodigo;
    }

    public String getIdTipo() {
        return idTipo;
    }

    public void setIdTipo(String idTipo) {
        this.idTipo = idTipo;
    }

    public long getIdVersion() {
        return idVersion;
    }

    public void setIdVersion(long idVersion) {
        this.idVersion = idVersion;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Date getFechaInicial() {
        return fechaInicial;
    }

    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }

    public double getValor() {
        return valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    public TipoTarifaEnhanced getTipoTarifa() {
        return tipoTarifa;
    }

    public void setTipoTarifa(TipoTarifaEnhanced tipoTarifa) {
        this.tipoTarifa = tipoTarifa;
        setIdTipo(tipoTarifa.getIdTipo());
    }
    
	public static TarifaEnhanced enhance(Tarifa tarifa) {
		return (TarifaEnhanced) Enhanced.enhance(tarifa);
	}
}