package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.TipoOficina;

/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class TipoOficinaEnhanced extends Enhanced {
    private String idTipoOficina; // pk 
    private String nombre;
    private UsuarioEnhanced usuario;

    public TipoOficinaEnhanced() {
    }

    public UsuarioEnhanced getUsuario() {
		return usuario;
	}

	public void setUsuario(UsuarioEnhanced usuario) {
		this.usuario = usuario;
	}

	public String getIdTipoOficina() {
        return idTipoOficina;
    }

    public void setIdTipoOficina(String idTipoOficina) {
        this.idTipoOficina = idTipoOficina;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    
    
	public static TipoOficinaEnhanced enhance (
	TipoOficina tipoOficina)
	{
		return (TipoOficinaEnhanced)Enhanced.enhance(tipoOficina);
	}


    public int hashCode() {
		int result = 0;
		result = (29 * result) +
			((idTipoOficina != null) ? idTipoOficina.hashCode() : 0);

		return result;
	}



	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}

		if (!(o instanceof TipoOficinaEnhanced)) {
			return false;
		}

		final TipoOficinaEnhanced id = (TipoOficinaEnhanced) o;

		if ((this.idTipoOficina != null)
				? (!idTipoOficina.equals(id.idTipoOficina))
					: (id.idTipoOficina != null)) {
			return false;
		}

		return true;
	}
	
}
