package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.TipoPago;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class TipoPagoEnhanced extends Enhanced{

    private long idTipoDocPago; // pk 
    private Date fechaCreacion;
    private String nombre;

    public TipoPagoEnhanced() {
    }

    public long getIdTipoDocPago() {
        return idTipoDocPago;
    }

    public void setIdTipoDocPago(long idTipoDocPago) {
        this.idTipoDocPago = idTipoDocPago;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
 
	public static TipoPagoEnhanced enhance (
	TipoPago tipoPago)
	{
		return (TipoPagoEnhanced)Enhanced.enhance(tipoPago);
	}
}