package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.TipoImpuesto;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class TipoImpuestoEnhanced  extends Enhanced{

    private String idTipoImpuesto; // pk 
    private String nombre;

    public TipoImpuestoEnhanced() {
    }

    public String getIdTipoImpuesto() {
        return idTipoImpuesto;
    }

    public void setIdTipoImpuesto(String idTipoImpuesto) {
        this.idTipoImpuesto = idTipoImpuesto;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    
    
	public static TipoImpuestoEnhanced enhance (
	TipoImpuesto tipoImpuesto)
	{
		return (TipoImpuestoEnhanced)Enhanced.enhance(tipoImpuesto);
	}
}