package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.TipoOficio;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class TipoOficioEnhanced extends Enhanced{

    private String idTipoOficio; // pk 
    private Date fechaCreacion;
    private String nombre;

    public TipoOficioEnhanced() {
    }

    public String getIdTipoOficio() {
        return idTipoOficio;
    }

    public void setIdTipoOficio(String idTipoOficio) {
        this.idTipoOficio = idTipoOficio;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
 
	public static TipoOficioEnhanced enhance (
	TipoOficio tipo)
	{
		return (TipoOficioEnhanced)Enhanced.enhance(tipo);
	}
}
