package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.TipoRecurso;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class TipoRecursoEnhanced extends Enhanced{

    private String idTipoRecurso; // pk 
    private String descripcion;
    private Date fechaCreacion;

    public TipoRecursoEnhanced() {
    }

    public String getIdTipoRecurso() {
        return idTipoRecurso;
    }

    public void setIdTipoRecurso(String idTipoRecurso) {
        this.idTipoRecurso = idTipoRecurso;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
 
	public static TipoRecursoEnhanced enhance (TipoRecurso tipoTarifa){
		return (TipoRecursoEnhanced)Enhanced.enhance(tipoTarifa);
	}
}
