package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.TipoFotocopia;

import java.util.Date;

/*
 * Generated by JDO Genie (version:3.2.0beta7 (20 Sep 2004))
 */
public class TipoFotocopiaEnhanced extends Enhanced{

    private String idTipoFotocopia; // pk 
    private Date fechaCreacion;
    private String nombre;
    
    public TipoFotocopiaEnhanced() {
    }

    public String getIdTipoFotocopia() {
        return idTipoFotocopia;
    }

    public void setIdTipoFotocopia(String idTipoFotocopia) {
        this.idTipoFotocopia = idTipoFotocopia;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

	public static TipoFotocopiaEnhanced enhance (
	TipoFotocopia tipoFotocopia)
	{
		return (TipoFotocopiaEnhanced)Enhanced.enhance(tipoFotocopia);
	}
}