package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.TipoAnotacion;




/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class TipoAnotacionEnhanced extends Enhanced{
    private String idTipoAnotacion; // pk 
    private String nombre;

    public TipoAnotacionEnhanced() {
    }

    public String getIdTipoAnotacion() {
        return idTipoAnotacion;
    }

    public void setIdTipoAnotacion(String idTipoAnotacion) {
        this.idTipoAnotacion = idTipoAnotacion;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
	public static TipoAnotacionEnhanced enhance(TipoAnotacion tipoAnotacion) {
		return (TipoAnotacionEnhanced) Enhanced.enhance(tipoAnotacion);
	}
}
