package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.TipoPantalla;


/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class TipoPantallaEnhanced extends Enhanced{

    private long idTipoPantalla; // pk
    private String nombre;

    public TipoPantallaEnhanced() {
    }

    public long getIdTipoPantalla() {
        return idTipoPantalla;
    }

    public void setIdTipoPantalla(long idTipoPantalla) {
        this.idTipoPantalla = idTipoPantalla;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


   
	public static TipoPantallaEnhanced enhance (
	TipoPantalla tipoPantalla)
	{
		return (TipoPantallaEnhanced)Enhanced.enhance(tipoPantalla);
	}
}
