package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.TipoDocumento;

/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class TipoDocumentoEnhanced extends Enhanced {

    private String idTipoDocumento; // pk 
    private String nombre;
    private UsuarioEnhanced usuario;

    public UsuarioEnhanced getUsuario() {
        return usuario;
    }

    public void setUsuario(UsuarioEnhanced usuario) {
        this.usuario = usuario;
    }

    public TipoDocumentoEnhanced() {
    }

    public String getIdTipoDocumento() {
        return idTipoDocumento;
    }

    public void setIdTipoDocumento(String idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public static TipoDocumentoEnhanced enhance(
            TipoDocumento tipoDocumento) {
        return (TipoDocumentoEnhanced) Enhanced.enhance(tipoDocumento);
    }
}
