package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.Traslado;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class TrasladoEnhanced extends Enhanced{

    private String idTraslado; // pk 
    private Date fechaTraslado;
    /**
    * @author      :  Julio Alcazar
    * @change      :  Revision: FolioDestino cambio de ser un objeto FolioEnhanced a ser String
    * Caso Mantis  :  0007676: Acta - Requerimiento No 247 - Traslado de Folios V2
    */
    private String folioDestino;
    private FolioEnhanced folioOrigen;
    private String resolucion;
    /**
     * @author      :  Julio Alcazar
     * @change      :  nuevas propiedades de el objeto
     * Caso Mantis  :  0007676: Acta - Requerimiento No 247 - Traslado de Folios V2
     */
    private String resolucionDestino;
    private Date fechaResolucionOrigen;
    private Date fechaResolucionDestino;

    /**
        * @author     : Carlos Torres
        * Caso Mantis : 14985: Acta - Requerimiento 028_589_Formato_de_certificado_expedido_para_matrículas_trasladadas
        */
    private TrasladoDatosEnhanced trasladoDatos;
    private Date fechaConfirTras;

    public Date getFechaResolucionDestino() {
        return fechaResolucionDestino;
    }

    public void setFechaResolucionDestino(Date fechaResolucionDestino) {
        this.fechaResolucionDestino = fechaResolucionDestino;
    }

    public Date getFechaResolucionOrigen() {
        return fechaResolucionOrigen;
    }

    public void setFechaResolucionOrigen(Date fechaResolucionOrigen) {
        this.fechaResolucionOrigen = fechaResolucionOrigen;
    }

    public String getResolucionDestino() {
        return resolucionDestino;
    }

    public void setResolucionDestino(String resolucionDestino) {
        this.resolucionDestino = resolucionDestino;
    }

    public TrasladoEnhanced() {
    }

    public String getIdTraslado() {
        return idTraslado;
    }

    public void setIdTraslado(String idTraslado) {
        this.idTraslado = idTraslado;
    }

    public Date getFechaTraslado() {
        return fechaTraslado;
    }

    public void setFechaTraslado(Date fechaTraslado) {
        this.fechaTraslado = fechaTraslado;
    }

    /**
    * @author      :  Julio Alcazar
    * @change      :  Revision: FolioDestino cambio de ser un objeto FolioEnhanced a ser String
    * Caso Mantis  :  0007676: Acta - Requerimiento No 247 - Traslado de Folios V2
    */
    public String getFolioDestino() {
        return folioDestino;
    }

    /**
    * @author      :  Julio Alcazar
    * @change      :  Revision: FolioDestino cambio de ser un objeto FolioEnhanced a ser String
    * Caso Mantis  :  0007676: Acta - Requerimiento No 247 - Traslado de Folios V2
    */
    public void setFolioDestino(String folioDestino) {
        this.folioDestino = folioDestino;
    }

    public FolioEnhanced getFolioOrigen() {
        return folioOrigen;
    }

    public void setFolioOrigen(FolioEnhanced folioOrigen) {
        this.folioOrigen = folioOrigen;
    }
    
    public String getResolucion() {
    	return resolucion;
    }
    
    public void setResolucion(String resolucion) {
    	this.resolucion = resolucion;
    }


    public TrasladoDatosEnhanced getTrasladoDatos() {
        return trasladoDatos;
    }

    public void setTrasladoDatos(TrasladoDatosEnhanced trasladoDatos) {
        this.trasladoDatos = trasladoDatos;
    }
    

    public static TrasladoEnhanced enhance (Traslado traslado)
    {
            return (TrasladoEnhanced)Enhanced.enhance(traslado);
    }

    public Date getFechaConfirTras() {
        return fechaConfirTras;
    }

    public void setFechaConfirTras(Date fechaConfirTras) {
        this.fechaConfirTras = fechaConfirTras;
    }
        
}