package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.TurnoFolio;

import java.util.Date;


/*
 * Generated by JDO Genie (version:3.2.0beta7 (20 Sep 2004))
 */
public class TurnoFolioEnhanced extends Enhanced {
    private String anio; // pk 
    private String idCirculo; // pk 
    private String idMatricula; // pk 
    private long idProceso; // pk 
    private String idTurno; // pk 
    private Date fechaApertura;
    private FolioEnhanced folio; // inverse Folio.turnosFolio
    private TurnoEnhanced turno;

    public TurnoFolioEnhanced() {
    }

    public String getAnio() {
        return anio;
    }

    public void setAnio(String anio) {
        this.anio = anio;
    }

    public String getIdCirculo() {
        return idCirculo;
    }

    public void setIdCirculo(String idCirculo) {
        this.idCirculo = idCirculo;
    }

    public String getIdMatricula() {
        return idMatricula;
    }

    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }

    public long getIdProceso() {
        return idProceso;
    }

    public void setIdProceso(long idProceso) {
        this.idProceso = idProceso;
    }

    public String getIdTurno() {
        return idTurno;
    }

    public void setIdTurno(String idTurno) {
        this.idTurno = idTurno;
    }

    public Date getFechaApertura() {
        return fechaApertura;
    }

    public void setFechaApertura(Date fechaApertura) {
        this.fechaApertura = fechaApertura;
    }

    public FolioEnhanced getFolio() {
        return folio;
    }

    public void setFolio(FolioEnhanced folio) {
        this.folio = folio;
        setIdMatricula(folio.getIdMatricula());
    }

    public TurnoEnhanced getTurno() {
        return turno;
    }

    public void setTurno(TurnoEnhanced turno) {
        this.turno = turno;
        setAnio(turno.getAnio());
        setIdCirculo(turno.getIdCirculo());
        setIdProceso(turno.getIdProceso());
        setIdTurno(turno.getIdTurno());
    }

    public static TurnoFolioEnhanced enhance(TurnoFolio turnoFolio) {
        return (TurnoFolioEnhanced) Enhanced.enhance(turnoFolio);
    }
}
