/*
 * Created on 26-jul-04
 *
 * To change the template for this generated file go to
 * Window&gt;Preferences&gt;Java&gt;Code Generation&gt;Code and Comments
 */
package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.UsuarioCirculo;



/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class UsuarioCirculoEnhanced extends Enhanced{
    private String idCirculo; // pk 
    private long idUsuario; // pk 
    private CirculoEnhanced circulo; 
    private UsuarioEnhanced usuario; // inverse Usuario.usuarioCirculos

    public UsuarioCirculoEnhanced() {
    }
    public String getIdCirculo() {
        return idCirculo;
    }

    public void setIdCirculo(String idCirculo) {
        this.idCirculo = idCirculo;
    }

    public long getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }

    public CirculoEnhanced getCirculo() {
        return circulo;
    }

    public void setCirculo(CirculoEnhanced circulo) {
        this.circulo = circulo;
    }

    public UsuarioEnhanced getUsuario() {
        return usuario;
    }

    public void setUsuario(UsuarioEnhanced usuario) {
        this.usuario = usuario;
    }
    
	public static UsuarioCirculoEnhanced enhance(UsuarioCirculo usuarioCirculo) {
		return (UsuarioCirculoEnhanced) Enhanced.enhance(usuarioCirculo);
	}


}
