package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.Usuario;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class UsuarioEnhanced extends Enhanced {

    private long idUsuario = 0; // pk 
    private String nombre;
    private String password;
    private String username;
    private String loginID;
    private List llavesBloqueo = new ArrayList(); // contains LlaveBloqueo
    private List usuarioCirculos = new ArrayList(); // contains UsuarioCirculo  inverse UsuarioCirculo.usuario
    private List subtiposAtencion = new ArrayList(); // contains UsuarioSubtipoAtencioEnhanced  inverse UsuarioSubtipoAtencioEnhanced.usuario
    private List repartos = new ArrayList(); // contains RepartoEnhanced  inverse RepartoEnhanced.usuario
    private String apellido1;
    private String apellido2;
    private boolean activo;

    /**
     * @author Cesar Ramírez
     * @change: 1247.ASIGNACION.SOLICITANTE.CORRECCION.INTERNA Tipo de
     * Identificación y Número de Identificación del Usuario
	 *
     */
    private String tipoIdentificacion;
    private long numIdentificacion;

    public UsuarioEnhanced() {
        super();
    }

    public UsuarioEnhanced(String username, String nombre, String pass,
            String loginID) {
        super();
        this.nombre = nombre;
        this.password = pass;
        this.loginID = loginID;
        this.username = username;
    }

    public long getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * @return
     */
    public String getLoginID() {
        return loginID;
    }

    public static UsuarioEnhanced enhance(Usuario usuario) {
        return (UsuarioEnhanced) Enhanced.enhance(usuario);
    }

    /**
     * Este método devuelve el usuario de Auriga a partir del usuario de sir
     *
     * @return org.auriga.core.modelo.transferObjects.Usuario con el id
     */
    public org.auriga.core.modelo.transferObjects.Usuario getUsuarioAuriga() {
        org.auriga.core.modelo.transferObjects.Usuario usuario = new org.auriga.core.modelo.transferObjects.Usuario();
        usuario.setUsuarioId(this.getUsername());
        if (this.getIdUsuario() != 0) {
            usuario.setUsuarioNum(this.getIdUsuario());
        }
        return usuario;
    }

    /**
     * @param string
     */
    public void setLoginID(String string) {
        loginID = string;
    }

    public List getLlavesBloqueos() {
        return Collections.unmodifiableList(llavesBloqueo);
    }

    public boolean addLlavesBloqueo(LlaveBloqueoEnhanced newLlavesBloqueo) {
        return llavesBloqueo.add(newLlavesBloqueo);
    }

    public boolean removeLlavesBloqueo(LlaveBloqueoEnhanced oldLlavesBloqueo) {
        return llavesBloqueo.remove(oldLlavesBloqueo);
    }

    public List getUsuarioCirculos() {
        return Collections.unmodifiableList(usuarioCirculos);
    }

    public boolean addUsuarioCirculo(UsuarioCirculoEnhanced newUsuarioCirculo) {
        return usuarioCirculos.add(newUsuarioCirculo);
    }

    public boolean removeUsuarioCirculo(
            UsuarioCirculoEnhanced oldUsuarioCirculo) {
        return usuarioCirculos.remove(oldUsuarioCirculo);
    }

    public List getRepartos() {
        return Collections.unmodifiableList(repartos);
    }

    public boolean addReparto(RepartoEnhanced newReparto) {
        return repartos.add(newReparto);
    }

    public boolean removeReparto(RepartoEnhanced oldReparto) {
        return repartos.remove(oldReparto);
    }

    public List getSubtiposAtencions() {
        return Collections.unmodifiableList(subtiposAtencion);
    }

    public boolean addSubtiposAtencion(
            UsuarioSubtipoAtencionEnhanced newSubtiposAtencion) {
        return subtiposAtencion.add(newSubtiposAtencion);
    }

    public boolean addListaSubtiposAtencion(
            List nuevosSubtiposAtencion) {
        return subtiposAtencion.addAll(nuevosSubtiposAtencion);
    }

    public boolean removeSubtiposAtencion(UsuarioSubtipoAtencionEnhanced oldSubtiposAtencion) {
        return subtiposAtencion.remove(oldSubtiposAtencion);
    }

    public boolean removeListaSubtiposAtencion(List nuevosSubtiposAtencion) {
        return subtiposAtencion.removeAll(nuevosSubtiposAtencion);
    }

    /**
     * @return
     */
    public boolean isActivo() {
        return activo;
    }

    /**
     * @return
     */
    public String getApellido1() {
        return apellido1;
    }

    /**
     * @return
     */
    public String getApellido2() {
        return apellido2;
    }

    /**
     * @param b
     */
    public void setActivo(boolean b) {
        activo = b;
    }

    /**
     * @param string
     */
    public void setApellido1(String string) {
        apellido1 = string;
    }

    /**
     * @param string
     */
    public void setApellido2(String string) {
        apellido2 = string;
    }

    /**
     * @author Cesar Ramírez
     * @change: 1247.ASIGNACION.SOLICITANTE.CORRECCION.INTERNA Metodos getter y
     * setter.
	 *
     */
    /**
     * @return the tipoIdentificacion *
     */
    public String getTipoIdentificacion() {
        return tipoIdentificacion;
    }

    /**
     * @param tipoIdentificacion the tipoIdentificacion to set *
     */
    public void setTipoIdentificacion(String tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }

    /**
     * @return the numIdentificacion *
     */
    public long getNumIdentificacion() {
        return numIdentificacion;
    }

    /**
     * @param numIdentificacion the numIdentificacion to set *
     */
    public void setNumIdentificacion(long numIdentificacion) {
        this.numIdentificacion = numIdentificacion;
    }
}
