package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.ValidacionNota;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class ValidacionNotaEnhanced extends Enhanced {

    private String idFase; // pk 
    private long idProceso; // pk 
    private String idRespuesta; // pk 
    private Date fechaCreacion;
    private ProcesoEnhanced proceso;
    private boolean validaDetalle;
    private List validacionesNotaDetalle = new ArrayList();

    public ValidacionNotaEnhanced() {
    }

    public String getIdFase() {
        return idFase;
    }

    public void setIdFase(String idFase) {
        this.idFase = idFase;
    }

    public long getIdProceso() {
        return idProceso;
    }

    public void setIdProceso(long idProceso) {
        this.idProceso = idProceso;
    }

    public String getIdRespuesta() {
        return idRespuesta;
    }

    public void setIdRespuesta(String idRespuesta) {
        this.idRespuesta = idRespuesta;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public ProcesoEnhanced getProceso() {
        return proceso;
    }

    public void setProceso(ProcesoEnhanced proceso) {
        this.proceso = proceso;
        setIdProceso(proceso.getIdProceso());
    }
    

	public static ValidacionNotaEnhanced enhance(ValidacionNota validacion) {
		return (ValidacionNotaEnhanced) Enhanced.enhance(validacion);
	}
    

    public boolean isValidaDetalle() {
		return validaDetalle;
	}

	public void setValidaDetalle(boolean validaDetalle) {
		this.validaDetalle = validaDetalle;
	}

	public List getValidacionesNotaDetalle() {
		return validacionesNotaDetalle;
	}

	public void setValidacionesNotaDetalle(List validacionesNotaDetalle) {
		this.validacionesNotaDetalle = validacionesNotaDetalle;
	}
}