package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.WebAnotaHereda;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class WebAnotaHeredaEnhanced extends Enhanced {

    private String idAnotacion; // pk
    private String idMatricula; // pk
    private String idSolicitud; // pk
    private String idWebSegeng; // pk
    private Date fechaCreacion;
    private WebFolioHeredadoEnhanced folio; // inverse WebFolioHeredadoEnhanced.anotacionesHeredadas

    public WebAnotaHeredaEnhanced() {
    }

    public String getIdAnotacion() {
        return idAnotacion;
    }

    public void setIdAnotacion(String idAnotacion) {
        this.idAnotacion = idAnotacion;
    }

    public String getIdMatricula() {
        return idMatricula;
    }

    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }

    public String getIdSolicitud() {
        return idSolicitud;
    }

    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public String getIdWebSegeng() {
        return idWebSegeng;
    }

    public void setIdWebSegeng(String idWebSegeng) {
        this.idWebSegeng = idWebSegeng;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public WebFolioHeredadoEnhanced getFolio() {
        return folio;
    }

    public void setFolio(WebFolioHeredadoEnhanced folio) {
        this.folio = folio;
        setIdMatricula(folio.getIdMatricula());
        setIdSolicitud(folio.getIdSolicitud());
        setIdWebSegeng(folio.getIdWebSegeng());
    }
    

	public static WebAnotaHeredaEnhanced enhance(WebAnotaHereda v){
		return (WebAnotaHeredaEnhanced)Enhanced.enhance(v);
	}
}
