package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.WebDocumento;

import java.util.Date;

/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class WebDocumentoEnhanced extends Enhanced{

    private String idSolicitud; // pk
    private String idWebSegeng; // pk
    private String comentario;
    private Date fecha;
    private Date fechaCreacion;
    private String idOficinaOrigen;
    private String idTipoDocumento;
    private String numero;
    private String oficinaInternacional;
    private WebAnotacionEnhanced anotacion; // inverse WebAnotacionEnhanced.documentos
    /*
     *  @author Carlos Torres
     *  @chage   se agrega validacion de version diferente
     *  @mantis 0013414: Acta - Requerimiento No 069_453_Código_Notaria_NC
     */
    private Long version;

    public WebDocumentoEnhanced() {
    }

    public String getIdSolicitud() {
        return idSolicitud;
    }

    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public String getIdWebSegeng() {
        return idWebSegeng;
    }

    public void setIdWebSegeng(String idWebSegeng) {
        this.idWebSegeng = idWebSegeng;
    }

    public String getComentario() {
        return comentario;
    }

    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getIdOficinaOrigen() {
        return idOficinaOrigen;
    }

    public void setIdOficinaOrigen(String idOficinaOrigen) {
        this.idOficinaOrigen = idOficinaOrigen;
    }

    public String getIdTipoDocumento() {
        return idTipoDocumento;
    }

    public void setIdTipoDocumento(String idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }

    public String getNumero() {
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public String getOficinaInternacional() {
        return oficinaInternacional;
    }

    public void setOficinaInternacional(String oficinaInternacional) {
        this.oficinaInternacional = oficinaInternacional;
    }

    public WebAnotacionEnhanced getAnotacion() {
        return anotacion;
    }

    public void setAnotacion(WebAnotacionEnhanced anotacion) {
        this.anotacion = anotacion;
        setIdSolicitud(anotacion.getIdSolicitud());
        setIdWebSegeng(anotacion.getIdWebSegeng());
    }
    
	public static WebDocumentoEnhanced enhance(WebDocumento v){
		return (WebDocumentoEnhanced)Enhanced.enhance(v);
	}
    /*
     *  @author Carlos Torres
     *  @chage   se agrega validacion de version diferente
     *  @mantis 0013414: Acta - Requerimiento No 069_453_Código_Notaria_NC
     */
    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }
}
