package gov.sir.core.negocio.modelo.jdogenie;

import gov.sir.core.negocio.modelo.WebFolioNuevo;

import java.util.Date;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;

/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class WebFolioNuevoEnhanced extends Enhanced{

    private String idSolicitud; // pk
    private String idWebSegeng; // pk
    private String area;
    private String hectareas;
    private String metros;
    private String centimetros;
    private String privMetros;
    private String privCentimetros;
    private String consMetros;
    private String consCentimetros;
    private String determinaInm;
    private String descripcion;
    private Date fechaCreacion;
    private String nombre;
    private WebEnglobeEnhanced englobe; // inverse WebEnglobeEnhanced.foliosNuevos
    private List direcciones = new ArrayList(); // contains WebDireccionEnhanced  inverse WebDireccionEnhanced.folioNuevo

    public WebFolioNuevoEnhanced() {
    }

    public String getIdSolicitud() {
        return idSolicitud;
    }

    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public String getIdWebSegeng() {
        return idWebSegeng;
    }

    public void setIdWebSegeng(String idWebSegeng) {
        this.idWebSegeng = idWebSegeng;
    }


    public WebEnglobeEnhanced getEnglobe() {
        return englobe;
    }

    public void setEnglobe(WebEnglobeEnhanced englobe) {
        this.englobe = englobe;
        setIdSolicitud(englobe.getIdSolicitud());
        setIdWebSegeng(englobe.getIdWebSegeng());
    }

    public List getDirecciones() {
        return Collections.unmodifiableList(direcciones);
    }

    public boolean addDireccione(WebDireccionEnhanced newDireccione) {
        return direcciones.add(newDireccione);
    }

    public boolean removeDireccione(WebDireccionEnhanced oldDireccione) {
        return direcciones.remove(oldDireccione);
    }
    
    
	public static WebFolioNuevoEnhanced enhance(WebFolioNuevo v){
		return (WebFolioNuevoEnhanced)Enhanced.enhance(v);
	}

    public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

        public String getHectareas() {
            return hectareas;
        }

        public void setHectareas(String hectareas) {
            this.hectareas = hectareas;
        }

        public String getMetros() {
            return metros;
        }

        public void setMetros(String metros) {
            this.metros = metros;
        }

        public String getCentimetros() {
            return centimetros;
        }

        public void setCentimetros(String centimetros) {
            this.centimetros = centimetros;
        }

        public String getPrivMetros() {
            return privMetros;
        }

        public void setPrivMetros(String privMetros) {
            this.privMetros = privMetros;
        }

        public String getPrivCentimetros() {
            return privCentimetros;
        }

        public void setPrivCentimetros(String privCentimetros) {
            this.privCentimetros = privCentimetros;
        }

        public String getConsMetros() {
            return consMetros;
        }

        public void setConsMetros(String consMetros) {
            this.consMetros = consMetros;
        }

        public String getConsCentimetros() {
            return consCentimetros;
        }

        public void setConsCentimetros(String consCentimetros) {
            this.consCentimetros = consCentimetros;
        }

        public String getDeterminaInm() {
            return determinaInm;
        }

        public void setDeterminaInm(String determinaInm) {
            this.determinaInm = determinaInm;
        }

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}
