package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */

/**
 * Clase que define las causales de aumento de recibos de manera manual por parte de los usuarios
 */
public class AumentoRecibo implements TransferObject{

    private String idAumentoRecibo; // pk 
    private Date fechaCreacion;
    private String motivo;
    private long numeroRecibo;
    private Usuario usuario;
private static final long serialVersionUID = 1L;
    /** Metodo constructor por defecto  */
    
    public AumentoRecibo() {
    }

    /**
     * Retorna el identificador único del aumento de recibo
     * @return idAumentoRecibo
     */
    public String getIdAumentoRecibo() {
        return idAumentoRecibo;
    }

    /**
     * Cambia el identificador único del aumento de recibo
     * @paranm idAumentoRecibo
     */
    public void setIdAumentoRecibo(String idAumentoRecibo) {
        this.idAumentoRecibo = idAumentoRecibo;
    }

    /**
     * Retorna la fecha de creación del registro
     * @return fechaCreacion
     */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /**
     * Cambia la fecha de creación del registro
     * @paranm fechaCreacion
     */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /**
     * Retorna el motivo de aumeto de recibo
     * @return motivo
     */
    public String getMotivo() {
        return motivo;
    }

    /**
     * Cambia el motivo de aumeto de recibo
     * @paranm motivo
     */
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    /**
     * Retorna el número de recibo al que se aumento
     * @return numeroRecibo
     */
    public long getNumeroRecibo() {
        return numeroRecibo;
    }

    /**
     * Cambia el número de recibo al que se aumento
     * @paranm numeroRecibo
     */
    public void setNumeroRecibo(long numeroRecibo) {
        this.numeroRecibo = numeroRecibo;
    }

    /**
     * Retorna el identificador del usuario que realiza el aumento
     * @return usuario
     */
    public Usuario getUsuario() {
        return usuario;
    }

    /**
     * Cambia el identificador del usuario que realiza el aumento
     * @paranm usuario
     */
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
}