package gov.sir.core.negocio.modelo;
import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */

/**
 * Clase que modela la informacion de los bloqueos historicos y actuales de folios
 */
public class BloqueoFolio implements TransferObject {
    private String idLlave; // pk 
    private String idMatricula; // pk 
    private Folio folio; // inverse Folio.bloqueoFolio
    private LlaveBloqueo llaveBloqueo; // inverse LlaveBloqueo.bloqueoFolio
	private Date fechaBloqueo;
	private Date fechaDesbloqueo;
	private String idWorkflowBloqueo;
    private static final long serialVersionUID = 1L;
	/** Constructor por defecto */
    public BloqueoFolio() {
    }

    /**
     * Retorna el identificador de la llave de bloqueo
     * @return idLlave
     */
    public String getIdLlave() {
        return idLlave;
    }

    /**
     * Cambia el identificador de la llave de bloqueo
     * @paranm idLlave
     */
    public void setIdLlave(String idLlave) {
        this.idLlave = idLlave;
    }

    /**
     * Retorna el identificador del folio a bloquearse
     * @return idMatricula
     */
    public String getIdMatricula() {
        return idMatricula;
    }

    /**
     * Cambia el identificador del folio a bloquearse
     * @paranm idMatricula
     */
    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }


    /** Retorna el identificador del folio   */
    
    public Folio getFolio() {
        return folio;
    }

    /** Modifica el identificador del folio   */
    
    public void setFolio(Folio folio) {
        this.folio = folio;
        setIdMatricula(folio.getIdMatricula());
    }

    /** Retorna el identificador de la llave de bloqueo  */
    
    public LlaveBloqueo getLlaveBloqueo() {
        return llaveBloqueo;
    }

    /** Modifica el identificador de la llave de bloqueo  */
    
    public void setLlaveBloqueo(LlaveBloqueo llaveBloqueo) {
        this.llaveBloqueo = llaveBloqueo;
        setIdLlave(llaveBloqueo.getIdLlave());
    }

    /**
	 * Retorna la fecha en que se realiza el bloqueo
	 * @return fechaBloqueo
	 */
	public Date getFechaBloqueo() {
		return fechaBloqueo;
	}

	/**
	 * Retorna la fecha en que se realiza el desbloqueo
	 * @return fechaDesbloqueo
	 */
	public Date getFechaDesbloqueo() {
		return fechaDesbloqueo;
	}

	/**
	 * Cambia la fecha en que se realiza el bloqueo
	 * @param date
	 */
	public void setFechaBloqueo(Date date) {
		fechaBloqueo = date;
	}

	/**
	 * Cambia la fecha en que se realiza el desbloqueo
	 * @param date
	 */
	public void setFechaDesbloqueo(Date date) {
		fechaDesbloqueo = date;
	}

	/**
	 * Retorna el identificador del turno que realiza el bloqueo
	 * @return idWorkflowBloqueo
	 */
	public String getIdWorkflowBloqueo() {
		return idWorkflowBloqueo;
	}

	/**
	 * Cambia el identificador del turno que realiza el bloqueo
	 * @param string
	 */
	public void setIdWorkflowBloqueo(String string) {
		idWorkflowBloqueo = string;
	}

}
