package gov.sir.core.negocio.modelo;

import java.util.List;
import java.util.ArrayList;
import java.util.Collections;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by JDO Genie (version:3.2.0beta7 (20 Sep 2004))
 */

/**
 * Clase que modela las categorias en la que se pueden clasificar las minutas 
 */
public class Categoria implements TransferObject{

    private String idCategoria; // pk 
    private String nombre;
    private double valorMin;
    private double unidadMin;
    private double unidadMax;
    private double valorMax;
    private List oficinasOrigen = new ArrayList(); // contains OficinaCategoriaEnhanced  inverse OficinaCategoriaEnhanced.categoria
    private boolean activo = true;
    private static final long serialVersionUID = 1L;
    /** Constructor por defecto */
    public Categoria() {
    }
    

    /**
     * Retorna el identificador de la categoría
     * @return idCategoria  */
    public String getIdCategoria() {
        return idCategoria;
    }

    /**
     * Cambia el identificador de la categoría
     * @param idCategoria
     */
    public void setIdCategoria(String idCategoria) {
        this.idCategoria = idCategoria;
    }


    /**
     * Retorna el nombre de la categoría
     * @return nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Cambia el nombre de la categoría
     * @param nombre
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * Retorna el tope máximo que puede tener las unidades de la minuta para quedar
     * clasificada dentro de la categoría
     * @return unidadMax
     */
    public double getUnidadMax() {
        return unidadMax;
    }

    /**
     * Cambia el tope máximo que puede tener las unidades de la minuta 
     * para quedar clasificada dentro de la categoría
     * @param unidadMax
     */
    public void setUnidadMax(double unidadMax) {
        this.unidadMax = unidadMax;
    }

    /**
     * Retorna el tope máximo que puede tener la cuantía de la minuta 
     * para quedar clasificada dentro de la categoría
     * @return valorMax
     */
    public double getValorMax() {
        return valorMax;
    }

    /**
     * Cambia el tope máximo que puede tener la cuantía de la minuta 
     * para quedar clasificada dentro de la categoría
     * @param valorMax
     */
    public void setValorMax(double valorMax) {
        this.valorMax = valorMax;
    }

    /** Retorna la lista oficinasOrigen  */
    
    public List getOficinasOrigens() {
        return Collections.unmodifiableList(oficinasOrigen);
    }

    /**
     * Añade una oficina de origen a la lista oficinasOrigen
     */
    public boolean addOficinasOrigen(OficinaCategoria newOficinasOrigen) {
        return oficinasOrigen.add(newOficinasOrigen);
    }

    /**
     * Elimina una oficina de origen a la lista oficinasOrigen
     */
    public boolean removeOficinasOrigen(OficinaCategoria oldOficinasOrigen) {
        return oficinasOrigen.remove(oldOficinasOrigen);
    }

    /**
	 * Retorna el tope mínimo que puede tener la cuantía de la minuta 
	 * para quedar clasificada dentro de la categoría
	 * @return valorMin
	 */
	public double getValorMin() {
		return valorMin;
	}

	/**
	 * Cambia el tope mínimo que puede tener la cuantía de la minuta 
	 * para quedar clasificada dentro de la categoría
	 * @param string
	 */
	public void setValorMin(double valorMinimo) {
		valorMin = valorMinimo;
	}

	/**
	 * Retorna el tope mínimo que puede tener las unidades de la minuta 
	 * para quedar clasificada dentro de la categoría
	 * @return unidadMin
	 */
	public double getUnidadMin() {
		return unidadMin;
	}

	/**
	 * Cambia el tope mínimo que puede tener las unidades de la minuta 
	 * para quedar clasificada dentro de la categoría
	 * @param string
	 */
	public void setUnidadMin(double valorMinimo) {
		unidadMin = valorMinimo;
	}
	

	public int hashCode() {
		int result = 0;
		result = 29 * result + (idCategoria != null ? idCategoria.hashCode() : 0);
		return result;
	}


	public boolean isActivo() {
		return activo;
	}


	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}