package gov.sir.core.negocio.modelo;

import java.util.Date;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004)) */

/**
 * Clase que modela los círculos notariales */
public class CirculoNotarial implements TransferObject{
        private static final long serialVersionUID = 1L;
    private String idCirculo; // pk 
    private Date fechaCreacion;
    private String nombre;
    private Circulo circuloRegistral;
    private List zonasNotariales = new ArrayList(); // contains ZonaNotarial  inverse ZonaNotarial.circuloNotarial
    private boolean incluirEnReparto;

    public boolean isIncluirEnReparto() {
		return incluirEnReparto;
	}

	public void setIncluirEnReparto(boolean incluirEnReparto) {
		this.incluirEnReparto = incluirEnReparto;
	}

    /** Constructor por defecto */
    public CirculoNotarial() {
    }

    /**
     * Retorna el identificador del círculo notarial
     * @return idCirculo
     */
    public String getIdCirculo() {
        return idCirculo;
    }

    /**
     * Cambia el identificador del círculo notarial
     * @param idCirculo
     */
    public void setIdCirculo(String idCirculo) {
        this.idCirculo = idCirculo;
    }

    /** Retorna la fecha de creación del registro en la base de datos
     * @return fechaCreacion
     */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /**
     * Cambia la fecha de creación del registro en la base de datos
     * @param fechaCreacion  */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /**
     * Retorna el nombre del círculo notarial
     * @return nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Cambia el nombre del círculo notarial
     * @param nombre
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** Retorna el identificador del circulo registral asociado
     * @return circuloRegistral
     */ 
    public Circulo getCirculoRegistral() {
        return circuloRegistral;
    }

    /**
     * Cambia el identificador del circulo registral asociado
     * @param circuloRegistral
     */
    public void setCirculoRegistral(Circulo circuloRegistral) {
        this.circuloRegistral = circuloRegistral;
    }

    /** Retorna la lista zonasNotariales
     * @return List zonasRegistrales
     */
    public List getZonasNotariales() {
        return Collections.unmodifiableList(zonasNotariales);
    }

    /** Añade una zona notarial a la lista zonasNotariales */
    public boolean addZonasNotariale(ZonaNotarial newZonasNotariale) {
        return zonasNotariales.add(newZonasNotariale);
    }

    /** Elimina una zona notarial a la lista zonasNotariales */
    public boolean removeZonasNotariale(ZonaNotarial oldZonasNotariale) {
        return zonasNotariales.remove(oldZonasNotariale);
    }
}