package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004)) */
/**
 * Clase que modela los diferentes tipos de pago habilitados para el circulo
 * registral
 */
public class CirculoTipoPago implements TransferObject {

    private String idCirculoTipoPago; // pk
    private String idCirculo;
    private long idTipoDocPago;
    private String idCuentaBancaria;
    private String idCanalRecaudo;
    private Date fechaCreacion;
    private Circulo circulo; // inverse CirculoEnhanced.tiposPago
    private TipoPago tipoPago;
    private CuentasBancarias cuentasBancarias;
    private CanalesRecaudo canalesRecaudo;
    private boolean ctpActivo;
    private boolean canalSir;
    private static final long serialVersionUID = 1L;
    /**Constructor por defecto */
    public CirculoTipoPago() {
    }

    /** Retorna el identificador del círculo registral */
    public String getIdCirculo() {
        return idCirculo;
    }

    /** Cambia el identificador del círculo registral */
    public void setIdCirculo(String idCirculo) {
        this.idCirculo = idCirculo;
    }

    /** Retorna el identificador del tipo de pago */
    public long getIdTipoDocPago() {
        return idTipoDocPago;
    }

    /** Cambia el identificador del tipo de pago */
    public void setIdTipoDocPago(long idTipoDocPago) {
        this.idTipoDocPago = idTipoDocPago;
    }

    /** Retorna la fecha creación del registro en la base de datos */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /** Cambia la fecha creación del registro en la base de datos */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /** Retorna el identificador del círculo registral */
    public Circulo getCirculo() {
        return circulo;
    }

    /** Cambia el identificador del círculo registral */
    public void setCirculo(Circulo circulo) {
        this.circulo = circulo;
        setIdCirculo(circulo.getIdCirculo());
    }

    /** Retorna el identificador del tipo de pago */
    public TipoPago getTipoPago() {
        return tipoPago;
    }

    /** Cambia el identificador del tipo de pago */
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
        setIdTipoDocPago(tipoPago.getIdTipoDocPago());
    }

    public String getIdCirculoTipoPago() {
        return idCirculoTipoPago;
    }

    public void setIdCirculoTipoPago(String idCirculoTipoPago) {
        this.idCirculoTipoPago = idCirculoTipoPago;
    }

    public String getIdCuentaBancaria() {
        return idCuentaBancaria;
    }

    public void setIdCuentaBancaria(String idCuentaBancaria) {
        this.idCuentaBancaria = idCuentaBancaria;
    }

    public String getIdCanalRecaudo() {
        return idCanalRecaudo;
    }

    public void setIdCanalRecaudo(String idCanalRecaudo) {
        this.idCanalRecaudo = idCanalRecaudo;
    }

    public CanalesRecaudo getCanalesRecaudo() {
        return canalesRecaudo;
    }

    public void setCanalesRecaudo(CanalesRecaudo canalesRecaudo) {
        this.canalesRecaudo = canalesRecaudo;
        setIdCanalRecaudo(canalesRecaudo.getIdCanal() + "");
    }

    public CuentasBancarias getCuentasBancarias() {
        return cuentasBancarias;
    }

    public void setCuentasBancarias(CuentasBancarias cuentasBancarias) {
        this.cuentasBancarias = cuentasBancarias;
        //setIdCuentaBancaria(cuentasBancarias.getId()+"");
    }

    public boolean isCtpActivo() {
        return ctpActivo;
    }

    public void setCtpActivo(boolean ctpActivo) {
        this.ctpActivo = ctpActivo;
    }

    public boolean isCanalSir() {
        return canalSir;
    }

    public void setCanalSir(boolean canalSir) {
        this.canalSir = canalSir;
    }
    
}
