package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
/**
 * Clase que modela la relación entre círculo, proceso y año con el fin 
 * de guardar las secuencias de turnos y solicitudes 
 */
public class CirculoProceso implements TransferObject {

    private String anio; // pk 
    private String idCirculo; // pk 
    private long idProceso; // pk 
    private long lastIdTurno;
    private Circulo circulo;
    private Proceso proceso;
    private long lastIdSolicitud;
    private long lastIdRepartoNotarial;
    private static final long serialVersionUID = 1L;
    /**
    * Secuencial para el manejo de constancias de pago de devolución. 
    */
    private long secuencialConstDevolucion;
    
    private long secuencialConstMasivos;
    

    /**
     * Constructor por defecto */
    public CirculoProceso() {
    }

    /**
     * Retorna el año
     * @return anio
     */
    public String getAnio() {
        return anio;
    }

    /** Cambia el año
     * @param anio  */
    public void setAnio(String anio) {
        this.anio = anio;
    }

    /** Retorna el identificador del círculo
     * @return idCirculo   */
    public String getIdCirculo() {
        return idCirculo;
    }

    /** Cambia el identificador del círculo */
    public void setIdCirculo(String idCirculo) {
        this.idCirculo = idCirculo;
    }

    /** Retorna el identificador del proceso */
    public long getIdProceso() {
        return idProceso;
    }

    /** Cambia el identificador del proceso */
    public void setIdProceso(long idProceso) {
        this.idProceso = idProceso;
    }

    /** Retorna la secuencia de turnos */
    public long getLastIdTurno() {
        return lastIdTurno;
    }

    /** Cambia la secuencia de turnos */
    public void setLastIdTurno(long lastIdTurno) {
        this.lastIdTurno = lastIdTurno;
    }

    /** Retorna el identificador del círculo */
    public Circulo getCirculo() {
        return circulo;
    }

    /** Cambia el identificador del círculo */
    public void setCirculo(Circulo circulo) {
        this.circulo = circulo;
        setIdCirculo(circulo.getIdCirculo());
    }

    /** Retorna el identificador del proceso */
    public Proceso getProceso() {
        return proceso;
    }

    /** Cambia el identificador del proceso */
    public void setProceso(Proceso proceso) {
        this.proceso = proceso;
        setIdProceso(proceso.getIdProceso());
    }

    /** Retorna la secuencia de solicitudes 
	 * @return  
	 */
	public long getLastIdSolicitud() {
		return lastIdSolicitud;
	}

	/** Cambia la secuencia de solicitudes 
	 * @param  
	 */
	public void setLastIdSolicitud(long l) {
		lastIdSolicitud = l;
	}

	/**
	 * @return
	 */
	public long getLastIdRepartoNotarial() {
		return lastIdRepartoNotarial;
	}

	/**
	 * @param l
	 */
	public void setLastIdRepartoNotarial(long l) {
		lastIdRepartoNotarial = l;
	}

	/**
	 * @return Retorna el secuencial de constancia de devolución.
	 */
	public long getSecuencialConstDevolucion() {
		return secuencialConstDevolucion;
	}

	/**
	 * @param l Nuevo secuencial que va a ser asignado a la constancia de devolución. 
	 */
	public void setSecuencialConstDevolucion(long l) {
		secuencialConstDevolucion = l;
	}

	/**
	 * @return Returns the secuencialConstMasivos.
	 */
	public long getSecuencialConstMasivos() {
		return secuencialConstMasivos;
	}
	/**
	 * @param secuencialConstMasivos The secuencialConstMasivos to set.
	 */
	public void setSecuencialConstMasivos(long secuencialConstMasivos) {
		this.secuencialConstMasivos = secuencialConstMasivos;
	}
}