package gov.sir.core.negocio.modelo;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004)) */

/** Clase que modela los registros de ciudadanos */
public class Ciudadano implements TransferObject {
    private String idCiudadano; // pk 
    private String documento;
    private String nombre;
    private String tipoDoc;
    private String tipoPersona;
    private String sexo;
    private String apellido1;
    private String apellido2;
    private String telefono;
	private List prohibiciones = new ArrayList(); // contains CiudadanoProhibicion  inverse CiudadanoProhibicion.ciudadano
	private boolean solicitante;
	private String idCirculo;
        private static final long serialVersionUID = 1L;
	/** Retorna el identificador del circulo  */
	
    public String getIdCirculo() {
		return idCirculo;
	}

    /** Modifica el identificador del circulo  */
    
	public void setIdCirculo(String idCirculo) {
		this.idCirculo = idCirculo;
	}

	/** Constructor por defecto */
    public Ciudadano() {
    }

    /** Retorna el identificador del ciudadano */
    public String getIdCiudadano() {
        return idCiudadano;
    }

    /** Cambia el identificador del ciudadano */
    public void setIdCiudadano(String idCiudadano) {
        this.idCiudadano = idCiudadano!=null?idCiudadano.toUpperCase():null;
    }

    /** Retorna el número de documento del ciudadano */
    public String getDocumento() {
        return documento;
    }
    
    /** Retorna el tipo de persona del ciudadano*/
    public String getTipoPersona() {
        return tipoPersona;
    }
    
    /** Cambia el tipo de persona del ciudadano*/
    public void setTipoPersona(String tipoPersona) {
        this.tipoPersona = tipoPersona!=null?tipoPersona.toUpperCase().trim():null;
    }
    
    /** Retorna el sexo del ciudadano*/
    public String getSexo() {
        return sexo;
    }
    
    /** Cambia el sexo del ciudadano*/
    public void setSexo(String sexo) {
        this.sexo = sexo!=null?sexo.toUpperCase().trim():null;
    }
    
    /** Cambia el número de documento del ciudadano */
    public void setDocumento(String documento) {
        this.documento = documento!=null?documento.toUpperCase().trim():null;
    }

    /** Retorna el nombre del ciudadano */
    public String getNombre() {
        return nombre;
    }

    /** Cambia el nombre del ciudadano */
    public void setNombre(String nombre) {
        this.nombre = nombre!=null?nombre.toUpperCase().trim():null;
    }

    /** Retorna el tipo de docuemento del ciudadano */
    public String getTipoDoc() {
        return tipoDoc;
    }

    /** Cambia el tipo de docuemento del ciudadano */
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc!=null?tipoDoc.toUpperCase().trim():null;
    }

    /** Retorna el primer apellido del ciudadano, si es persona jurídica se 
     * guarda la razón social en este campo */
    public String getApellido1() {
        return apellido1;
    }

    /** Retorna el segundo apellido del ciudadano
     * @return apellido2  */
    public String getApellido2() {
        return apellido2;
    }

    /** Cambia el primer apellido del ciudadano, si es persona jurídica 
     * se guarda la razón social en este campo
     * @param string  */
    public void setApellido1(String string) {
        this.apellido1 = string!=null?string.toUpperCase().trim():null;
    }

    /** Cambia el segundo apellido del ciudadano
     * @param string  */
    public void setApellido2(String string) {
        this.apellido2 = string!=null?string.toUpperCase().trim():null;
    }

    /**Retorna el teléfono del ciudadano 
	 * @return
	 */
	public String getTelefono() {
		return telefono;
	}

	/** Cambia el teléfono del ciudadano
	 * @param string  */
	public void setTelefono(String string) {
		telefono = string!=null?string.toUpperCase().trim():null;
	}
	
	/** Retorna apellidos, nombres, documento y tipo asociados al ciudadano  */
	
	public String getInfoCiudadano(){
		return ((tipoPersona!= null)? tipoPersona + " - " : " ") + ((apellido1==null)?" ":apellido1) + " " + ((apellido2==null)?" ":apellido2) + " " + ((nombre==null)?" ":nombre) + " - " + tipoDoc + " " + documento;
	}
	
	/** Retorna el nombre completo del ciudadano  */
	
	public String getNombreCompletoCiudadano(){
		return ((nombre==null)?" ":nombre.trim()) + " " +((apellido1==null)?" ":apellido1.trim()) + " " + ((apellido2==null)?" ":apellido2.trim()) + " " ;
	}
	
	/** Retorna la lista prohibiciones  */
	
	public List getProhibiciones() {
		return Collections.unmodifiableList(prohibiciones);
	}

	/** Añade una prohibición a la lista de prohibiciones */
	public boolean addProhibicione(CiudadanoProhibicion newProhibicione) {
		return prohibiciones.add(newProhibicione);
	}

	/** Elimina una prohibición a la lista de prohibiciones */
	public boolean removeProhibicione(CiudadanoProhibicion oldProhibicione) {
		return prohibiciones.remove(oldProhibicione);
	}

	/** Indica si el ciudadano es solicitante o es ciudadano de anotacion
	 * @return
	 */
	public boolean isSolicitante() {
		return solicitante;
	}

	/** Modifica el flag que indica si el ciudadano es solicitante o es ciudadano de anotacion
	 * @param b
	 */
	public void setSolicitante(boolean b) {
		solicitante = b;
	}

}
