

package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004)) */
/** Clase que modela a los ciudadanos con sus prohibiciones */
public class CiudadanoProhibicion implements TransferObject {

    private String idCiudadano; // pk 
    private String idProhibicion; // pk 
    private Date fechaCreacion; //pk
    private String idCirculo;
    private Date fechaFinal;
    private Date fechaInicial;
    private Ciudadano ciudadano; // inverse CiudadanoEnhanced.ciudadanoProhibicionEnhanced
    private Prohibicion prohibicion;
	private String comentario;
	private Usuario usuarioCreacion;
	private Usuario usuarioEliminacion;
	private String comentarioAnulacion;
        private static final long serialVersionUID = 1L;
	/** Constructor por defecto */
    public CiudadanoProhibicion() {
    }

    /** Retorna el identificador del ciudadano */
    public String getIdCiudadano() {
        return idCiudadano;
    }

    /** Cambia el identificador del ciudadano */
    public void setIdCiudadano(String idCiudadano) {
        this.idCiudadano = idCiudadano;
    }
    
    /** Retorna el identificador del ciudadano */
    public String getIdCirculo() {
        return idCirculo;
    }

    /** Cambia el identificador del ciudadano */
    public void setIdCirculo(String idCirculo) {
        this.idCirculo = idCirculo;
    }

    /** Retorna el identificador de la prohibición */
    public String getIdProhibicion() {
        return idProhibicion;
    }

    /** Cambia el identificador de la prohibición */
    public void setIdProhibicion(String idProhibicion) {
        this.idProhibicion = idProhibicion;
    }

    /** Retorna la fecha de creación del registro en la base de datos */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /** Cambia la fecha de creación del registro en la base de datos */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /** Retorna la fecha en que se retiro la prohibición */
    public Date getFechaFinal() {
        return fechaFinal;
    }

    /** Cambia la fecha en que se retiro la prohibición */
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }

    /** Retorna la fecha en la que se incluyo la prohibicion   */
    
    public Date getFechaInicial() {
        return fechaInicial;
    }

    /** Modifica la fecha en la que se incluyo la prohibicion   */
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }

    /** Retorna el identificador del ciudadano */
    public Ciudadano getCiudadano() {
        return ciudadano;
    }

    /** Cambia el identificador del ciudadano */
    public void setCiudadano(Ciudadano ciudadano) {
        this.ciudadano = ciudadano;
        setIdCiudadano(ciudadano.getIdCiudadano());
    }

    /** Retorna el identificador de la prohibición */
    public Prohibicion getProhibicion() {
        return prohibicion;
    }

    /** Cambia el identificador de la prohibición */
    public void setProhibicion(Prohibicion prohibicion) {
        this.prohibicion = prohibicion;
        setIdProhibicion(prohibicion.getIdProhibicion());
    }

    /** Retorna el comentario asociado
	 * @return
	 */
	public String getComentario() {
		return comentario;
	}

	/** Modifica el comentario asociado
	 * @param string
	 */
	public void setComentario(String string) {
		comentario = string;
	}

	/** Retorna el Usuario que creó esta instancia
	 * @return
	 */
	public Usuario getUsuarioCreacion() {
		return usuarioCreacion;
	}

	/** Modifica el Usuario que creó esta instancia
	 * @param string
	 */
	public void setUsuarioCreacion(Usuario usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}
	
	/** Retorna el Usuario que eliminó esta instancia
	 * @return
	 */
	public Usuario getUsuarioEliminacion() {
		return usuarioEliminacion;
	}

	/** Modifica el Usuario que eliminó esta instancia
	 * @param string
	 */
	public void setUsuarioEliminacion(Usuario usuarioEliminacion) {
		this.usuarioEliminacion = usuarioEliminacion;
	}

	public String getComentarioAnulacion() {
		return comentarioAnulacion;
	}

	public void setComentarioAnulacion(String comentarioAnulacion) {
		this.comentarioAnulacion = comentarioAnulacion;
	}
	
	
}