package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004)) */
/** Clase que modela la información de la complementación del folio */
public class Complementacion implements TransferObject {

    private String idComplementacion; // pk 
    private String complementacion;
    private String complementacionConflictiva;    
    private static final long serialVersionUID = 1L;
    /** Constructor por defecto */
    public Complementacion() {
    }

    /** Retorna el identificador de la complementacion del folio */
    public String getIdComplementacion() {
        return idComplementacion;
    }

    /** Cambia el identificador de la complementacion del folio */
    public void setIdComplementacion(String idComplementacion) {
        this.idComplementacion = idComplementacion;
    }

    /** Retorna el identificador de la complementacion del folio */
    public String getComplementacion() {
        return complementacion;
    }

    /** Cambia el identificador de la complementacion del folio */
    public void setComplementacion(String complementacion) {
        this.complementacion = complementacion;
    }
    
	/**
	 * Retorna la complementacion conflictiva. (Que es del sistema FOLIO)
	 * @return
	 */
	public String getComplementacionConflictiva() {
		return complementacionConflictiva;
	}

	/**
	 * Cambia la complementacion conflictiva. (Que es del sistema FOLIO)
	 * @param complementacionConflictiva
	 */
	public void setComplementacionConflictiva(String complementacionConflictiva) {
		this.complementacionConflictiva = complementacionConflictiva;
	}


}