package gov.sir.core.negocio.modelo;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.auriga.core.modelo.TransferObject;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004)) */
/** Clase que modela la información de departamentos */
public class Departamento implements TransferObject {
    private String idDepartamento; // pk 
    private String nombre;
    private List municipios = new ArrayList(); // contains Municipio  inverse Municipio.departamento
	private static final long serialVersionUID = 1L;
    /** Constructor por defecto */
    public Departamento() {
    }

    /** Retorna el identificador del departamento */
    public String getIdDepartamento() {
        return idDepartamento;
    }

    /** Cambia el identificador del departamento */
    public void setIdDepartamento(String idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    /**Retorna el nombre del departamento */
    public String getNombre() {
        return nombre;
    }

    /**Cambia el nombre del departamento */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** Retorna la lista municipios */
    public List getMunicipios() {
        return Collections.unmodifiableList(municipios);
    }

    /** Añade un municipio a la lista municipios */
    public boolean addMunicipio(Municipio newMunicipio) {
        return municipios.add(newMunicipio);
    }

    /** Elimina un municipio a la lista municipios */
    public boolean removeMunicipio(Municipio oldMunicipio) {
        return municipios.remove(oldMunicipio);
    }


    public boolean equals(Object o) {
		if (this == o) {
			return true;
		}

		if (!(o instanceof Departamento)) {
			return false;
		}

		final Departamento id = (Departamento) o;

		if ((this.idDepartamento != null)
				? (!idDepartamento.equals(id.idDepartamento))
					: (id.idDepartamento != null)) {
			return false;
		}

		return true;
	}

}
