package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;

import java.util.Date;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004)) */

/** Clase que modela la informacion de los documentos radicados */
public class Documento implements TransferObject {
    private String idDocumento; // pk 
    private Date fecha;
    private String numero;
    private OficinaOrigen oficinaOrigen;
    private TipoDocumento tipoDocumento;
    private String comentario;
    private String oficinaInternacional;
    private String circulo;
    private static final long serialVersionUID = 1L;
    /** Metodo constructor por defecto  */
    
    public Documento() {
    }

    /**
     * Obtener el atributo comentario
     * @return Retorna el atributo comentario
     */
    public String getComentario() {
        return comentario;
    }

    /**
     * Actualizar el valor del atributo comentario
     * @param comentario El nuevo valor del atributo comentario
     */
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    /**
     * Obtener el atributo fecha
     * @return Retorna el atributo fecha
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * Actualizar el valor del atributo fecha
     * @param fecha El nuevo valor del atributo fecha
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * Obtener el atributo idDocumento
     * @return Retorna el atributo idDocumento
     */
    public String getIdDocumento() {
        return idDocumento;
    }

    /**
     * Actualizar el valor del atributo idDocumento
     * @param idDocumento El nuevo valor del atributo idDocumento
     */
    public void setIdDocumento(String idDocumento) {
        this.idDocumento = idDocumento;
    }

    /**
     * Obtener el atributo numero
     * @return Retorna el atributo numero
     */
    public String getNumero() {
        return numero;
    }

    /**
     * Actualizar el valor del atributo numero
     * @param numero El nuevo valor del atributo numero
     */
    public void setNumero(String numero) {
        this.numero = numero;
    }

    /**
     * Obtener el atributo oficinaInternacional
     * @return Retorna el atributo oficinaInternacional
     */
    public String getOficinaInternacional() {
        return oficinaInternacional;
    }

    /**
     * Actualizar el valor del atributo oficinaInternacional
     * @param oficinaInternacional El nuevo valor del atributo oficinaInternacional
     */
    public void setOficinaInternacional(String oficinaInternacional) {
        this.oficinaInternacional = oficinaInternacional;
    }

    /**
     * Obtener el atributo oficinaOrigen
     * @return Retorna el atributo oficinaOrigen
     */
    public OficinaOrigen getOficinaOrigen() {
        return oficinaOrigen;
    }

    /**
     * Actualizar el valor del atributo oficinaOrigen
     * @param oficinaOrigen El nuevo valor del atributo oficinaOrigen
     */
    public void setOficinaOrigen(OficinaOrigen oficinaOrigen) {
        this.oficinaOrigen = oficinaOrigen;
    }

    /**
     * Obtener el atributo tipoDocumento
     * @return Retorna el atributo tipoDocumento
     */
    public TipoDocumento getTipoDocumento() {
        return tipoDocumento;
    }

    /**
     * Actualizar el valor del atributo tipoDocumento
     * @param tipoDocumento El nuevo valor del atributo tipoDocumento
     */
    public void setTipoDocumento(TipoDocumento tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    public String getCirculo() {
		return circulo;
	}

	public void setCirculo(String circulo) {
		this.circulo = circulo;
	}
}
