package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004)) */
/** Clase que modela los ejes configurados en el sistema */
public class Eje implements TransferObject {
    private String idEje; // pk 
    private String nombre;
    private static final long serialVersionUID = 1L;
    /** Constructor por defecto */
    public Eje() {
    }

    /** Retorna el identificador del eje */
    public String getIdEje() {
        return idEje;
    }

    /** Cambia el identificador del eje */
    public void setIdEje(String idEje) {
        this.idEje = idEje;
    }

    /** Retorna el nombre del eje */
    public String getNombre() {
        return nombre;
    }

    /** Cambia el nombre del eje */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}
