package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by Versant Open Access (version:3.2.9 (17 Jan 2005)) */
/** Clase que modela las entidades publicas configuradas para se parte 
 * de otorgantes de minutas en reparto notarial */
public class EntidadPublica  implements TransferObject {
    private static final long serialVersionUID = 1L;
     private String idEntidadPublica; // pk 
    private Date fechaCreacion;
    private String nit;
    private String nombre;
    private NaturalezaJuridicaEntidad naturalezaJuridica;
	private boolean activo;
	private boolean exento;

	/** Constructor por defecto */
    public EntidadPublica() {
    }

    /** Retorna el identificador de la entidad publica */
    public String getIdEntidadPublica() {
        return idEntidadPublica;
    }

    /** Cambia el identificador de la entidad publica */
    public void setIdEntidadPublica(String idEntidadPublica) {
        this.idEntidadPublica = idEntidadPublica;
    }

    /** Retorna la fecha de creación del registro en la base de datos */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /** Cambia la fecha de creación del registro en la base de datos */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /** Retorna el NIT de la entidad publica */
    public String getNit() {
        return nit;
    }

    /** Cambia el NIT de la entidad publica */
    public void setNit(String nit) {
        this.nit = nit;
    }

    /** Retorna el nombre de la entidad pública */
    public String getNombre() {
        return nombre;
    }

    /** Cambia el nombre de la entidad pública */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** Retorna el identificador de la naturaleza jurídica asociada a la entidad */
    public NaturalezaJuridicaEntidad getNaturalezaJuridica() {
        return naturalezaJuridica;
    }

    /** Cambia el identificador de la naturaleza jurídica asociada a la entidad */
    public void setNaturalezaJuridica(NaturalezaJuridicaEntidad naturalezaJuridica) {
        this.naturalezaJuridica = naturalezaJuridica;
    }

    /** Indica si la entidad publica esta activa
	 * @return activo
	 */
	public boolean isActivo() {
		return activo;
	}

	/** Modifica la marca que indica si la entidad publica esta activa
	 * @param b
	 */
	public void setActivo(boolean b) {
		activo = b;
	}

	public boolean isExento() {
		return exento;
	}

	public void setExento(boolean exento) {
		this.exento = exento;
	}

}
