package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004)) */
/** Clase que modela las secuencias de los recibos por estación  */
public class EstacionRecibo implements TransferObject{

    private String idEstacion; // pk 
    private Date fechaCreacion;
    private long numeroFinal;
    private long numeroInicial;
    private long ultimoNumero;
    private long numeroProceso; //pk
    private static final long serialVersionUID = 1L;
    /** Constructor por defecto */
    public EstacionRecibo() {
    }

    /** Retorna el identificador de la estación */
    public String getIdEstacion() {
        return idEstacion;
    }

    /** Cambia el identificador de la estación */
    public void setIdEstacion(String idEstacion) {
        this.idEstacion = idEstacion;
    }

    /** Retorna la fecha creación del registro en la base de datos */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /** Cambia la fecha creación del registro en la base de datos */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /** Retorna el número final de secuencia de recibo */
    public long getNumeroFinal() {
        return numeroFinal;
    }

    /** Cambia el número final de secuencia de recibo */
    public void setNumeroFinal(long numeroFinal) {
        this.numeroFinal = numeroFinal;
    }

    /** Retorna el número inicial de secuencia de recibo */
    public long getNumeroInicial() {
        return numeroInicial;
    }

    /** Cambia el número inicial de secuencia de recibo */
    public void setNumeroInicial(long numeroInicial) {
        this.numeroInicial = numeroInicial;
    }

    /** Retorna el último número asignado a un recibo, este número varia desde el 
     * número inicial menos uno hasta el número final */
    public long getUltimoNumero() {
        return ultimoNumero;
    }

    /** Cambia el último número asignado a un recibo, este número 
     * varia desde el número inicial menos uno hasta el número final */
    public void setUltimoNumero(long ultimoNumero) {
        this.ultimoNumero = ultimoNumero;
    }
    
    public long getNumeroProceso() {
		return numeroProceso;
	}

	public void setNumeroProceso(long numeroProceso) {
		this.numeroProceso = numeroProceso;
	}

	
}