package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))  */

/** Clase que modela la información historica de estados de folio  */

public class EstadoHistoria  implements TransferObject  {

    private String idEstadoHistoria; // pk 
    private String idMatricula; // pk 
    private Date fechaCreacion;
    private Date fechaRegistro;
    private EstadoFolio estadoOrigen;
	private EstadoFolio estadoDestino;
    private Folio folio;
    private Usuario usuario;
    private static final long serialVersionUID = 1L;
	/** Guarda el comentario del cambio de estado */
	private String comentario;
	private String comentarioAnterior;

	/** Constructor por defecto */
    public EstadoHistoria() {
    }

    /** Retorna el identificador del estado relativo al folio */
    public String getIdEstadoHistoria() {
        return idEstadoHistoria;
    }

    /** Cambia el identificador del estado relativo al folio */
    public void setIdEstadoHistoria(String idEstadoHistoria) {
        this.idEstadoHistoria = idEstadoHistoria;
    }

    /** Retorna el identificador del folio   */
    public String getIdMatricula() {
        return idMatricula;
    }

    /** Cambia el identificador del folio   */
    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }

    /** Retorna la fecha de creación del registro en la base de datos */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /** Cambia la fecha de creación del registro en la base de datos */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /** Retorna la fecha de registro del nuevo estado */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /** Cambia la fecha de registro del nuevo estado */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    
    /** Retorna el identificador del folio */
    
    public Folio getFolio() {
        return folio;
    }

    /** Modifica el identificador del folio */
    
    public void setFolio(Folio folio) {
        this.folio = folio;
        setIdMatricula(folio.getIdMatricula());
    }

    /** Retorna el identificador del usuario que cambia el estado */
    public Usuario getUsuario() {
        return usuario;
    }

    /** Cambia el identificador del usuario que cambia el estado */
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    /** Retorna el identificador del estado destino del cambio
	 * @return estadoDestino */
    
	public EstadoFolio getEstadoDestino() {
		return estadoDestino;
	}

	/** Retorna el identificador del estado origen del cambio
	 * @return estadoOrigen  */
	
	public EstadoFolio getEstadoOrigen() {
		return estadoOrigen;
	}

	/** Cambia el identificador del estado destino del cambio
	 * @param folio	 */
	
	public void setEstadoDestino(EstadoFolio folio) {
		estadoDestino = folio;
	}

	/** Cambia el identificador del estado origen del cambio
	 * @param folio	 */
	
	public void setEstadoOrigen(EstadoFolio folio) {
		estadoOrigen = folio;
	}

	/** Retorna el comentario del cambio de estado del folio
	 * @return comentario	 */
	
	public String getComentario() {
		return comentario;
	}

	/** Cambia el comentario del cambio de estado del folio
	 * @param string  */
	
	public void setComentario(String string) {
		comentario = string;
	}

	/** Retorna el comentario anterior asociado  */
	
	public String getComentarioAnterior() {
		return comentarioAnterior;
	}

	/** Modifica el comentario anterior asociado  */
	
	public void setComentarioAnterior(String comentarioAnterior) {
		this.comentarioAnterior = comentarioAnterior;
	}

}
