package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004)) */
/** Clase que modela los estados de folio configurados en el sistema */
public class EstadoFolio implements TransferObject {
    private String idEstado; // pk 
    private String nombre;
    private static final long serialVersionUID = 1L;
    
    /**
     * Campo No persistente, utilizado para guardar el comentario
     * del cambio de estado
     */
    private String comentario;
    
  //  public final static String CUSTODIA = "CUSTODIA";
//	public final static String ACTIVO = "ACTIVO";

    /** Constructor por defecto  */
    public EstadoFolio() {
    }

    /** Retorna el identificador del estado de folio */
    public String getIdEstado() {
        return idEstado;
    }

    /** Cambia el identificador del estado de folio */
    public void setIdEstado(String idEstado) {
        this.idEstado = idEstado;
    }

    /** Retorna el nombre del estado de folio */
    public String getNombre() {
        return nombre;
    }

    /** Cambia el nombre del estado de folio */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** Retorna el comentario asociado
	 * @return comentario
	 */
	public String getComentario() {
		return comentario;
	}

	/** Modifica el comentario asociado
	 * @param string
	 */
	public void setComentario(String string) {
		comentario = string;
	}


}
