package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))  */
/** Clase que modela las secuencias de los recibos por estación */
public class EstadoAnotacion implements TransferObject{

    private String idEstadoAn; // pk 
    private String nombre;
    private static final long serialVersionUID = 1L;
    /** Constructor por defecto */
    public EstadoAnotacion() {
    }

    /** Retorna el identificador del estado de la anotación */
    public String getIdEstadoAn() {
        return idEstadoAn;
    }

    /** Cambia el identificador del estado de la anotación */
    public void setIdEstadoAn(String idEstadoAn) {
        this.idEstadoAn = idEstadoAn;
    }

    /** Retorna el nombre del estado de la anotación */
    public String getNombre() {
        return nombre;
    }

    /** Cambia el nombre del estado de la anotación */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}