package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))   */

/** Clase que modela las sesiones y direcciones IP asociadas a impresión   */

public class Impresion implements TransferObject{

    private String idSesion; // pk 
    private boolean administrador;
    private String direccionIP;
    private Date fechaCreacion;
    private String puerto;
    private String circulo;
    private static final long serialVersionUID = 1L;
    /** Constructor por defecto  */
    public Impresion()  {
    }

    /** Retorna el identificador de la sesión  */
    public String getIdSesion() {
        return idSesion;
    }

    /** Cambia el identificador de la sesión  */
    public void setIdSesion(String idSesion) {
        this.idSesion = idSesion;
    }

    /** Retorna la dirección IP asociada a la sesión  */
    public String getDireccionIP() {
        return direccionIP;
    }

    /** Cambia la dirección IP asociada a la sesión  */
    public void setDireccionIP(String direccionIP) {
        this.direccionIP = direccionIP;
    }

    /** Retorna la fecha de creación del registro en la base de datos  */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /** Cambia la fecha de creación del registro en la base de datos  */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /** Retorna el número de puerto asociado  */
    public String getPuerto() {
        return puerto;
    }

    /** Cambia el número de puerto asociado  */
    public void setPuerto(String puerto) {
        this.puerto = puerto;
    }
    
	/**
	 * @return el circulo
	 */
	public String getCirculo() {
		return circulo;
	}

	/**
	 * @param setea el circulo
	 */
	public void setCirculo(String circulo) {
		this.circulo = circulo;
	}
    
    
    /** Indica si la sesion es de administrador
	 * @return
	 */
	public boolean isAdministrador() {
		return administrador;
	}

	/** Modifica la marca que indica si la sesion es de administrador
	 * @param b
	 */
	public void setAdministrador(boolean b) {
		administrador = b;
	}


}
