package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class ImprimiblePdf implements TransferObject {

    private int idImprimible; // pk
    private byte[] datosImprimible;
    private Date fechaCreacion;
    private String turno;
    private int numeroBytes;
    private String tipoImprimible;
    private String circulo;
    private int numeroImpresiones;
    private static final long serialVersionUID = 1L;
	public String getCirculo() {
		return circulo;
	}

	public void setCirculo(String circulo) {
		this.circulo = circulo;
	}

	public int getNumeroImpresiones() {
		return numeroImpresiones;
	}

	public void setNumeroImpresiones(int numeroImpresiones) {
		this.numeroImpresiones = numeroImpresiones;
	}

	public int getNumeroBytes() {
		return numeroBytes;
	}

	public void setNumeroBytes(int numeroBytes) {
		this.numeroBytes = numeroBytes;
	}

	public String getTipoImprimible() {
		return tipoImprimible;
	}

	public void setTipoImprimible(String tipoImprimible) {
		this.tipoImprimible = tipoImprimible;
	}

	public String getTurno() {
		return turno;
	}

	public void setTurno(String turno) {
		this.turno = turno;
	}

	public ImprimiblePdf() {
    }

    public int getIdImprimible() {
        return idImprimible;
    }

    public void setIdImprimible(int idImprimible) {
        this.idImprimible = idImprimible;
    }

    public byte[] getDatosImprimible() {
        return datosImprimible;
    }

    public void setDatosImprimible(byte[] datosImprimible) {
        this.datosImprimible = datosImprimible;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
}
