package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;


/* Generated by JDO Genie (version:3.0.0 (08 Jun 2004)) */

/** Clase que modela las naturalezas juridicas configuradas en el sistema  */

public class NaturalezaJuridica implements TransferObject {

    private String idNaturalezaJuridica; // pk 
    private String nombre;
    private GrupoNaturalezaJuridica grupoNaturalezaJuridica; // inverse GrupoNaturalezaJuridica.naturalezaJuridicas
    private DominioNaturalezaJuridica dominioNaturalezaJuridica;
    private boolean habilitadoCalificacion;
    private static final long serialVersionUID = 1L;
    /*
        *  @author Carlos Torres
        *  @chage   se agrega validacion de version diferente
        *  @mantis 12705: Acta - Requerimiento No 056_453_Modificiación_de_Naturaleza_Jurídica
        */
    private long version;
	
	/** Constructor por defecto */
    public NaturalezaJuridica() {
    }

    /** Retorna el identificador de la naturaleza jurídica */
    public String getIdNaturalezaJuridica() {
        return idNaturalezaJuridica;
    }

    /** Cambia el identificador de la naturaleza jurídica */
    public void setIdNaturalezaJuridica(String idNaturalezaJuridica) {
        this.idNaturalezaJuridica = idNaturalezaJuridica;
    }

    /** Retorna el nombre de la naturaleza jurídica */
    public String getNombre() {
        return nombre;
    }

    /** Cambia el nombre de la naturaleza jurídica */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** Retorna el identificador del grupo de la naturaleza jurídica asociado */
    public GrupoNaturalezaJuridica getGrupoNaturalezaJuridica() {
        return grupoNaturalezaJuridica;
    }

    /** Cambia el identificador del grupo de la naturaleza jurídica asociado */
    public void setGrupoNaturalezaJuridica(GrupoNaturalezaJuridica grupoNaturalezaJuridica) {
        this.grupoNaturalezaJuridica = grupoNaturalezaJuridica;
    }

    /** Retorna el identificador del dominio de la naturaleza jurídica asociado
	 * @return dominioNaturalezaJuridica	 */
	public DominioNaturalezaJuridica getDominioNaturalezaJuridica() {
		return dominioNaturalezaJuridica;
	}

	/** Cambia el identificador del dominio de la naturaleza jurídica asociado
	 * @param juridica
	 */
	public void setDominioNaturalezaJuridica(DominioNaturalezaJuridica juridica) {
		dominioNaturalezaJuridica = juridica;
	}


	/** Indica si la naturaleza juridica esta habilitada para calificacion
	 * @return
	 */
	public boolean isHabilitadoCalificacion() {
		return habilitadoCalificacion;
	}

	/** Modifica la marca que indica si la naturaleza juridica esta habilitada para calificacion
	 * @param b
	 */
	public void setHabilitadoCalificacion(boolean b) {
		habilitadoCalificacion = b;
	}
        /*
        *  @author Carlos Torres
        *  @chage   se agrega validacion de version diferente
        *  @mantis 12705: Acta - Requerimiento No 056_453_Modificiación_de_Naturaleza_Jurídica
        */
        public long getVersion() {
            return version;
        }

        public void setVersion(long version) {
            this.version = version;
        }
}
