package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class NotaActuacion implements TransferObject {

    private String idNotaActuacion; // pk
    private String idSolicitud; // pk
    private String estado;
    private Date fechaCreacion;
    private String nota;
    private Solicitud solicitud; // inverse SolicitudCorreccionEnhanced.notasActuaciones
    private Usuario usuario;
    private static final long serialVersionUID = 1L;
    public NotaActuacion() {
    }

    public String getIdNotaActuacion() {
        return idNotaActuacion;
    }

    public void setIdNotaActuacion(String idNotaActuacion) {
        this.idNotaActuacion = idNotaActuacion;
    }

    public String getIdSolicitud() {
        return idSolicitud;
    }

    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getNota() {
        return nota;
    }

    public void setNota(String nota) {
        this.nota = nota;
    }

    public Solicitud getSolicitud() {
        return solicitud;
    }

    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
        setIdSolicitud(solicitud.getIdSolicitud());
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
}
