package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class NumeroMatricula implements TransferObject{
    private String idNumero; // pk 
private static final long serialVersionUID = 1L;
    /** Metodo constructor  */
    
    public NumeroMatricula() {
    }

    /** Retorna el identificador del numero de matricula  */
    
    public String getIdNumero() {
        return idNumero;
    }

    /** Modifica el identificador del numero de matricula  */
    
    public void setIdNumero(String idNumero) {
        this.idNumero = idNumero;
    }
}
