package gov.sir.core.negocio.modelo;


import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/* Generated by Versant Open Access (version:3.2.6 (17 Nov 2004)) */

/** Clase que modela los registros de oficios dentro de una fase determinada de un turno */

public class Oficio implements TransferObject{

    private String idOficio; // pk 
    private String textoOficio;
    private TurnoHistoria turnoHistoria;
    private boolean firmado;
    private String numero;
    private Date fechaFirma;
	private Date fechaCreacion;
	private TipoOficio tipo;
private static final long serialVersionUID = 1L;
	/** Método constructor por defecto */
    public Oficio() {
    }

    /** Retorna el identificador del oficio  */
    public String getIdOficio() {
        return idOficio;
    }

    /** Cambia el identificador del oficio  */
    public void setIdOficio(String idOficio) {
        this.idOficio = idOficio;
    }

    /** Retorna el texto del oficio  */
    public String getTextoOficio() {
        return textoOficio;
    }

    /** Modifica el texto del oficio  */
    public void setTextoOficio(String textoOficio) {
        this.textoOficio = textoOficio;
    }

    /** Retorna el identificador del historial relativo al turno  */
    public TurnoHistoria getTurnoHistoria() {
        return turnoHistoria;
    }

    /** Cambia el identificador del historial relativo al turno  */
    public void setTurnoHistoria(TurnoHistoria turnoHistoria) {
        this.turnoHistoria = turnoHistoria;
    }

    /** Indica si el oficio fue firmado
	 * @return firmado
	 */
	public boolean isFirmado() {
		return firmado;
	}

	/** Modifica la marca que indica si el oficio fue firmado
	 * @param b
	 */
	public void setFirmado(boolean b) {
		firmado = b;
	}

	/** Retorna el número de oficio
	 * @return numero 		 */
	public String getNumero() {
		return numero;
	}

	/** Cambia el número de oficio
	 * @param string
	 */
	public void setNumero(String string) {
		numero = string;
	}

	/** Retorna la fecha en que se firma el oficio
	 * @return fechaFirma		 */
	public Date getFechaFirma() {
		return fechaFirma;
	}

	/** Cambia la fecha en que se firma el oficio
	 * @param date		 */
	public void setFechaFirma(Date date) {
		fechaFirma = date;
	}

	/** Retorna la fecha de creación del registro en la base de datos
	 * @return fechaCreacion	 */
	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	/** Cambia la fecha de creación del registro en la base de datos
	 * @param date		*/
	public void setFechaCreacion(Date date) {
		fechaCreacion = date;
	}

	/** Retorna el identificador del tipo de oficio
	 * @return tipo		 */
	public TipoOficio getTipo() {
		return tipo;
	}

	/** Cambia el identificador del tipo de oficio
	 * @param oficio	 */
	public void setTipo(TipoOficio oficio) {
		tipo = oficio;
	}

}
