package gov.sir.core.negocio.modelo;

import java.util.Date;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;

import org.auriga.core.modelo.TransferObject;

/* Generated by JDO Genie (version:3.0.0 (08 Jun 2004))	 */

/** Clase que modela los tipos de dato  */

public class OPLookupTypes implements TransferObject {

    private String tipo; // pk 
    private Date fecha_creacion;
    private String descripcion;
    private List OPlookupCodes = new ArrayList(); // contains LookupCodes  inverse LookupCodes.lookupType
    private static final long serialVersionUID = 1L;
    /** Método constructor por defecto  */
    public OPLookupTypes() {
    }

    /** Retorna el identificador del tipo de dato configurado  */
    public String getTipo() {
        return tipo;
    }

    /** Cambia el identificador del tipo de dato configurado  */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    /** Retorna la lista OPlookupCodes */
    public List getOPLookupCodes() {
        return Collections.unmodifiableList(OPlookupCodes);
    }

    /** Añade un LookuoCode a la lista OPlookupCodes  */
    public boolean addOPLookupCode(OPLookupCodes newLookupCode) {
        return OPlookupCodes.add(newLookupCode);
    }

    /** Elimina un LookuoCode a la lista OPlookupCodes  */
    public boolean removeLookupCode(OPLookupCodes oldLookupCode) {
        return OPlookupCodes.remove(oldLookupCode);
    }

    /** Retorna la fecha de creación del registro en la base de datos
	 * @return fecha_creacion
	 */
	public Date getFecha_creacion() {
		return fecha_creacion;
	}

	/** Cambia la fecha de creación del registro en la base de datos
	 * @param date
	 */
	public void setFecha_creacion(Date date) {
		fecha_creacion = date;
	}
	
	/**
     * Retorna la descripcion.
     * @return descripcion
     */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * Modifica la descripcion
	 * @param descripcion
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}