package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/* Generated by Versant Open Access (version:3.2.6 (17 Nov 2004)) */

/** Clase que modela los permisos de corrección configurados en el sistema   */

public class PermisoCorreccion implements TransferObject{

    private String idPermiso; // pk 
    private String descripcion;
    private Date fechaCreacion;
    private static final long serialVersionUID = 1L;
    /** Constructor por defecto */
    public PermisoCorreccion() {
    }

    /** Retorna el identificador del permiso de corrección   */
    public String getIdPermiso() {
        return idPermiso;
    }

    /** Cambia el identificador del permiso de corrección   */
    public void setIdPermiso(String idPermiso) {
        this.idPermiso = idPermiso;
    }

    /** Retorna la descripción del permiso de corrección   */
    public String getDescripcion() {
        return descripcion;
    }

    /** Cambia la descripción del permiso de corrección   */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /** Retorna la fecha de creación del registro en la base de datos  */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /** Cambia la fecha de creación del registro en la base de datos  */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
}
