package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;


/* Generated by JDO Genie (version:3.0.0 (08 Jun 2004)) */

/** Clase que modela los procesos configurados en el sistema  */

public class Proceso implements TransferObject{

    private long idProceso; // pk 
    private String descripcion;
    private String nombre;
    private boolean generaRecibo;
    private static final long serialVersionUID = 1L;
    /** Constructor por defecto   */
    public Proceso() {
    }

	public Proceso(long idProceso, String nombre, String descripcion){
	 	this.idProceso=idProceso;
	 	this.nombre=nombre;
	 	this.descripcion=descripcion;
	}
	
	/** Retorna el identificador del proceso  */
    public long getIdProceso() {
        return idProceso;
    }

    /** Cambia el identificador del proceso  */
    public void setIdProceso(long idProceso) {
        this.idProceso = idProceso;
    }

    /** Retorna la descripción del proceso   */
    public String getDescripcion() {
        return descripcion;
    }

    /** Cambia la descripción del proceso   */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /** Retorna el nombre del proceso   */
    public String getNombre() {
        return nombre;
    }

    /** Cambia el nombre del proceso   */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    /**
	 * @return Returns the generaRecibo.
	 */
	public boolean isGeneraRecibo() {
		return generaRecibo;
	}
	/**
	 * @param generaRecibo The generaRecibo to set.
	 */
	public void setGeneraRecibo(boolean generaRecibo) {
		this.generaRecibo = generaRecibo;
	}
    
	public boolean equals(Object o) {
		if (this == o) return true;
		if (!(o instanceof Proceso)) return false;

		final Proceso id = (Proceso) o;

		if (this.getIdProceso()!= id.getIdProceso()) return false;
		return true;
	}

	public int hashCode() {
		int result = 0;
		result = 29 * result + (int) (idProceso ^ (idProceso >>> 32));
		return result;
	}
	
}