package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/* Generated by Versant Open Access (version:3.2.6 (17 Nov 2004)) */

/** Clase que modela las prohibiciones de ciudadano configuradas en el sistema  */

public class Prohibicion implements TransferObject {

    private String idProhibicion; // pk 
    private Date fechaCreacion;
    private String nombre;
    private String descripcion;
    private static final long serialVersionUID = 1L;
    /** Método constructor por defecto  */
    public Prohibicion() {
    }

    /** Obtiene el identificador de la prohibición  */
    public String getIdProhibicion() {
        return idProhibicion;
    }

    /** Modifica el identificador de la prohibición  */
    public void setIdProhibicion(String idProhibicion) {
        this.idProhibicion = idProhibicion;
    }

    /** Retorna la fecha de creacion del registro en la base de datos */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /** Modifica la fecha de creacion del registro en la base de datos */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /** Retorna el nombre de la prohibición   */
    public String getNombre() {
        return nombre;
    }

    /** Cambia el nombre de la prohibición   */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** Retorna la descripción de la prohibición   */
    public String getDescripcion() {
        return descripcion;
    }

    /** Cambia la descripción de la prohibición   */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}