package gov.sir.core.negocio.modelo;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.auriga.core.modelo.TransferObject;


/* Generated by JDO Genie (version:3.0.0 (08 Jun 2004)) */

/** Clase que modela las salvedades de folio */

public class SalvedadFolio implements TransferObject {
    private String idMatricula; // pk 
    private String idSalvedad; // pk 
    private String descripcion;
    private Folio folio; // inverse Folio.salvedades
    private Usuario usuarioCreacion;
	private List turnoSalvedadFolio = new ArrayList(); // contains TurnoSalvedadAnotacion  inverse TurnoSalvedadAnotacion.salvedad
	private Date fechaCreacion;
	private String numRadicacion;
	private Usuario usuarioCreacionTMP;
	private boolean isTemporal;
	private static final long serialVersionUID = 1L;

	/** Método constructor por defecto  */
    public SalvedadFolio() {
    }

    /** Retorna el identificador de la matrícula  */
    public String getIdMatricula() {
        return idMatricula;
    }

    /** Cambia el identificador de la matrícula  */
    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }

    /** Retorna el identificador de la salvedad relativa al folio  */
    public String getIdSalvedad() {
        return idSalvedad;
    }

    /** Cambia el identificador de la salvedad relativa al folio  */
    public void setIdSalvedad(String idSalvedad) {
        this.idSalvedad = idSalvedad;
    }

    /** Retorna la descripción de la salvedad   */
    public String getDescripcion() {
        return descripcion;
    }

    /** Cambia la descripción de la salvedad   */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /** Retorna el identificador del folio  */
    public Folio getFolio() {
        return folio;
    }

    /** Modifica el identificador del folio  */
    public void setFolio(Folio folio) {
        this.folio = folio;
        setIdMatricula(folio.getIdMatricula());
    }
    
    /** Retorna el usuario que hace definitiva la salvedad 
	 * @return usuarioCreacion
	 */
	public Usuario getUsuarioCreacion() {
		return usuarioCreacion;
	}

	/** Cambia el usuario que hace definitiva la salvedad
	 * @param usuario
	 */
	public void setUsuarioCreacion(Usuario usuario) {
		usuarioCreacion = usuario;
	}
	
	/** Retorna la lista turnoSalvedadFolio */
	public List getTurnoSalvedadFolios() {
		return Collections.unmodifiableList(turnoSalvedadFolio);
	}

	/** Añade un TurnoSalvedadFolio a la lista turnoSalvedadFolio  */
	public boolean addTurnoSalvedadFolio(TurnoSalvedadFolio newTurnoSalvedadFolio) {
		return turnoSalvedadFolio.add(newTurnoSalvedadFolio);
	}

	/** Elimina un TurnoSalvedadFolio a la lista turnoSalvedadFolio  */
	public boolean removeTurnoSalvedadFolio(TurnoSalvedadFolio oldTurnoSalvedadFolio) {
		return turnoSalvedadFolio.remove(oldTurnoSalvedadFolio);
	}

	/** Retorna la fecha de creación del registro en la base de datos
	 * @return fechaCreacion
	 */
	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	 /** Cambia la fecha de creación del registro en la base de datos
	 * @param date
	 */
	public void setFechaCreacion(Date date) {
		fechaCreacion = date;
	}

	/** Numero el identificador del turno que crea el folio
	 * @return
	 */
	public String getNumRadicacion() {
		return numRadicacion;
	}

	/** Modifica el identificador del turno que crea el folio
	 * @param string
	 */
	public void setNumRadicacion(String string) {
		numRadicacion = string;
	}

	/** Retorna el usuario que crea la salvedad del folio
	 * @return
	 */
	public Usuario getUsuarioCreacionTMP() {
		return usuarioCreacionTMP;
	}

	/** Cambia el usuario que crea la salvedad del folio
	 * @param usuario
	 */
	public void setUsuarioCreacionTMP(Usuario usuario) {
		usuarioCreacionTMP = usuario;
	}

	/**
	 * @return Returns the isTemporal.
	 */
	public boolean isTemporal() {
		return isTemporal;
	}

	/**
	 * @param isTemporal The isTemporal to set.
	 */
	public void setTemporal(boolean isTemporal) {
		this.isTemporal = isTemporal;
	}

}
