package gov.sir.core.negocio.modelo;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.auriga.core.modelo.TransferObject;


/* Generated by JDO Genie (version:3.0.0 (08 Jun 2004)) */

/** Clase que modela las salvedades de anotación  */

public class SalvedadAnotacion implements TransferObject {
    private String idAnotacion; // pk 
    private String idMatricula; // pk 
    private String idSalvedad; // pk 
    private String descripcion;
    private Anotacion anotacion; // inverse Anotacion.salvedades
    private Usuario usuarioCreacion;
	private List turnoSalvedadAnotacion = new ArrayList(); // contains TurnoSalvedadAnotacion  inverse TurnoSalvedadAnotacion.salvedad
	private boolean toDelete;
	private Date fechaCreacion;
	private String numRadicacion;
	private Usuario usuarioCreacionTMP;
	private boolean isTemporal;
        private static final long serialVersionUID = 1L;
	/** Método constructor por defecto  */
    public SalvedadAnotacion() {
    }

    /** Retorna el identificador de la anotación  */
    public String getIdAnotacion() {
        return idAnotacion;
    }

    /** Cambia el identificador de la anotación  */
    public void setIdAnotacion(String idAnotacion) {
        this.idAnotacion = idAnotacion;
    }

    /** Retorna el identificador de la matrícula  */
    public String getIdMatricula() {
        return idMatricula;
    }

    /** Cambia el identificador de la matrícula  */
    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }

    /** Retorna el identificador de la salvedad relativa a la anotación  */
    public String getIdSalvedad() {
        return idSalvedad;
    }

    /** Cambia el identificador de la salvedad relativa a la anotación  */
    public void setIdSalvedad(String idSalvedad) {
        this.idSalvedad = idSalvedad;
    }

    /** Retorna la descripción de la salvedad  */
    public String getDescripcion() {
        return descripcion;
    }

    /** Cambia la descripción de la salvedad  */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /** Retorna el identificador de la anotación  */
    public Anotacion getAnotacion() {
        return anotacion;
    }

    /** Cambia el identificador de la anotación  */
    public void setAnotacion(Anotacion anotacion) {
        this.anotacion = anotacion;
        setIdAnotacion(anotacion.getIdAnotacion());
        setIdMatricula(anotacion.getIdMatricula());
    }

    /** Retorna el usuario que hace definitiva la salvedad
	 * @return
	 */
	public Usuario getUsuarioCreacion() {
		return usuarioCreacion;
	}

	/** Cambia el usuario que hace definitiva la salvedad
	 * @param usuario
	 */
	public void setUsuarioCreacion(Usuario usuario) {
		usuarioCreacion = usuario;
	}
	
	/** Retorna la lista turnoSalvedadAnotacion */
	public List getTurnoSalvedadAnotacions() {
		return Collections.unmodifiableList(turnoSalvedadAnotacion);
	}

	/** Añade un TurnoSalvedadAnotacion a la lista turnoSalvedadAnotacion  */
	public boolean addTurnoSalvedadAnotacion(TurnoSalvedadAnotacion newTurnoSalvedadAnotacion) {
		return turnoSalvedadAnotacion.add(newTurnoSalvedadAnotacion);
	}

	/** Elimina un TurnoSalvedadAnotacion a la lista turnoSalvedadAnotacion  */
	public boolean removeTurnoSalvedadAnotacionEnhanced(TurnoSalvedadAnotacion oldTurnoSalvedadAnotacionEnhanced) {
		return turnoSalvedadAnotacion.remove(oldTurnoSalvedadAnotacionEnhanced);
	}

	/**
	 * @return
	 */
	public boolean isToDelete() {
		return toDelete;
	}

	/**
	 * @param b
	 */
	public void setToDelete(boolean b) {
		toDelete = b;
	}
	

	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}

		if (!(o instanceof SalvedadAnotacion)) {
			return false;
		}

		final SalvedadAnotacion id = (SalvedadAnotacion) o;

		if ((this.idAnotacion != null)
				? (!idAnotacion.equals(id.idAnotacion))
					: (id.idAnotacion != null)) {
			return false;
		}

		if ((this.idMatricula != null)
				? (!idMatricula.equals(id.idMatricula))
					: (id.idMatricula != null)) {
			return false;
		}

		if ((this.idSalvedad != null) ? (!idSalvedad.equals(id.idSalvedad))
										  : (id.idSalvedad != null)) {
			return false;
		}

		return true;
	}

	/** Retorna la fecha de creación del registro en la base de datos
	 * @return fechaCreacion
	 */
	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	/** CAmbia la fecha de creación del registro en la base de datos
	 * @param date
	 */
	public void setFechaCreacion(Date date) {
		fechaCreacion = date;
	}

	/**
	 * @return
	 */
	public String getNumRadicacion() {
		return numRadicacion;
	}

	/**
	 * @param string
	 */
	public void setNumRadicacion(String string) {
		numRadicacion = string;
	}

	/** Retorna el usuario que crea la salvedad de la anotación
	 * @return
	 */
	public Usuario getUsuarioCreacionTMP() {
		return usuarioCreacionTMP;
	}

	/** Cambia el usuario que crea la salvedad de la anotación
	 * @param usuario
	 */
	public void setUsuarioCreacionTMP(Usuario usuario) {
		usuarioCreacionTMP = usuario;
	}

	/**
	 * @return Returns the isTemporal.
	 */
	public boolean isTemporal() {
		return isTemporal;
	}

	/**
	 * @param isTemporal The isTemporal to set.
	 */
	public void setTemporal(boolean isTemporal) {
		this.isTemporal = isTemporal;
	}	
	
}
