package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;


/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004)) */

/** Clase que modela las secuencias de las tablas cuyos identificadores 
 * no dependen de otras tablas operativas o de negocio  */ 

public class Secuencias implements TransferObject{

    private String tableName; // pk 
    private long lastUsedId;
    private static final long serialVersionUID = 1L;
    /** Método constructor por defecto  */
    public Secuencias() {
    }

    /** Retorna el nombre de la tabla  */
    public String getTableName() {
        return tableName;
    }

    /** Cambia el nombre de la tabla  */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /** Retorna la secuencia del identificador de la tabla  */
    public long getLastUsedId() {
        return lastUsedId;
    }

    /** Cambia la secuencia del identificador de la tabla  */
    public void setLastUsedId(long lastUsedId) {
        this.lastUsedId = lastUsedId;
    }
}