package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;


/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class SolCheckedItemDev implements TransferObject{

    private String idCheckItemDev; // pk
    private String idSolicitud; // pk
    private Date fechaCreacion;
    private CheckItemDev checkItem;
    private SolicitudDevolucion solicitud; // inverse SolicitudDevolucionEnhanced.checkedItems
    private static final long serialVersionUID = 1L;
    public SolCheckedItemDev() {
    }

    public String getIdCheckItemDev() {
        return idCheckItemDev;
    }

    public void setIdCheckItemDev(String idCheckItemDev) {
        this.idCheckItemDev = idCheckItemDev;
    }

    public String getIdSolicitud() {
        return idSolicitud;
    }

    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public CheckItemDev getCheckItem() {
        return checkItem;
    }

    public void setCheckItem(CheckItemDev checkItem) {
        this.checkItem = checkItem;
        setIdCheckItemDev(checkItem.getIdCheckItemDev());
    }

    public Solicitud getSolicitud() {
        return solicitud;
    }

    public void setSolicitud(SolicitudDevolucion solicitud) {
        this.solicitud = solicitud;
        setIdSolicitud(solicitud.getIdSolicitud());
    }
}
