package gov.sir.core.negocio.modelo;

import gov.sir.core.negocio.modelo.constantes.CSolicitudFolio;

import org.auriga.core.modelo.TransferObject;


/* Generated by JDO Genie (version:3.0.0 (08 Jun 2004)) */

/** Clase que modela la información de folios asociados a la solicitud  */

public class SolicitudFolio implements TransferObject{

    private String idMatricula; // pk 
    private String idSolicitud; // pk 
    private Folio folio;
    private Solicitud solicitud; // inverse Solicitud.solicitudFolios
    private String oficio;
    private Usuario usuario;
	private boolean marcado;
	private int estado=CSolicitudFolio.SIN_ESTADO;
	private boolean recienCreadoAntiguoSistema;
	private String idBusquedaConsulta;
    private String circulo;
    private static final long serialVersionUID = 1L;
	/** Método constructor por defecto  */
    public SolicitudFolio() {
    }

    /** Retorna el identificador del folio  */
    public String getIdMatricula() {
        return idMatricula;
    }

    /** Cambia el identificador del folio  */
    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }

    /** Retorna el identificador de la solicitud  */
    public String getIdSolicitud() {
        return idSolicitud;
    }

    /** Cambia el identificador de la solicitud  */
    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    /** Retorna el identificador del folio  */
    public Folio getFolio() {
        return folio;
    }

    /** Modifica el identificador del folio  */
    public void setFolio(Folio folio) {
        this.folio = folio;
		this.idMatricula = folio.getIdMatricula();
    }

    /** Retorna el identificador de la solicitud */
    public Solicitud getSolicitud() {
        return solicitud;
    }

    /** Modifica el identificador de la solicitud */
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
		this.idSolicitud = solicitud.getIdSolicitud();
    }

    /** Retorna el oficio de pertenencia
	 * @return
	 */
	public String getOficio() {
		return oficio;
	}

	/** Cambia el oficio de pertenencia
	 * @param string
	 */
	public void setOficio(String string) {
		oficio = string;
	}

	/**
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object obj) {
		if(obj instanceof SolicitudFolio){
			SolicitudFolio sfolio=(SolicitudFolio)obj;
			return (sfolio.idMatricula.equals(this.idMatricula))&&
			(sfolio.idSolicitud.equals(this.idSolicitud));
		}
		else
			return false;
	}

	/** Retorna el identificador del usuario
	 * @return
	 */
	public Usuario getUsuario() {
		return usuario;
	}

	/** Cambia el identificador del usuario
	 * @param usuario
	 */
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	/** Indica que el folio en la solicitud se encuentra marcado
	 * @return
	 */
	public boolean isMarcado() {
		return marcado;
	}

	/** Modifica la marca que indica que el folio en la solicitud se encuentra marcado
	 * @param b
	 */
	public void setMarcado(boolean b) {
		marcado = b;
	}

	/** Indica que el folio est recien creado en antiguo sistema
	 * @return recienCreadoAntiguoSistema
	 */
	public boolean isRecienCreadoAntiguoSistema() {
		return recienCreadoAntiguoSistema;
	}

	/** Modifica la marca que indica que el folio est recien creado en antiguo sistema
	 * @param b
	 */
	public void setRecienCreadoAntiguoSistema(boolean b) {
		recienCreadoAntiguoSistema = b;
	}

	/** Retorna el identificador de la búsqueda de la cual se anexa el folio
	 * @return idBusquedaConsulta
	 */
	public String getIdBusquedaConsulta() {
		return idBusquedaConsulta;
	}

	/** Cambia el identificador de la búsqueda de la cual se anexa el folio
	 * @param string
	 */
	public void setIdBusquedaConsulta(String string) {
		idBusquedaConsulta = string;
	}

	public int getEstado() {
		return estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public String getCirculo() {
		return circulo;
	}

	public void setCirculo(String circulo) {
		this.circulo = circulo;
	}

}