package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/** Clase que modela las relaciones entre las solicitudes vinculadas de registro */

 /* Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class SolicitudVinculada implements TransferObject {

    private String idSolicitud; // pk 
    private String idSolicitud1; // pk 
    private Date fechaCreacion;
    private Solicitud solicitudHija;
    private Solicitud solicitudPadre; // inverse SolicitudEnhanced.solicitudesVinculadas
    private static final long serialVersionUID = 1L;
    /**Metodo constructor por defecto */
    public SolicitudVinculada() {
    }

    /** Retorna el identificador de la solicitud vinculada padre */
    public String getIdSolicitud() {
        return idSolicitud;
    }
    /** Modifica el identificador de la solicitud vinculada padre */
    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    /** Retorna el identificador de la solicitud vinculada padre */
    public String getIdSolicitud1() {
        return idSolicitud1;
    }
    /** Modifica el identificador de la solicitud vinculada padre */
    public void setIdSolicitud1(String idSolicitud1) {
        this.idSolicitud1 = idSolicitud1;
    }

    /** Retorna la fecha de creacion del registro en la base de datos  */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }
    /** Modifica la fecha de creacion del registro en la base de datos  */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /** Retorna el identificador de la solicitud vinculada hija  */
    public Solicitud getSolicitudHija() {
        return solicitudHija;
    }
    /** Cambia el identificador de la solicitud vinculada hija  */
    public void setSolicitudHija(Solicitud solicitudHija) {
        this.solicitudHija = solicitudHija;
		setIdSolicitud1(solicitudHija.getIdSolicitud());
    }
    /** Retorna el identificador de la solicitud vinculada padre */
    public Solicitud getSolicitudPadre() {
        return solicitudPadre;
    }
    /** Modifica el identificador de la solicitud vinculada padre */
    public void setSolicitudPadre(Solicitud solicitudPadre) {
        this.solicitudPadre = solicitudPadre;
        setIdSolicitud(solicitudPadre.getIdSolicitud());
    }
}
