package gov.sir.core.negocio.modelo;


import org.auriga.core.modelo.TransferObject;

/** Clase que modela los subtipos de atencion con los 
 * subtipos de solicitud configurados en el sistema */
/*
 * Generated by JDO Genie (version:3.2.0beta7 (20 Sep 2004))
 */
public class SubAtencionSubSolicitud  implements TransferObject {

    private String idSubtipoAtencion; // pk 
    private String idSubtipoSol; // pk 
    private SubtipoAtencion subtipoAtencion; // inverse SubtipoAtencionEnhanced.subtipoSolicitudes
    private SubtipoSolicitud subtipoSolicitud;
    private static final long serialVersionUID = 1L;
    /** Metodo constructor por defecto */
    public SubAtencionSubSolicitud() {
    }

    /** Retorna el identificador del subtipo de atencion  */
    public String getIdSubtipoAtencion() {
        return idSubtipoAtencion;
    }
    
    /** Modifica el identificador del subtipo de atencion  */
    public void setIdSubtipoAtencion(String idSubtipoAtencion) {
        this.idSubtipoAtencion = idSubtipoAtencion;
    }

    /** Retorna el identificador del subtipo de solicitud  */
    public String getIdSubtipoSol() {
        return idSubtipoSol;
    }
    
    /** Modifica el identificador del subtipo de solicitud  */
    public void setIdSubtipoSol(String idSubtipoSol) {
        this.idSubtipoSol = idSubtipoSol;
    }

    /** Retorna el identificador del subtipo de atencion  */
    public SubtipoAtencion getSubtipoAtencion() {
        return subtipoAtencion;
    }

    /** Modifica el identificador del subtipo de atencion  */
    public void setSubtipoAtencion(SubtipoAtencion subtipoAtencion) {
        this.subtipoAtencion = subtipoAtencion;
        setIdSubtipoAtencion(subtipoAtencion.getIdSubtipoAtencion());
    }

    /** Retorna el identificador del subtipo de solicitud  */
    public SubtipoSolicitud getSubtipoSolicitud() {
        return subtipoSolicitud;
    }

    /** Modifica el identificador del subtipo de solicitud  */
    public void setSubtipoSolicitud(SubtipoSolicitud subtipoSolicitud) {
        this.subtipoSolicitud = subtipoSolicitud;
        setIdSubtipoSol(subtipoSolicitud.getIdSubtipoSol());
    }
}