package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/** Clase que modela los subtipos de atencion configurados en el sistema */
/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class SubtipoAtencion implements TransferObject {
    private String idSubtipoAtencion; // pk 
    private long minAnotaciones;
    private String nombre;
    private long orden;
    private long unidadesTrabajo;
    private List tiposActo = new ArrayList(); // contains SubtipoAtencionTipoActo  inverse SubtipoAtencionTipoActo.subtipoAtencion
    private List subtipoSolicitudes = new ArrayList(); // contains SubAtencionSubSolicitudEnhanced  inverse SubAtencionSubSolicitudEnhanced.subtipoAtencion
	private long minFolios;
	private static final long serialVersionUID = 1L;
    /**
         * @param enhanced
         */
    public SubtipoAtencion(String idSubtipoAtencion, long minAnotaciones,
        String nombre, long unidadesTrabajo) {
        this.idSubtipoAtencion = idSubtipoAtencion; // pk 
        this.minAnotaciones = minAnotaciones;
        this.nombre = nombre;
        this.unidadesTrabajo = unidadesTrabajo;
    }

    /** Metodo constructor por defecto */
    public SubtipoAtencion() {
    }

    /** Retorna el identificador del subtipo de atencion  */
    public String getIdSubtipoAtencion() {
        return idSubtipoAtencion;
    }

    /** Modifica el identificador del subtipo de atencion  */
    public void setIdSubtipoAtencion(String idSubtipoAtencion) {
        this.idSubtipoAtencion = idSubtipoAtencion;
    }

    /** Retorna el numero minimo de anotaciones  */
    public long getMinAnotacione() {
        return minAnotaciones;
    }
    
    /** Modifica el numero minimo de anotaciones  */
    public void setMinAnotacione(long minAnotaciones) {
        this.minAnotaciones = minAnotaciones;
    }
    
    /** Retorna el nombre del subtipo de atencion  */
    public String getNombre() {
        return nombre;
    }

    /** Cambia el nombre del subtipo de atencion  */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** Retorna la prioridad del subtipo de atecion  */
    public long getOrden() {
        return orden;
    }

    /** Modifica la prioridad del subtipo de atecion  */
    public void setOrden(long orden) {
        this.orden = orden;
    }

    /** Retorna las unidades de trabajo  */
    public long getUnidadesTrabajo() {
        return unidadesTrabajo;
    }

    /** Modifica las unidades de trabajo  */
    public void setUnidadesTrabajo(long unidadesTrabajo) {
        this.unidadesTrabajo = unidadesTrabajo;
    }

    /** Retorna la lista tiposActo */
    public List getTiposActos() {
        return Collections.unmodifiableList(tiposActo);
    }

    /** Añade un tipo de acto a la lista tiposActo  */
    public boolean addTiposActo(SubtipoAtencionTipoActo newTiposActo) {
        return tiposActo.add(newTiposActo);
    }

    /** Elimina un tipo de acto a la lista tiposActo  */
    public boolean removeTiposActo(SubtipoAtencionTipoActo oldTiposActo) {
        return tiposActo.remove(oldTiposActo);
    }

    /** Retorna la lista subtipoSolicitudes  */
    public List getSubtipoSolicitudes() {
        return Collections.unmodifiableList(subtipoSolicitudes);
    }

    /** Añade un subtipo de solicitud a la lista subtipoSolicitudes */
    public boolean addSubtipoSolicitude(
        SubAtencionSubSolicitud newSubtipoSolicitude) {
        return subtipoSolicitudes.add(newSubtipoSolicitude);
    }

    /** Elimina un subtipo de solicitud a la lista subtipoSolicitudes */
    public boolean removeSubtipoSolicitude(
        SubAtencionSubSolicitud oldSubtipoSolicitude) {
        return subtipoSolicitudes.remove(oldSubtipoSolicitude);
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }

        if (!(o instanceof SubtipoAtencion)) {
            return false;
        }

        SubtipoAtencion obj = (SubtipoAtencion) o;

        if (obj.getIdSubtipoAtencion() != null) {
            return obj.getIdSubtipoAtencion().equals(this.idSubtipoAtencion);
        }

        return false;
    }
    

	public int hashCode() {
		int result = 0;
		result = (29 * result) +
			((idSubtipoAtencion != null) ? idSubtipoAtencion.hashCode() : 0);

		return result;
	}

    /** Retorna el numero minimo de anotaciones
	 * @return
	 */
	public long getMinAnotaciones() {
		return minAnotaciones;
	}

	/** Modifica el numero minimo de anotaciones
	 * @param l
	 */
	public void setMinAnotaciones(long l) {
		minAnotaciones = l;
	}

	/** Retorna el numero minimo de folios asociados
	 * @return
	 */
	public long getMinFolios() {
		return minFolios;
	}

	/** Cambia el numero minimo de folios asociados
	 * @param l
	 */
	public void setMinFolios(long l) {
		minFolios = l;
	}

}
