package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;

/** Clase que modela la informacion de los documentos radicados  */
/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class TipoDocumento implements TransferObject{
    private String idTipoDocumento; // pk 
    private String nombre;
    private static final long serialVersionUID = 1L;
    /** Metodo constructor por defecto  */
    
    public TipoDocumento() {
    }

    /** Retorna el identificador del documento  */
    
    public String getIdTipoDocumento() {
        return idTipoDocumento;
    }

    /** Modifica el identificador del documento  */
    
    public void setIdTipoDocumento(String idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }

    /** Retorna el nombre del tipo de documento  */
    public String getNombre() {
        return nombre;
    }

    /** Modifica el nombre del tipo de documento  */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}
