package gov.sir.core.negocio.modelo;

import java.util.List;
import java.util.ArrayList;
import java.util.Collections;

import org.auriga.core.modelo.TransferObject;

/** Clase que modela los tipos de acto configurados en el sistema*/

 /* Generated by JDO Genie (version:3.2.0beta7 (20 Sep 2004))*/

public class TipoActo implements TransferObject{

    private String idTipoActo; // pk 
    private boolean impPorCuantia;
    private String nombre;
    private static final long serialVersionUID = 1L;
    private TipoCalculo tipoCalculo;
    private List tiposDerechosRegistrales = new ArrayList(); // contains TipoActoDerechoRegistral  inverse TipoActoDerechoRegistral.tipoActo

    /*
     *@autor          : JATENCIA 
     * @mantis        : 0015082 
     * @Requerimiento : 027_589_Acto_liquidación_copias 
     * @descripcion   : Se adiciona una variable que representa el atributo en
     * la tabla SIR_OP_TIPO_ACTO, para determinar si se encuentra activo el Tipo de Acto.
     * 
     * A la variable " activo " de tipo boolean, se le debe crear su metodo get y set.
     * 
     * P02 - Agragar la vaiable tal cual se crea en la clase dentro del .jdo para el Map 
     * se declara y se indica cual es el atributo de la tabla y sus caracteristicas.
     */
    private boolean activo;
    
    /**
    * @Autor: Santiago Vásquez
    * @Change: 2062.TARIFAS.REGISTRALES.2017
    */
    private boolean incentivoRegistral;

    public boolean isIncentivoRegistral() {
        return incentivoRegistral;
    }

    public void setIncentivoRegistral(boolean incentivoRegistral) {
        this.incentivoRegistral = incentivoRegistral;
    }
    
    public boolean isActivo() {
        return activo;
    }

    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    /* - Fin del bloque - */
    
    /** Metodo constructor por defecto  */
    public TipoActo() {
    }

    /** Retorna el identificador del tipo de acto */
    public String getIdTipoActo() {
        return idTipoActo;
    }

    /** Modifica el identificador del tipo de acto */
    public void setIdTipoActo(String idTipoActo) {
        this.idTipoActo = idTipoActo;
    }
    
    /** Retorna el nombre del tipo de acto  */
    public String getNombre() {
        return nombre;
    }

    /** Modifica el nombre del tipo de acto  */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** Retorna el identificador del tipo de calculo asociado al tipo de acto */
    public TipoCalculo getTipoCalculo() {
        return tipoCalculo;
    }

    /** Modifica el identificador del tipo de calculo asociado al tipo de acto */
    public void setTipoCalculo(TipoCalculo tipoCalculo) {
        this.tipoCalculo = tipoCalculo;
    }

    /** Retorna la lista tipoDerechosRegistrales */
    public List getTiposDerechosRegistrales() {
        return Collections.unmodifiableList(tiposDerechosRegistrales);
    }

    /** Añade un tipo de derecho registral a la lista tipo DerechosRegistrales */
    public boolean addTiposDerechosRegistrale(TipoActoDerechoRegistral newTiposDerechosRegistrale) {
        return tiposDerechosRegistrales.add(newTiposDerechosRegistrale);
    }

    /** Elimina un tipo de derecho registral a la lista tipo DerechosRegistrales */
    public boolean removeTiposDerechosRegistrale(TipoActoDerechoRegistral oldTiposDerechosRegistrale) {
        return tiposDerechosRegistrales.remove(oldTiposDerechosRegistrale);
    }

    /** Indica si el tipo de acto tiene impuesto por cuantia
	 * @return
	 */
	public boolean isImpPorCuantia() {
		return impPorCuantia;
	}

	/** Modifica el flag que indica si el tipo de acto tiene impuesto por cuantia
	 * @param b
	 */
	public void setImpPorCuantia(boolean b) {
		impPorCuantia = b;
	}

}
