package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/** Clase que modela los tipos de recursos configurados en el sistema */
/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class TipoRecurso  implements TransferObject{

    private String idTipoRecurso; // pk 
    private String descripcion;
    private Date fechaCreacion;
    private static final long serialVersionUID = 1L;
    /** Metodo constructor por defecto  */
    
    public TipoRecurso() {
    }

    /** Retorna el identificador del tipo de recurso */
    
    public String getIdTipoRecurso() {
        return idTipoRecurso;
    }

    /** Modifica el identificador del tipo de recurso */
    
    public void setIdTipoRecurso(String idTipoRecurso) {
        this.idTipoRecurso = idTipoRecurso;
    }

    /** Retorna la descripcion del tipo de recurso */
    
    public String getDescripcion() {
        return descripcion;
    }

    /** Modifica la descripcion del tipo de recurso */
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /** Retorna la fecha de creacion del registro en la base de datos  */
    
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /** Modifica la fecha de creacion del registro en la base de datos  */
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
}
