package gov.sir.core.negocio.modelo;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.auriga.core.modelo.TransferObject;

/** Clase que modela los tipos de certificados configurados en el sistema */
/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class TipoCertificado implements TransferObject{

	
    private String idTipoCertificado; // pk 
    private String nombre;
    private static final long serialVersionUID = 1L;
    /**
    * Flag que indica si el tipo de certificado está asociado con el proceso de 
    * certificados individuales.  
    */
    private boolean flagIndividual;
    
	private List validaciones = new ArrayList(); // contains TipoCertificadoValidacion  inverse TipoCertificadoValidacion.tipoCertificado

	/** Metodo constructor por defecto */
    public TipoCertificado() {
    }

    /** Retorna el identificador del tipo de certificado  */
    public String getIdTipoCertificado() {
        return idTipoCertificado;
    }

    /** Modifica el identificador del tipo de certificado  */
    
    public void setIdTipoCertificado(String idTipoCertificado) {
        this.idTipoCertificado = idTipoCertificado;
    }

    /** Retorna el nombre del tipo de certificado */
    public String getNombre() {
        return nombre;
    }

    /** Modifica el nombre del tipo de certificado */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
	
	/**
	* Asocia al atributo flagIndividual, el valor recibido como parámetro. 
	* @param flag booleano que será asignado al atributo flagIndividual,
	* <code>true</code> si el tipo de certificado está asociado con el proceso de 
	* certificados individuales, o <code>false</code> en caso contrario. 
	*/
	public void setFlagIndividual (boolean flag) {
		   this.flagIndividual = flag;
	   }

	
	
	/**
	* Obtiene el valor del atributo flagIndividual asociado con el tipo de certificado. 
	*/
	public boolean getFlagIndividual() {
		return flagIndividual;
	}
    
	/** Retorna la lista validaciones */
	public List getValidaciones() {
		 return Collections.unmodifiableList(validaciones);
	 }

	/** Añade una validacion a la lista validaciones  */
	 public boolean addValidacion(TipoCertificadoValidacion newValidacione) {
		 return validaciones.add(newValidacione);
	 }

	 /** Elimina una validacion a la lista validaciones   */
	 public boolean removeValidacion(TipoCertificadoValidacion oldValidacione) {
		 return validaciones.remove(oldValidacione);
	 }
}