package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/** Clase que modela el registro de los turnos en que se crean las salvedades de folios */
/*
 * Generated by JDO Genie (version:3.2.0beta7 (20 Sep 2004))
 */
public class TurnoSalvedadFolio implements TransferObject{

    private String anio; // pk 
    private String idCirculo; // pk 
    private String idMatricula; // pk 
    private long idProceso; // pk 
    private String idSalvedadFo; // pk 
    private String idTurno; // pk 
    private Date rrsfFechaCreacion;
    private SalvedadFolio salvedad; // inverse SalvedadFolio.turnoSalvedadFolio
    private Turno turno;
    private static final long serialVersionUID = 1L;
    /** Metodo constructor por defecto  */
    
    public TurnoSalvedadFolio() {
    }

    /** Retorna el identificador del turno correspondiente al anio  */
    
    public String getAnio() {
        return anio;
    }

    /** Modifica el identificador del turno correspondiente al anio  */
    
    public void setAnio(String anio) {
        this.anio = anio;
    }

    /** Retorna el identificador del turno correspondiente al circulo  */
    
    public String getIdCirculo() {
        return idCirculo;
    }

    /** Modifica el identificador del turno correspondiente al circulo  */
    
    public void setIdCirculo(String idCirculo) {
        this.idCirculo = idCirculo;
    }

    /** Retorna el identificador de la salvedad de folio correspondiente a la matricula */
    
    public String getIdMatricula() {
        return idMatricula;
    }

    /** Modifica el identificador de la salvedad de folio correspondiente a la matricula */
    
    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }

    /** Retorna el identificador del turno correspondiente al proceso  */
    
    public long getIdProceso() {
        return idProceso;
    }

    /** Modifica el identificador del turno correspondiente al proceso  */
    
    public void setIdProceso(long idProceso) {
        this.idProceso = idProceso;
    }

    /** Retorna el identificador de la salvedad de folio  */
    
    public String getIdSalvedadFo() {
        return idSalvedadFo;
    }

    /** Modifica el identificador de la salvedad de folio  */
    
    public void setIdSalvedadFo(String idSalvedadFo) {
        this.idSalvedadFo = idSalvedadFo;
    }

    /** Retorna el identificador del turno  */
    
    public String getIdTurno() {
        return idTurno;
    }

    /** Modifica el identificador del turno  */
    
    public void setIdTurno(String idTurno) {
        this.idTurno = idTurno;
    }

    /** Retorna la fecha creacion de registro en la base de datos  */
    
    public Date getRrsfFechaCreacion() {
        return rrsfFechaCreacion;
    }

    /** Modifica la fecha creacion de registro en la base de datos  */
    
    public void setRrsfFechaCreacion(Date rrsfFechaCreacion) {
        this.rrsfFechaCreacion = rrsfFechaCreacion;
    }

    /** Retorna el identificador de la salvedad del folio  */
    
    public SalvedadFolio getSalvedad() {
        return salvedad;
    }

    /** Modifica el identificador de la salvedad del folio  */
    
    public void setSalvedad(SalvedadFolio salvedad) {
        this.salvedad = salvedad;
        setIdMatricula(salvedad.getIdMatricula());
        setIdSalvedadFo(salvedad.getIdSalvedad());
    }

    /** Retorna el identificador del turno relativo al anio, circulo y proceso  */
    
    public Turno getTurno() {
        return turno;
    }

    /** Modifica el identificador del turno relativo al anio, circulo y proceso  */
    
    public void setTurno(Turno turno) {
        this.turno = turno;
        setAnio(turno.getAnio());
        setIdCirculo(turno.getIdCirculo());
        setIdProceso(turno.getIdProceso());
        setIdTurno(turno.getIdTurno());
    }
}