package gov.sir.core.negocio.modelo;

import java.util.Date;
import java.util.List;

import org.auriga.core.modelo.TransferObject;

/** Clase que modela los procesos, fases y respuestas en donde es necesario exigir 
 * nota informativa cuando se avanza un turno  */
/*
 * Generated by Versant Open Access (version:3.2.6 (17 Nov 2004))
 */
public class ValidacionNota implements TransferObject{

    private String idFase; // pk 
    private long idProceso; // pk 
    private String idRespuesta; // pk 
    private Date fechaCreacion;
    private Proceso proceso;
    private boolean validaDetalle;
    private List validacionesNotaDetalle;
    private static final long serialVersionUID = 1L;
    /** Metodo constructor por defecto  */
    
    public ValidacionNota() {
    }

    /** Retorna el identificador de la fase  */
    
    public String getIdFase() {
        return idFase;
    }

    /** Modifica el identificador de la fase  */
    
    public void setIdFase(String idFase) {
        this.idFase = idFase;
    }

    /** Retorna el identificador del proceso   */
    
    public long getIdProceso() {
        return idProceso;
    }

    /** Modifica el identificador del proceso   */
    
    public void setIdProceso(long idProceso) {
        this.idProceso = idProceso;
    }

    /** Retorna la respuesta de avance de workflow  */
    
    public String getIdRespuesta() {
        return idRespuesta;
    }

    /** Modifica la respuesta de avance de workflow  */
    
    public void setIdRespuesta(String idRespuesta) {
        this.idRespuesta = idRespuesta;
    }

    /** Retorna la fecha de creacion del registro en la base de datos  */
    
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /** Modifica la fecha de creacion del registro en la base de datos  */
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /** Retorna el identificador del proceso  */
    
    public Proceso getProceso() {
        return proceso;
    }

    /** Modifica el identificador del proceso  */
    
    public void setProceso(Proceso proceso) {
        this.proceso = proceso;
        setIdProceso(proceso.getIdProceso());
    }

    public List getValidacionesNotaDetalle() {
		return validacionesNotaDetalle;
	}

	public void setValidacionesNotaDetalle(List validacionesNotaDetalle) {
		this.validacionesNotaDetalle = validacionesNotaDetalle;
	}

	public boolean isValidaDetalle() {
		return validaDetalle;
	}

	public void setValidaDetalle(boolean validaDetalle) {
		this.validaDetalle = validaDetalle;
	}
}