package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;

/** Clase que modela las veredas configuradas en el sistema  */
/*
 * Generated by JDO Genie (version:3.0.0 (08 Jun 2004))
 */
public class Vereda implements TransferObject {
    private String idVereda; // pk 
    private String idMunicipio; //pk
    private String idDepartamento; //pk
    private String nombre;
    private Municipio municipio; // inverse Municipio.veredas
    private boolean cabecera;
    private static final long serialVersionUID = 1L;
    /** Metodo constructor por defecto  */
    
    public Vereda() {
    }

    /** Retorna el identificador de la vereda  */
    
    public String getIdVereda() {
        return idVereda;
    }

    /** Modifica el identificador de la vereda  */
    
    public void setIdVereda(String idVereda) {
        this.idVereda = idVereda;
    }

    /** Retorna el nombre de la vereda  */
    
    public String getNombre() {
        return nombre;
    }

    /** Modifica el nombre de la vereda  */
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** Retorna el identificador del municipio asociado  */
    
    public Municipio getMunicipio() {
        return municipio;
    }

    /** Modifica el identificador del municipio asociado  */
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
        this.setIdMunicipio(municipio.getIdMunicipio());
        this.setIdDepartamento(municipio.getIdDepartamento());
    }


   /** Retorna el identificador del departamento asociado
	 * @return
	 */
	public String getIdDepartamento() {
		return idDepartamento;
	}

	/** Retorna el identificador del municipio asociado
	 * @return
	 */
	public String getIdMunicipio() {
		return idMunicipio;
	}

	/** Modifica el identificador del departamento asociado
	 * @param string
	 */
	public void setIdDepartamento(String string) {
		idDepartamento = string;
	}

	/** Modifica el identificador del municipio asociado
	 * @param string
	 */
	public void setIdMunicipio(String string) {
		idMunicipio = string;
	}

	/** Indica si la vereda es cabecera municipal
	 * @return
	 */
	public boolean isCabecera() {
		return cabecera;
	}

	/** Modifica el flag que indica si la vereda es cabecera municipal
	 * @param b
	 */
	public void setCabecera(boolean b) {
		cabecera = b;
	}

}
