package gov.sir.core.negocio.modelo;

import org.auriga.core.modelo.TransferObject;


/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class WebDireccion implements TransferObject{

    private String idSolicitud; // pk
    private String idWebDireccion; // pk
    private String idWebSegeng; // pk
    private String idEje1;
    private String idEje2;
    private String valorEje1;
    private String valorEje2;
    private WebFolioNuevo folioNuevo; // inverse WebFolioNuevoEnhanced.direcciones
    private String especificacion;
    private static final long serialVersionUID = 1L;
    public String getEspecificacion() {
		return especificacion;
	}

	public void setEspecificacion(String especificacion) {
		this.especificacion = especificacion;
	}

	public WebDireccion() {
    }

    public String getIdSolicitud() {
        return idSolicitud;
    }

    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public String getIdWebDireccion() {
        return idWebDireccion;
    }

    public void setIdWebDireccion(String idWebDireccion) {
        this.idWebDireccion = idWebDireccion;
    }

    public String getIdWebSegeng() {
        return idWebSegeng;
    }

    public void setIdWebSegeng(String idWebSegeng) {
        this.idWebSegeng = idWebSegeng;
    }

    public String getIdEje1() {
        return idEje1;
    }

    public void setIdEje1(String idEje1) {
        this.idEje1 = idEje1;
    }

    public String getIdEje2() {
        return idEje2;
    }

    public void setIdEje2(String idEje2) {
        this.idEje2 = idEje2;
    }

    public String getValorEje1() {
        return valorEje1;
    }

    public void setValorEje1(String valorEje1) {
        this.valorEje1 = valorEje1;
    }

    public String getValorEje2() {
        return valorEje2;
    }

    public void setValorEje2(String valorEje2) {
        this.valorEje2 = valorEje2;
    }

    public WebFolioNuevo getFolioNuevo() {
        return folioNuevo;
    }

    public void setFolioNuevo(WebFolioNuevo folioNuevo) {
        this.folioNuevo = folioNuevo;
        setIdSolicitud(folioNuevo.getIdSolicitud());
        setIdWebSegeng(folioNuevo.getIdWebSegeng());
    }
}
