package gov.sir.core.negocio.modelo;

import java.util.Date;

import org.auriga.core.modelo.TransferObject;

/*
 * Generated by Versant Open Access (version:3.2.18 (15 Jun 2005))
 */
public class WebFolioDerivado implements TransferObject{

    private String idSolicitud; // pk
    private String idWebFolioDerivado; // pk
    private String idWebSegeng; // pk
    private String area;
    private String hectareas;
    private String metros;
    private String centimetros;
    private String privMetros;
    private String privCentimetros;
    private String consMetros;
    private String consCentimetros;
    private String determinaInm;
    private Date fechaCreacion;
    private String inmueble;
    private String porcentaje;
    private WebSegregacion segregacion; // inverse WebSegregacionEnhanced.foliosDerivados
    private int orden;
    private static final long serialVersionUID = 1L;
    public int getOrden() {
		return orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	public WebFolioDerivado() {
    }

    public String getIdSolicitud() {
        return idSolicitud;
    }

    public void setIdSolicitud(String idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    public String getIdWebFolioDerivado() {
        return idWebFolioDerivado;
    }

    public void setIdWebFolioDerivado(String idWebFolioDerivado) {
        this.idWebFolioDerivado = idWebFolioDerivado;
    }

    public String getIdWebSegeng() {
        return idWebSegeng;
    }

    public void setIdWebSegeng(String idWebSegeng) {
        this.idWebSegeng = idWebSegeng;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getHectareas() {
        return hectareas;
    }

    public void setHectareas(String hectareas) {
        this.hectareas = hectareas;
    }

    public String getMetros() {
        return metros;
    }

    public void setMetros(String metros) {
        this.metros = metros;
    }

    public String getCentimetros() {
        return centimetros;
    }
    
    public String getPrivMetros() {
        return privMetros;
    }

    public void setPrivMetros(String privMetros) {
        this.privMetros = privMetros;
    }

    public String getPrivCentimetros() {
        return privCentimetros;
    }

    public void setPrivCentimetros(String privCentimetros) {
        this.privCentimetros = privCentimetros;
    }

    public String getConsMetros() {
        return consMetros;
    }

    public void setConsMetros(String consMetros) {
        this.consMetros = consMetros;
    }

    public String getConsCentimetros() {
        return consCentimetros;
    }

    public void setConsCentimetros(String consCentimetros) {
        this.consCentimetros = consCentimetros;
    }

    public String getDeterminaInm() {
        return determinaInm;
    }

    public void setDeterminaInm(String determinaInm) {
        this.determinaInm = determinaInm;
    }

    public void setCentimetros(String centimetros) {
        this.centimetros = centimetros;
    }
    
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getInmueble() {
        return inmueble;
    }

    public void setInmueble(String inmueble) {
        this.inmueble = inmueble;
    }

    public String getPorcentaje() {
        return porcentaje;
    }

    public void setPorcentaje(String porcentaje) {
        this.porcentaje = porcentaje;
    }

    public WebSegregacion getSegregacion() {
        return segregacion;
    }

    public void setSegregacion(WebSegregacion segregacion) {
        this.segregacion = segregacion;
        setIdSolicitud(segregacion.getIdSolicitud());
        setIdWebSegeng(segregacion.getIdWebSegeng());
    }
}
